### ISSUE TITLE
maybe bug in Base.results about loose ?

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#102]
code as below:
"""
            if nudged is True and self.loose is False:
                blast_results[query_id] = loose
            elif self.loose is True:
                blast_results[query_id] = loose

"""
self.loose  t didn't work. ...

**Comment by huynhw1** [comment]
Hey there @feihongloveworld ,

Just so I can help you better, can you please describe what you are trying to do?
This would help me narrow down what's happening and if it's a bug or not.

Thank you!
-----
William Huynh, CARD Curator-Developer

**Comment by feihongloveworld** [comment]
> Hey there @feihongloveworld ,
> 
> Just so I can help you better, can you please describe what you are trying to do?
> This would help me narrow down what's happening and if it's a bug or not.
> 
> ## Thank you!
> William Huynh, CARD Curator-Developer
