### ISSUE TITLE
a confusion about rRNA gene variant model

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#104]
hi sir：
  The sequence from model_id: 2820, accession:NR_076160.1.
  There six clinical snp descript in card.json,: "A2109C"，"A2663C"，"T2611C"， "A2057G"，"A2059G"，"C196A".
  But the 2109 is 'A'; 2663 is  'C';   2611 is 'A'; 2057 is 'T',2059 is 'G', 196 is 'T'.
Considering the possibility of reverse complementary sequence：2019 is ‘G’，2663 is ‘T’，2611 is 'C', 2057 is 'A', '2059' is 'A', 196 is 'C'.
if sequence is Forward sequence，2663-2611-2057-2059-194 are wrong,
if sequence is reverse complementary sequence, 2019-2663-2611 are wrong.
I don't quite understand，i need your help.
thanks.

**Comment by huynhw1** [comment]
Hey there @feihongloveworld !

The mutations presented in the papers are in E. coli numbering. Aligning E. coli 23s rRNA with Chlamydia trachomatis 23s rRNA and looking at the numbering would show you that the equivalent of for example: A2059C in E. coli would be A2109C in Chlamydia trachomatis.

Thank you!
-------

William Huynh, CARD Curator-Developer

**Comment by feihongloveworld** [comment]
hi @huynhw1 :
  if A2059G is mutation in E. coli sequence,it maybe error that  code of  RGI Main RrnaModel.py use this snp (A2059G) position to find possible AMR genes.?

**Comment by feihongloveworld** [comment]
hi @huynhw1 ：
   i check all rRNA variant model seqs to find snp start base was not Consistent with seqs；
  there 12 seqs maybe problem；
  the result as below：
>2076_4136 2076_4136 | model_type_id: 40295 | pass_bit_score: 2700 | SNP: C1192U,C1198U | False,True|
>2149_4142 2149_4142 | model_type_id: 40295 | pass_bit_score: 2700 | SNP: U1482C,U1389C,C1480U | False,True,False|
>2142_4143 2142_4143 | model_type_id: 40295 | pass_bit_score: 2700 | SNP: G1475A,G1475U | False|
>3353_5518 3353_5518 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: C656T | False|
>2792_5678 2792_5678 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: A2330T | False|
>2808_4155 2808_4155 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: G2281A,G2294A,G2295A | True,False,False|
>2816_4161 2816_4161 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: A2266G,A2267G | False,True|
>2810_4156 2810_4156 | model_type_id: 40295 | pass_bit_score: 5700 | SNP: A2271G,A2272G,A2272C,A2058C,A2058G,A2058T,A2059C,A2059G | True,True,True,False|
>2811_4157 2811_4157 | model_type_id: 40295 | pass_bit_score: 5700 | SNP: A2272C,A2274G,A2274U | True,False|
>2817_5408 2817_5408 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: A2125G,A2126G,C2641A,C2641G | True,False,True|
>2820_4165 2820_4165 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: A2109C,A2663C,T2611C,A2057G,A2059G,C196A | True,False,False,False,False,False|
>2823_4167 2823_4167 | model_type_id: 40295 | pass_bit_score: 5000 | SNP: G2057A | False|

**Comment by arpcard** [comment]
Thank you for pointing these out. We will get to fixing them as soon as possible. A2059G is E. coli numbering and is being fixed as we speak.

**Comment by feihongloveworld** [comment]
hi @arpcard 
     In addition to rRNA-Variant-model, Prot-Variant-model and Prot-overexpress-model maybe have same problems .
    Another question.： if SNP has U as C1198U，the python code did not to transformate  U  to ，rgi will miss some good snp。
