### ISSUE TITLE
there is no snp in 3741 of rRNA variant Model from card.3.0.8

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#105]
hi sir:
     there is no snp in 3741 of rRNA variant Model from card.3.0.8;
    it will raise a KeyError: 'snp' when run first time.

**Comment by arpcard** [comment]
Thank you for pointing this out!
We will be looking into this and will tell you as soon as it is resolved.

**Comment by arpcard** [comment]
Issue #109 deals with this problem.
Please have a look at Amos' post. This problem has been addressed in one of the commits.

Closing this issue.
