### ISSUE TITLE
a confusion about  ampicillin/sulbactam not in ARO_category

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#107]
hi @arpcard:
        the category_aro_description of the AMR Gene Family of the model 12,  model_name TEM-126 as below :
'''
 Although the inhibitor-resistant TEM variants are resistant to inhibition by clavulanic acid and sulbactam, thereby showing clinical resistance to the beta-lactam-lactamase inhibitor combinations of amoxicillin-clavulanate (Co-amoxiclav), ticarcillin-clavulanate, and ampicillin/sulbactam
'''
ampicillin-Sulbactam is in category_aro_description ,but not in resistance drug list ?
i have a AST result about  ticarcillin-clavulanate, so how i can get ampicillin-Sulbactam resistence informations?

**Comment by arpcard** [comment]
Hi @feihongloveworld ,

Ampicillin is an type of penicillin which in turn is a type of penam which is in the resistance drug list.
Also, clavulanic acid and sulbactam are beta-lactamase inhibitors that enhance the function of antibiotics when paired. By itself, it is not an antibiotic but paired it is considered an antibiotic adjuvant.

Thank you.

**Comment by feihongloveworld** [comment]
hi  @arpcard ：
     Thanks for the answers.
      ticarcillin-clavulanic was record in the resistance drug list in model 3653，so how can i Easy to get more comprehensive list of antibiotic resistance for a model ？
     The workload will be huge if i check every gene for every possible drug for many samples。
     Can you offer some easy ideas or ways to do this？
thank you very much

**Comment by arpcard** [comment]
Hi @feihongloveworld ,

Instead of checking every gene individually. Perhaps, you can check the drug class for the gene instead.

On the CARD website, if you look at https://card.mcmaster.ca/ontology/36017 which is Drug Class penam, you can see 107 sub-terms. These sub-terms include both the genes and antibiotic.

Hopefully, this will make it easier for you to check for drugs related to the model.

Thank you.

**Comment by feihongloveworld** [comment]
hi @arpcard ：
     wooow,this a good idea. thank you very very much. Is there a way to do this locally in bulk without relying on the website？
   Card maybe the most ideal database for AMR I've ever seen. Thank you for your work.

**Comment by feihongloveworld** [comment]
hi @arpcard ：
    add a small problem，What does that mean of “cvterm_id” in card？
thank you

**Comment by arpcard** [comment]
Hi @feihongloveworld ,

I was just testing a method for bulk searches.
You could write your own bash script to automate searches given a list of model IDs.
The main component that you can use is using "jq".
https://github.com/stedolan/jq/releases

Choose the correct installation for your computer operating system.

You can download the card.json file from the card website.
Place the card.json somewhere you can find easily.

Open your terminal and check if "jq" is functional.

Type in:

jq '."<model_id>"' ~/PATH/TO/CARD.JSON

In place of <model_id> substitute your the model number. Replace ~/PATH/TO/CARD.JSON to the path which your card.json is found. Hit enter.
Doing so will output information into your terminal listing all the related info including the antibiotics.

Example:

jq '."3653"' ~Desktop/card/card.json

Let me know if you have any issues.

As for cvterm_id, that is mostly for our database management. It allows us to see what terms relate to others. You do not need to worry about that.

Thank you.

**Comment by arpcard** [comment]
[example_output.txt](https://github.com/arpcard/rgi/files/4635286/example_output.txt)

This is an example of what your output should look like.

Cheers.
