### ISSUE TITLE
Conflict between RGI and Antimicrobial susceptibility test

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#110]
hi @arpcard 
    i get a AMR(amrA, modelid:1405),which its drug class contains amikacin，
but the AST result show that the sample(Acinetobacter_baumannii, contig also blastn to Acinetobacter_baumannii) sensitive to amikacin。
   How should I explain this result?
thank you.

**Comment by fmaguire** [comment]
Capacity for resistance (a gene in a genome like you detected) and an
actual resistance phenotype in your sample are not guaranteed (e.g., gene
may not be expressed at sufficient levels to confer resistance in your
sample, gene may require other genes as well be effective). This is
especially the case for efflux resistance mechanisms.  There is an
extensive amount of literature on how well resistance phenotypes can be
predicted from the genome that you should review.

This is not an RGI issue but a biological reality issue unfortunately.

**Comment by feihongloveworld** [comment]
@fmaguire 
Thanks for the heads up.   Can you give me some experience and advicem，
thanks

**Comment by fmaguire** [comment]
I've given you sufficient information to perform your own literature review for your specific research question.  Anything more is outwith the scope of this forum, which is for code-related issues.

**Comment by feihongloveworld** [comment]
tank you
