### ISSUE TITLE
[BUG]rgi bwt can not use bwa aligner

### ISSUE THREAD

**Issue by yipukangda** [arpcard/rgi#111]
**Describe the bug**
when using bwt modue with bwa aligner, it returns a warning `E::bwa_idx_load_from_disk] fail to locate the index files`, but not with bowtie2 

**Input**
rgi bwt --read_one ./test.fastq.gz --aligner bwa --output_file rgi_test_bwa --threads 14 --include_wildcard --local --mapq 10 --coverage 50 --clean

**Error log**
[E::bwa_idx_load_from_disk] fail to locate the index files

**CARD Version**
3.0.9

**RGI version**
5.0.1

**Expected behavior**
output card AMR analysis results as manual.

**Comment by raphenya** [comment]
@yipukangda I'm guessing you meant RGI version 5.1.0

**Comment by raphenya** [comment]
@yipukangda This is indeed a bug, there is a missing section for creating the index for `bwa`. Thank you, we will fix and notify you via this issue.
