### ISSUE TITLE
RrnaModel only reports one hit per model

### ISSUE THREAD

**Issue by weizhongli** [arpcard/rgi#114]
When running rgi main command, if the input has multiple contigs that hit a rRNA variant model. RGI only reports one contig for this model. 

I tried to modify the script (RrnaModel.py), it seemed that worked, see my modification at
https://github.com/weizhongli/rgi/commit/06c90e4579808abe093c3c2062bed115a1bf20c2#diff-d3d58fa4a7738c9f7446718dee6de22e

Thanks

**Comment by raphenya** [comment]
Thank you @weizhongli, this is indeed a bug.

**Comment by raphenya** [comment]
@weizhongli Please pull the latest commit and test for me, if you can. Cheers.
