### ISSUE TITLE
missing blast xml file().

### ISSUE THREAD

**Issue by gezmi** [arpcard/rgi#115]
Hi,

I have installed RGI with pip3 and also have blast installed from ncbi-blast+. I have downloaded and locally loaded the card.json file. I am trying to run RGI on the fasta of MH995508 from NCBI database (as a mock example). I give the following command:
`rgi main --input_sequence $PWD/storage/app/public/db/fasta/MH995508.fasta  --output_file test.out  -d plasmid -t contig --local`

The error message:
`ERROR 2020-07-19 01:30:31,257 : failed to write orf file                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                   File "/home/username/.local/lib/python3.6/site-packages/app/RGI.py", line 286, in process_contig                                                                                                                       if os.stat(contig_fsa_file).st_size > 0:                                                                                                                                                                       FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/username/PhpstormProjects/plasmid/MH995508.fasta.temp.contig.fsa'                                                                               ERROR 2020-07-19 01:30:31,261 : missing blast xml file(). Please check if input_type: 'contig' correspond with input file: '/mnt/c/Users/username/PhpstormProjects/plasmid/storage/app/public/db/fasta/MH995508.fasta' or use '--low_quality' flag for short contigs to predicts partial genes.`

Could you help me with troubleshooting this issue? (I even ran the command with sudo to see if it is a permission problem, it did not solve it.)

Thank you!

**Comment by huynhw1** [comment]
Hello @gezmi ,

The first thing that comes to mind is that RGI cannot find your input file. If RGI cannot find the input file, it cannot run prodigal to find the ORF and consequently cannot generate the blast xml file later on hence your xml error.
I suggest making sure your path to file is correct. That should fix your error.

Thank you.

**Comment by MatteoSchiavinato** [comment]
Hi, 

I have a very similar issue, so I think it makes sense to post it here underneath the already existing one. 

I'm running RGI like this (following `rgi load --local -i my_db.json`):

```
[schmat@n322-010 amrPlusPlus]$ rgi main --input_sequence /binfl/lv70694/schmat/chicken/amrPlusPlus/process/F21_E_R3/ExtractMegaresSNPs/SNP_fasta/F21_E_R3.snp.fasta --output_file test.output --local --debug -a diamond 
```

And I get the following error: 

```
INFO 2020-10-11 19:46:42,496 : /binfl/lv70694/schmat/chicken/amrPlusPlus/process/F21_E_R3/ExtractMegaresSNPs/SNP_fasta/F21_E_R3.snp.fasta => None
INFO 2020-10-11 19:46:42,522 : valid nucleotide fasta: {'A': 14, 'T': 21, 'G': 36, 'C': 28, 'N': 1, 'U': 0, 'W': 0, 'S': 0, 'M': 0, 'K': 0, 'R': 0, 'Y': 0, 'B': 0, 'D': 0, 'H': 0, 'V': 0}
INFO 2020-10-11 19:46:42,527 : blast DB exists
INFO 2020-10-11 19:46:42,529 : diamond DB exists
INFO 2020-10-11 19:50:19,279 : minimum sequence length: 30, maximun sequence length 100, number of sequences: 16806161
ERROR 2020-10-11 19:50:19,306 : failed to write orf file
Traceback (most recent call last):
  File "/home/lv70694/schmat/.local/lib/python3.6/site-packages/app/RGI.py", line 286, in process_contig
    if os.stat(contig_fsa_file).st_size > 0:
FileNotFoundError: [Errno 2] No such file or directory: '/binfl/lv70694/schmat/chicken/amrPlusPlus/F21_E_R3.snp.fasta.temp.contig.fsa'
INFO 2020-10-11 19:50:19,309 : run filter
ERROR 2020-10-11 19:50:19,310 : missing blast xml file(). Please check if input_type: 'contig' correspond with input file: '/binfl/lv70694/schmat/chicken/amrPlusPlus/process/F21_E_R3/ExtractMegaresSNPs/SNP_fasta/F21_E_R3.snp.fasta' or use '--low_quality' flag for short contigs to predicts partial genes.
INFO 2020-10-11 19:50:19,310 : Total running time 216.821s
```

The input FASTA file exists, I can open it and browse it. However, RGI does not create this `*fsa` intermediate file. Since my FASTA file contains sequences that are ~100 nt long, I tried to specify `--low_quality` as parameter as well, but it didn't help. 

I have tried looking into `RGI.py` but I did not find anything that could cause this issue. Basically, I provide a FASTA file with ~100 nt long sequences and it doesn't create the `*fsa` intermediate files that are needed for it to generate some results. 

Is there any easy explanation that you may have seen in the past already?

**Comment by MatteoSchiavinato** [comment]
I solved mine. One of the RGI dependencies (prodigal) was not the right version.

**Comment by Hanuphant** [comment]
Hi OP, 

Did you get a solution to this?

**Comment by raphenya** [comment]
closing this issue. @gezmi please re-open if you still have this issue. cheers.
