### ISSUE TITLE
Running rgi through different files in a directory

### ISSUE THREAD

**Issue by ddh8602** [arpcard/rgi#121]
I want to run rgi through different files in a directory as a for loop, I have around 100 genomes of L.monocytogenes in it. If someone has done something similar locally I would appreciate the help. I'm using the following script but I keep getting an error. 
>for file in /home/ddumas/input_rgi/*.fas; do tag=${file%.fas}; rgi main --input_sequence "$file" --output_file /mnt/c/Users/danie/Desktop/output_rgi/"$tag" --input_type contig --local --clean; done

**Comment by fmaguire** [comment]
Hey it is a lot easier to help if the you provide the error message (the Bug Report issue template will prompt you for all the details needed to try and fix an issue).  There is an error in your command as the `$tag` variable will contain the full input path (apart from extension) and be trying to output the results in:
     
      --output_file /mnt/c/Users/danie/Desktop/output_rgi/home/ddumas/input_rgi/FILENAME

To get what I'm assuming was the intended output path, you need to add a basename command to the $tag creation e.g. 

     tag=$(basename "${file%.fasta}")` to get `--output_file output_rgi/FILENAME

It's always worth testing your bash loop by just using echo to output the command you are running e.g.

    for file in /home/ddumas/input_rgi/*.fas; do tag=${file%.fas}; echo "rgi main --input_sequence \"$file\" --output_file output/\"$tag\" --input_type contig --local --clean"; done


If you are also getting an error similar to `ERROR 2020-09-19 10:32:38,208 : [Errno 2] No such file or directory: '$LOCALPATH/localDB/card.json'` then in the folder you are running this command from you need to:

- download the CARD data `https://card.mcmaster.ca/download/0/broadstreet-v3.1.0.tar.bz2` 
- extract it `tar xvf broadstreet-v3.1.0.tar.bz2` 
- and load it into CARD locally `rgi load -i card.json --local` in the directory you are running the for loop command.

**Comment by ddh8602** [comment]
Thank you very much **fmaguire**, I corrected the loop as you mentioned and loaded the card db from the input directory. I will leave the steps bellow if anyone else needs it in the future. 

1. Copy the card.json file or download and extract the card data into the input dir where all your .fas files are.
2. Navigate to the input dir.
2. Load the database ` rgi load -i card.json --local` from there.
3. For loop code to run rgi over all of the files:
`for file in /input_dir_path/*.fas; do tag=$(basename "${file%.fas}"); rgi main --input_sequence "$file" --output_file /output_dir_path/"$tag" --input_type contig --local --clean; done`
