### ISSUE TITLE
RGI couldn't detect mutation in nocode region

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#122]
hi sir:
     RGI couldn't detect mutation in nocode region;
     mutation in promoter regin in Mycobacterium tuberculosis fabG1 confer resistance to isoniazid, RGI disbale do it.

**Comment by raphenya** [comment]
@feihongloveworld Yes, the mutation from this https://card.mcmaster.ca/ontology/43108 are not being predicted yet in RGI. We are working towards this. Cheers.
