### ISSUE TITLE
[BUG]RGI get error with biopython

### ISSUE THREAD

**Issue by VoronDM** [arpcard/rgi#123]
**Describe the bug**
After installation RGI via Conda I tried to run a simple command and got an error.

**Input**
`(RGI) [user@bigmem]$ rgi --help`

**Error log**
```
Traceback (most recent call last):
  File "/export/home/user/miniconda3/envs/RGI/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/export/home/user/miniconda3/envs/RGI/lib/python3.6/site-packages/app/MainBase.py", line 1, in <module>
    from app.settings import *
  File "/export/home/user/miniconda3/envs/RGI/lib/python3.6/site-packages/app/settings.py", line 7, in <module>
    from Bio.Alphabet import generic_dna
  File "/export/home/user/miniconda3/envs/RGI/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**RGI version**
4.2.2

**Desktop (please complete the following information):**
 - OS: Linux 3.10.0-1127.13.1.el7.x86_64

**Additional context**
Python 3.6.12

**Comment by raphenya** [comment]
> After installation RGI via Conda I tried to run a simple command and got an error.

Which steps did you use to install RGI, so that we can reproduce?

**Comment by kirstengott** [comment]
I was also getting this error, and for me the problem was coming from a pip install of biopython, which for some reason was superseding my conda environment's biopython in my path when trying to run rgi.  Uninstalling the pip3 biopython fixed the issue for me: `pip3 uninstall biopython`
