### ISSUE TITLE
RGI can not be install because the error related to the Bio.alphabet

### ISSUE THREAD

**Issue by JALEM1** [arpcard/rgi#124]
Hi, It will be appreciated if you help me to solve this problem

I installed All of the dependencies and when I want to install RGI by the command 
pip3 install git+https://github.com/arpcard/rgi.git,  I get this error that Bio.alphabet has removed from Biopython. I tried with different Biopython versions 1.72 and 1.74 and also 1.78 (I know the Bio alphabet is removed from this version) but I got the same error. 

 from Bio.Alphabet import generic_dna
      File "/home/msoud/.local/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
        "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
    ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-_6_n3gyv-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tetw13zl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-_6_n3gyv-build/

**Comment by raphenya** [comment]
@JALEM1 RGI version 5.1.1 uses biopython version 1.72. Maybe use conda environments?

**Comment by JALEM1** [comment]
At first, I tried with conda to install all of the dependencies and RGI but it not worked and then I try just with pip3 to install RGI

**Comment by raphenya** [comment]
try: 

```
conda create --name rgi --channel bioconda --channel conda-forge --channel defaults rgi=5.1.1
```

**Comment by JALEM1** [comment]
I have installed Biopython 1.72 several times but when I check biopython version is 1.78 which has not Bio.alphabet. How I can solve this problem? and why it is not 1.72

**Comment by raphenya** [comment]
@JALEM1 I suspect conflicting versions maybe try the above command?

**Comment by kirstengott** [comment]
I was also getting a similar error, and for me the problem was coming from a pip install of biopython, which for some reason was superseding my conda environment's biopython in my path when trying to run rgi. Uninstalling the pip3 biopython fixed the issue for me: `pip3 uninstall biopython`

**Comment by raphenya** [comment]
This is resolved as per pull https://github.com/arpcard/rgi/pull/137
