### ISSUE TITLE
[BUG] hit reported that doesnt seem to be a hit

### ISSUE THREAD

**Issue by karchern** [arpcard/rgi#129]
Hi!

**Describe the bug**

I'm using RGI locally (anaconda installed, version 5.1.1) on a metagenome-assembled genome. Things look good, except that I get a hit on an ORF that is reported as 100% identical (in sequence) to a member of CARD. It also says the sequence matches ~30% of the reference sequence. Yet, manual inspection/alignment shows that this sequence bears little to no sequence similarity to the reference sequence. What is going on?

**Input**
`
rgi main -i AlmeidaA_2019__SRR6028284__bin.10.fna -o tmp/AlmeidaA_2019__SRR6028284__bin.10 -t contig -a BLAST -n 4 --clean
`
[AlmeidaA_2019__SRR6028284__bin.10.fna.zip](https://github.com/arpcard/rgi/files/5510137/AlmeidaA_2019__SRR6028284__bin.10.fna.zip)
**output**

ORF_ID gnl|X|AJBNPCAD_5_52 # 57506 # 57715 # -1 # ID=5_52;partial=00;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.505
Predicted_Protein: MKKHDVAYLCRNEGVATLFERTGDIPMSCKLQEWFQGKCMASGNHIRADVFPSGRGLAADGERQALEKL
CARD_Protein_Sequence
MAKILILDDEKEIVSLLSTLLSNEGYEVYEAMSGKESLEIIENNKIDLAILDVMLPDISGFDVLQSIREKQFFPVLMLTARGQDMDKITGLSMGADDYIVKPFNPFEVLARVKTQLRRYQTYNSQSIDETNEYAKNGLNISVNSRKVFLYDEEIKLTPIEFDILWYLCRNEGRVISSEELFEKVWKEDYLENNNTVMAHIAKIREKMHEKPRQPNIIKTVWGVGYTIEK
Best_Identities 100

I also saw that the Best_Hit_Bitscore (~21) is far below the Pass_Bitscore (400). 

**Input file**
The file you used as an input to run the data.
Either paste a sample or upload the file.

**Error log**

Not Applicable

**CARD Version**
3.0.9

**RGI version**
5.1.1

**Expected behavior**

To not have this reported as a hit at all (bitscore below threshold), and if it's reported to have a proper sequence identity value

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
 - Browser Chrome (but this doesn't apply here, I ran everything locally)

**Additional context**
If applicable, include dependency versions such as Biopython version and Python version.

**Comment by huynhw1** [comment]
It seems that your predicted protein sequence is matching with a portion of the card sequence at 30%.

qry: MKKHDVAYLCRNEGVATLFERTGDIPMSCKLQEWFQGKCMASGNHIRADVFPSGRGLAADGERQALEKL
sbj: MAKILILDDEKEIVSLLSTLLSNEGYEVYEAMSGKESLEIIENNKIDLAILDVMLPDISGFDVLQSIREKQFFPVL

These are similar enough that RGI calls a match but in reality they only match 30%.
This is because your query is not long enough for the card sequence, so rather than the aligner performing a whole sequence alignment, it matches your query to the portion of the card sequence it is most similar too.

This is expected, and the bit-score shows that since it is far below the pass bit-score value, it should be ignored.

**Comment by raphenya** [comment]
```
predicted           ------------------------------------------------------------	0
card_reference      MAKILILDDEKEIVSLLSTLLSNEGYEVYEAMSGKESLEIIENNKIDLAILDVMLPDISG	60
                                                                                

predicted           ------------------------------------------------------------	0
card_reference      FDVLQSIREKQFFPVLMLTARGQDMDKITGLSMGADDYIVKPFNPFEVLARVKTQLRRYQ	120
                                                                                

predicted           --------------------------------------MKKHDVAYLCRNEGVATLFERT	22
card_reference      TYNSQSIDETNEYAKNGLNISVNSRKVFLYDEEIKLTPIEFDILWYLCRNEGRVISSEEL	180
                                                          :: . : ******* .   *. 

predicted           GDIPMSCKLQEWFQGKCMASGNHIRADVFPSGRGLAADGE-----------RQALEKL	69
card_reference      FE-------KVWKE-DYLENNNTVMAHIAKIREKMHEKPRQPNIIKTVWGVGYTIEK-	229
                     :       : * : . : ..* : *.:    . :  . .             ::** 
```
The hit `ORF_ID gnl|X|AJBNPCAD_5_52 # 57506 # 57715 # -1` was moved from Loose hits to Strict hit due to the rule we set in RGI. This rule helps identify partials that might be of interest.

**Comment by raphenya** [comment]
So, this is not a bug but I think we might need to update the rule a bit.
