### ISSUE TITLE
Add version tag to docker

### ISSUE THREAD

**Issue by cimendes** [arpcard/rgi#13]
Hello. Thank you for providing a docker image for rgi. Unfortunately the only tag available is the "latest", which makes it hard to control new updates that are made to the container. Could you please use the software version as a tag? Thank you very much .

**Comment by arpcard** [comment]
Thank you, we will work on this.

**Comment by oschwengers** [comment]
As proper version tagging is a must in order to integrate CARD/RGI into automatic pipelines, this would be highly appreciated.

**Comment by raphenya** [comment]
@oschwengers Thank you, we will fix this.

**Comment by raphenya** [comment]
@cimendes @oschwengers Please see https://github.com/arpcard/rgi#run-rgi-from-docker---via-biocontainers-or-quay

@apetkau Thank you!
