### ISSUE TITLE
Is rgi feat for long reads sequence data with high error rate (like nanopore sequencing)

### ISSUE THREAD

**Issue by yipukangda** [arpcard/rgi#132]
I have some long reads meta genome data from nanopore sequencing but with somehow high error rate, while it is hard to assembly for not long enough read length, could I use rgi align bwt model to analysis ARM reads, and if it is better to build a k-mer index with a smaller `k` number, thanks.

**Comment by raphenya** [comment]
@yipukangda We do not have long reads support in `rgi`.

**Comment by raphenya** [comment]
@yipukangda closing this issue, please re-open if you would like.
