### ISSUE TITLE
[BUG]kmer build error

### ISSUE THREAD

**Issue by yipukangda** [arpcard/rgi#136]
**Describe the bug**
build a kmer db with `rgi kmer_build` then meet an error

**Input**
`rgi kmer_build --input_directory ./wildcard \
 --card card_database_v3.1.0.fasta -k 31 --threads 20 --batch_size 100000 --skip`

**Input file**

**Error log**
-- COUNTING KMERS --
Counting single species kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
Counting single genus kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
Counting multi genus kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
Counting chr + plasmid kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
Counting plasmid kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
Counting chromosome kmers...
sh: 1: jellyfish: not found
sh: 1: jellyfish: not found
DONE

`FileNotFoundError: [Errno 2] No such file or directory: './card_db/plasmid_31.out'`

**CARD Version**
3.1.0.

**RGI version**
5.1.1 installed from conda

**Comment by raphenya** [comment]
@yipukangda `jellyfish` dependency is installed separately from `rgi`. You will need `jellyfish` installed to run `rgi kmer_build` and `rgi kmer_query`

**Comment by raphenya** [comment]
@yipukangda closing this issue, please reopen if you have the same issue.
