### ISSUE TITLE
rgi main command causes error "faile to write orf"

### ISSUE THREAD

**Issue by drdee255** [arpcard/rgi#14]
rgi main -i NC_017563.1.fasta -n 4 -o out
ERROR 2018-04-15 01:57:38,128 : failed to write orf file
Traceback (most recent call last):
  File "/home/drdee/miniconda3/lib/python3.6/site-packages/app/RGI.py", line 211, in process_contig
    if os.stat(contig_fsa_file).st_size > 0:

**Comment by arpcard** [comment]
>rgi main -i NC_017563.1.fasta -n 4 -o out
ERROR 2018-04-15 01:57:38,128 : failed to write orf file
Traceback (most recent call last):
File "/home/drdee/miniconda3/lib/python3.6/site-packages/app/RGI.py", line 211, in process_contig
if os.stat(contig_fsa_file).st_size > 0:
FileNotFoundError: [Errno 2] No such file or directory: '/home/drdee/BioVolume/vikas_data/NC_017563.1.fasta.temp.contig.fsa'
ERROR 2018-04-15 01:57:38,128 : missing blast xml file(). Please check if input_type: 'contig' correspond with input file: '/home/drdee/BioVolume/vikas_data/NC_017563.1.fasta' or use '--low_quality' flag for short contigs to predicts partial genes.

By default rgi will try to predict complete genes. Looks like your input sequence has partial genes, trying using option `--low_quality`
