### ISSUE TITLE
rgi main: no output or error message, program stops immediately 

### ISSUE THREAD

**Issue by womandrea** [arpcard/rgi#142]
When running the given code
```
rgi main -i ~/.../input_file.fasta -o ~/.../out_dir -t read -n 10 --local --clean --low_quality --include_loose
```
The code stops short of running a few seconds (I presume) and provides no given output. Changing that data type (-t parameter) to something like protein or the default contig results in the programming running. I'm wondering if there is something I am missing for running read annotation with RGI. For context, these are long-read sequences that have been error corrected with short-read references. 

I am wondering if I should just run them as contigs to circumvent this - however, despite the data being long read the bp length is smaller than nanopore typically provides. I noticed that when I was playing around, using the contig setting applies prodigal to the datasets - if what this does is get a set of putative coding regions from the contigs and solely annotate those against CARD (which I'm assuming is the way the code works, please correct me if I'm wrong) I don't think it'd be appropriate to use that parameter to annotate my reads. Is there a more concrete reason that using the "read" setting for the data type parameter results in no output, and the program immediately "finishing" (with no error message, I'm not sure if it's terminating, quitting, or stops because of something else wrong unrelated to the tag). I think it might be the tag since changing it results in the program moving forward. 

Wondering if it's a bug or something more specific to the data I'm trying to annotate.

**Comment by womandrea** [comment]
As an update, I have run the aforelisted code in debug mode, and this is what I receive as an output: 
```
INFO 2021-02-08 18:14:36,333 : /home/andreaa/BIOL_499/Data/minION_Wastewater_2019_05_09/1WWL/correct_1WWL.fasta => None
INFO 2021-02-08 18:14:36,338 : Fasta
INFO 2021-02-08 18:14:36,338 : blast DB exists
INFO 2021-02-08 18:14:36,338 : diamond DB exists
INFO 2021-02-08 18:14:36,338 : process read
```

The output directory nor any files are formed from this. Hopefully this helps with troubleshooting the issue.

**Comment by raphenya** [comment]
@womandrea This looks like you are using older code which we didn't develop further. Current version for `rgi main` using only `protein` and `contig`.  

>  if what this does is get a set of putative coding regions from the contigs and solely annotate those against CARD (which I'm assuming is the way the code works, please correct me if I'm wrong)

This is correct, for contigs, we use Prodigal to call open reading frames before annotating with CARD

Currently, we do not have support for long reads in `rgi`.

**Comment by raphenya** [comment]
@womandrea closing this issue, please reopen if you have the same issue.
