### ISSUE TITLE
docker image: rgi can't detect input file

### ISSUE THREAD

**Issue by ewissel** [arpcard/rgi#144]
When running the docker rgi, I get an error that rgi cannot detect my file because it does not exist. I've tried the relative path, absolute path, and going into the same directory as the file. Here's the code I've tried:

```
## relative path
docker run finlaymaguire/rgi rgi main -i sim_dat/fasta/contigs.fasta -o rgi_out -t contig 

## absolute path 
docker run finlaymaguire/rgi rgi main -i /home/ewissel/amr-benchmarking/mock_2/sim_dat/fasta/contigs.fasta -o rgi_out -t contig 

## same directory as input file
docker run finlaymaguire/rgi rgi main -i contigs.fasta -o rgi_out -t contig 
```

Now when I run with the absolute path, I get this error:

> ERROR 2021-02-16 15:55:10,514 : input file does not exist: /home/ewissel/amr-benchmarking/mock_2/sim_dat/fasta/contigs.fasta

When I run with a relative path, RGI adds `/data/` to the front of the relative path:

> ERROR 2021-02-16 15:54:22,494 : input file does not exist: /data/sim_dat/fasta/contigs.fasta

I'm not sure why this is happening or how to work around it. I've triple checked and the full path to the file is `/home/ewissel/amr-benchmarking/mock_2/sim_dat/fasta/contigs.fasta`, so it *should* be able to detect it. It doesn't seem like I should have to do anything special for a fasta file to work with RGI. Open to any ideas!

**Comment by fmaguire** [comment]
You need to mount the directory containing your files into docker (a la https://github.com/arpcard/rgi#install-rgi-using-docker-singularity)

```docker run -v $PWD:/data finlaymaguire/rgi rgi main -i /data/contigs.fasta -o /data/rgi_output```

For more information check out the general docker tutorials, there is a ton of great documentation on how to use docker: https://docs.docker.com/storage/volumes/
