### ISSUE TITLE
problem with gzipped files

### ISSUE THREAD

**Issue by klincke** [arpcard/rgi#145]
Hello

I'm trying to run rgi main on gzipped files. That should be possible according to the inbuilt help message:
> Resistance Gene Identifier - 5.1.1 - Main
> optional arguments:
>   -h, --help            show this help message and exit
>   -i INPUT_SEQUENCE, --input_sequence INPUT_SEQUENCE
>                         input file must be in either FASTA (contig and protein) or gzip format! e.g myFile.fasta, myFasta.fasta.gz

But when I try to run it as `rgi main -i sample.contigs.fasta.gz -o sample.card -a DIAMOND -n 2 --clean` I get the following error:
> ERROR 2021-03-08 13:35:24,902 : gz
> ERROR 2021-03-08 13:35:24,902 : application/gzip
> WARNING 2021-03-08 13:35:24,902 : Sorry, no support for this format.

It seems as if the help message and the program features don't fit together. 
Are gzipped files supported or not?

**Comment by raphenya** [comment]
@klincke Sorry there is no support for gzipped files for version 5.1.1. But the latest commit support gzipped inputs.

**Comment by klincke** [comment]
Thanks for the fast reply. I meant gzipped inputs. 
Do I understand the help message from the 5.1.1 version wrong? It says (as I cited earlier) that the input file must be either in FASTA or gzip format and gives the example `myFasta.fasta.gz`. But I cannot run it as `rgi main -i myFasta.fasta.gz -o ...` as I then get the error.

**Comment by klincke** [comment]
Then it might be a good idea to update that as well.
It's too bad that rgi is not supporting gzipped input anymore.

**Comment by raphenya** [comment]
@klincke certainly, the next release will have those corrections.

**Comment by raphenya** [comment]
@klincke version 5.2.0 now has support for gzipped inputs. cheers.
