### ISSUE TITLE
Error loading database

### ISSUE THREAD

**Issue by Somebodyatthdoor** [arpcard/rgi#146]
Hi,

I am receiving an error when I try to load the card database. I have installed rgi using conda with:
conda install --channel bioconda --channel conda-forge --channel defaults rgi=5.1.1

I have obtained the card data using:
wget https://card.mcmaster.ca/latest/data
tar -xvf data ./card.json

But when I try and run "rgi load --card_json card.json --local" I get the error:

Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/rgi/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/rgi/lib/python3.6/site-packages/app/MainBase.py", line 9, in <module>
    import app.build_kmer_sets
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/rgi/lib/python3.6/site-packages/app/build_kmer_sets.py", line 2, in <module>
    import app.make_kmer_json
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/rgi/lib/python3.6/site-packages/app/make_kmer_json.py", line 1, in <module>
    import csv, re, argparse, multiprocessing, math, json, ahocorasick, os, sqlite3
ModuleNotFoundError: No module named 'ahocorasick'

There are a couple of closed issues with this error, and they seem to say that this module comes from pyahocorasick. This package (Version 1.4.0) is definitely present within my conda environment. 

Any advice you could give would be greatly appreciated. 

Laura

**Comment by raphenya** [comment]
@Somebodyatthdoor I did the following on a fresh install on ubuntu machine:
```
$ conda --version
conda 4.9.2

$ conda create --name rgi511 --channel bioconda --channel conda-forge --channel defaults rgi=5.1.1 -y

$ conda init bash

$ conda activate rgi511

$ wget https://card.mcmaster.ca/latest/data && tar -xvf data ./card.json

(rgi511) $ rgi load --card_json card.json --local --debug > log 2>&1

$ cat log 

INFO 2021-03-29 13:57:03,810 : {
  "card_json": "card.json",
  "card_annotation": null,
  "wildcard_annotation": null,
  "wildcard_index": null,
  "wildcard_version": null,
  "baits_annotation": null,
  "baits_index": null,
  "kmer_database": null,
  "amr_kmers": null,
  "kmer_size": null,
  "local_database": true,
  "debug": true
}
INFO 2021-03-29 13:57:04,033 : file card.json loaded ok
INFO 2021-03-29 13:57:04,187 : {
  "card_canonical": {
    "data_version": "3.1.1"
  },
  "card_variants": {
    "data_version": "N/A"
  },
  "card_kmers": {
    "kmer_sizes": []
  }
}

$ pip list
Package         Version
--------------- -------------------
biopython       1.72
certifi         2020.12.5
cycler          0.10.0
filetype        1.0.7
kiwisolver      1.3.1
matplotlib      3.3.4
numpy           1.19.5
olefile         0.46
pandas          1.1.5
patsy           0.5.1
Pillow          8.1.2
pip             21.0.1
pyahocorasick   1.4.0
pyfaidx         0.5.9.5
pyparsing       2.4.7
python-dateutil 2.8.1
pytz            2021.1
RGI             5.1.1
scipy           1.5.3
seaborn         0.11.1
setuptools      49.6.0.post20210108
six             1.15.0
statsmodels     0.12.2
tornado         6.1
wheel           0.36.2
```

I didn't get any errors.

**Comment by Somebodyatthdoor** [comment]
@raphenya Thanks for looking at this. Seems like it is a local issue with our cluster, I've found a work around now.
