### ISSUE TITLE
Different results between BLAST and DIAMOND

### ISSUE THREAD

**Issue by ATVincent** [arpcard/rgi#147]
Hello,

I am using rgi to detect antibiotic resistance genes in a metagenome assembly. Out of curiosity, I did the analysis with BLAST and DIAMOND. Although I expected a few differences, I find a huge disparity between the two methods. I found 583 determinants of antibiotic resistance with BLAST and 82 with DIAMOND.

Here are the commands used:
BLAST:
rgi main --input_sequence Dataset/Assembly.fasta --output_file Result.out --input_type contig --data wgs --num_threads 10 --clean
DIAMOND:
rgi main --input_sequence Dataset/Assembly.fasta --output_file Result.out --input_type contig --data wgs --num_threads 10 --clean --alignment_tool DIAMOND

I'm using rig 5.1.1 (the latest version).

Given this result, I wonder which of the two (BLAST or DIAMOND) gives the better result.

Thank you !

**Comment by raphenya** [comment]
@ATVincent  how many `Perfect`, `Strict`, and `Loose` hits did you get for both?

**Comment by ATVincent** [comment]
For BLAST:
Perfect = 4
Strict = 579
Loose = 0

For Diamond:
Perfect = 4
Strict = 78

**Comment by raphenya** [comment]
@ATVincent Looks like there is a lot of partial hits. Try using `Percentage Length of Reference Sequence` and `Nudged ` columns to assess.

**Comment by ATVincent** [comment]
Hello,

Thanks for the solutions. Indeed, the Percentage Length of Reference Sequence shows many hits with very low values with BLAST, compared to Diamond.
