### ISSUE TITLE
Missing "card.json"

### ISSUE THREAD

**Issue by adam-lab** [arpcard/rgi#15]
Hello. Today, I cloned and installed the command-line version of RGI, using the "pip install ." command, as described on the README. Upon running "pytest -v -rxs" I get the error message "No such file or directory" for the following file:  "rgi/app/_data/card.json".

Is this a file that I need to download separately from the RGI scripts?

Thanks for providing this tool. I'm very excited about it.
Adam

**Comment by arpcard** [comment]
> Upon running "pytest -v -rxs" I get the error message "No such file or directory" for the following file: "rgi/app/_data/card.json".

For testing use `test.sh` instead.

>Is this a file that I need to download separately from the RGI scripts?

Yes, download `card.json` from https://card.mcmaster.ca/download under `Download CARD Data` section

**Comment by JuanmaMedina** [comment]
Thanks for the aclaration! Maybe it is worth to add that information in the homepage, as by default, the user will run the `setup.py` and can find some errors (at least, I did).

**Comment by 7670367** [comment]
I had the same issue today. If test.sh works, I'll suggest a change to the README.

**Comment by neelam19051** [comment]
Hi, i am getting this error, however i have checked card.json is there.Please help me if anyone know anything about it.

rgi main -i  /home/bvs/Neelam/bakta_annotated/fna/P_aeruginosa_KCP_1.fna -o out -t contig
ERROR 2022-09-14 13:44:18,646 : [Errno 2] No such file or directory: '/home/bvs/.local/lib/python3.8/site-packages/app/_data/card.json'


Thank you
