### ISSUE TITLE
How to determine relative abundances for RGI bwt for metagenomics?

### ISSUE THREAD

**Issue by mhmism** [arpcard/rgi#150]
Hello, 

I there a way to calculate relative abundances of the RGI bwt results for downstream samples comparison?

**Comment by lroppolo** [comment]
Also wondering about this. Were you able to find anything to accomplish this? And if so, are you willing to share your solution?

**Comment by VGalata** [comment]
I have the same question. I am wondering whether "All Mapped Reads" from the allele/gene mapping tables could be used to estimate the abundance if normalizing by reference length and the total number of reads.

**Comment by raphenya** [comment]
@mhmism maybe use https://github.com/hallamlab/samsum
