### ISSUE TITLE
docker run -v $PWD:/data finlaymaguire/rgi -h fails on conda run

### ISSUE THREAD

**Issue by Jehops** [arpcard/rgi#152]
Hello,

Today we tried to install rgi using the docker installation instructions, but running `docker run -v $PWD:/data finlaymaguire/rgi -h` fails.

```
jrm@uthyr ~ % sudo docker run -v $PWD:/data finlaymaguire/rgi -h
usage: conda run [-h] [-n ENVIRONMENT | -p PATH] [-v] [--dev]
                 [--debug-wrapper-scripts] [--cwd CWD] [--no-capture-output]
                 [--live-stream]
                 ...
```

System information:
```
jrm@uthyr ~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Comment by fmaguire** [comment]
Ah minor issue in the documentation which I'll fix now.

`docker run -v $PWD:/data finlaymaguire/rgi rgi -h` will work as intended

**Comment by Jehops** [comment]
I thought the `-h` was an argument for `docker run`, but that requires a hostname, so was confused.

Thanks.

**Comment by fmaguire** [comment]
Ah, yes the -h is just to show the other rgi usage information. We did previously have rgi itself as the entrypoint for the container but I thought it made more sense to keep it compatible with the automatically generated biocontainers version from bioconda. 

No worries, always nice to see a fellow Dal person in bioinformatics!
