### ISSUE TITLE
Check help after installation results in error message [BUG]

### ISSUE THREAD

**Issue by merytouceda** [arpcard/rgi#157]
**Describe the bug**
After installation (tried various methods, but here I describe the option using anaconda), help commands return error. 

**Input**
conda create --name rgi --channel bioconda --channel conda-forge -c defaults
conda activate rgi
conda install --channel bioconda --channel conda-forge --channel defaults rgi=5.1.1
rgi --help 
or
rgi load --help

**Input file**
The file you used as an input to run the data.
Either paste a sample or upload the file.

**Error log**
Traceback (most recent call last):
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/rgi/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 1, in <module>
    from app.settings import *
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/rgi/lib/python3.6/site-packages/app/settings.py", line 7, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/u14/mtoucedasuarez/.local/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Additional context**
This is being run in an HPC, the created environment has: 
conda 4.8.3
Python 3.7.3

**Comment by acvill** [comment]
Yours appears to be a duplicate issue, the solution for which is described [here](https://github.com/arpcard/rgi/issues/124#issuecomment-753197048).

Note that I also got this issue with RGI v5.1.1, but it has been resolved in RGI v5.2.0.

**Comment by raphenya** [comment]
> Yours appears to be a duplicate issue, the solution for which is described [here](https://github.com/arpcard/rgi/issues/124#issuecomment-753197048).
> 
> Note that I also got this issue with RGI v5.1.1, but it has been resolved in RGI v5.2.0.

Thanks @acvill
