### ISSUE TITLE
min() arg is an empty sequence

### ISSUE THREAD

**Issue by jhalleran2** [arpcard/rgi#167]
Hello!  I am new to coding and working through the command terminal.  I believe I have loaded RGI and CARD successfully. I was trying to run my first alignment and I yielded this error message: 
![image](https://user-images.githubusercontent.com/91853214/135772549-690066db-2dc9-48cc-aefb-3d97289849a4.png)
I am unsure what this means and how to fix it.  Does anyone has any suggestions?  I really appreciate it! Thank you!

Jen

**Comment by danrlu** [comment]
Thanks! I just ran into the same problem. Very helpful!
