### ISSUE TITLE
Loose hits appear where they shouldn't

### ISSUE THREAD

**Issue by jkibilds** [arpcard/rgi#17]
Hello!
I get a bit confused when I observe loose hits in RGI output when RGI was run without the `--include_loose` option. For example, when I run `rgi main -i Lm78934_S49.a5.contigs.fasta -n 2 -o Lm78934_S49.a5.txt --clean -d wgs` I get [this output](https://github.com/arpcard/rgi/files/2045068/Lm78934_S49.a5.txt).
I am currently using RGI v 4.0.2 and CARD v 2.0.1 but I have also seen this with earlier versions of CARD.
Why do these loose hits make it into the results file and is it ok to just remove those lines if I'm interested in strict and perfect hits? Or are these loose hits very close to the threshold of strict and are therefore worth investigating further?

**Comment by arpcard** [comment]
Yes, this is a bug. We are looking into this.

**Comment by arpcard** [comment]
@jkibilds this issue is resolved now.
