### ISSUE TITLE
[Question]How to visualized .jsons which >20 M except the heatmap tool?

### ISSUE THREAD

**Issue by EugeneAeolus** [arpcard/rgi#170]
**Describe the question**
The file.jsons obtained by gene_sequence always are more than 20 M, obviously I cant visualize through the website. So is there any methods to generate a ring like a CARD website by file.json which larger than 20 M?
Thanks.

**Comment by EorgeKit** [comment]
> @EugeneAeolus Sorry, unfortunately, the wheel is only available on the website. We will work on this in the future. Cheers.

Hi, could you at least provide a link to a code that helps with the plotting of files that are larger than 20MB, like in the website, that'll be very helpful, because the normal visualisation of the json files is pretty much impossible to view

**Comment by raphenya** [comment]
@EorgeKit Your best bet is to write a custom script. Cheers.
