### ISSUE TITLE
[BUG] lxml doesn't install from bioconda rgi-5.2.0

### ISSUE THREAD

**Issue by biobrad** [arpcard/rgi#174]
Hey guys, just a heads up, when installing from bioconda rgi-5.2.0 doesn't install the lxml dependency.
An error is encountered when using auto_load for databases.

I installed lxml and then then it worked fine.

here is the method that i used when I  installed the environment:

$ conda create -n rgi-card -c bioconda rgi=5.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/harbj019/miniconda3/envs/rgi-card

  added / updated specs:
    - rgi=5.2.0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    bamtools-2.5.1             |       h9a82719_9        1012 KB  bioconda
    beautifulsoup4-4.9.3       |     pyhb0f4dca_0          86 KB  conda-forge
    biopython-1.72             |py36h14c3975_1000         2.4 MB  conda-forge
    blast-2.9.0                |  pl526he19e7b1_7        19.5 MB  bioconda
    cryptography-35.0.0        |   py36hb60f036_0         1.5 MB  conda-forge
    diamond-0.8.36             |       h2e03b76_5         508 KB  bioconda
    filetype-1.0.7             |     pyh9f0ad1d_0          13 KB  conda-forge
    kma-1.3.25                 |       h5bf99c6_0         229 KB  bioconda
    libblas-3.9.0              |12_linux64_openblas          12 KB  conda-forge
    libcblas-3.9.0             |12_linux64_openblas          12 KB  conda-forge
    libgfortran-ng-11.2.0      |      h69a702a_11          19 KB  conda-forge
    liblapack-3.9.0            |12_linux64_openblas          12 KB  conda-forge
    libtiff-4.2.0              |       hf544144_3         590 KB  conda-forge
    oligoarrayaux-3.8          |       hc9558a2_0         165 KB  bioconda
    patsy-0.5.2                |     pyhd8ed1ab_0         188 KB  conda-forge
    pyahocorasick-1.4.0        |   py36h8c4c3a4_2          35 KB  conda-forge
    pyfaidx-0.6.3.1            |     pyh5e36f6f_0          29 KB  bioconda
    pyparsing-3.0.6            |     pyhd8ed1ab_0          79 KB  conda-forge
    python_abi-3.6             |          2_cp36m           4 KB  conda-forge
    seaborn-0.11.2             |       hd8ed1ab_0           4 KB  conda-forge
    soupsieve-2.3              |     pyhd8ed1ab_0          33 KB  conda-forge
    statsmodels-0.12.2         |   py36he33b4a0_0        11.4 MB  conda-forge
    tbb-2021.4.0               |       h4bd325d_1         2.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        39.9 MB

here is the error:

(rgi-card) 
harbj019@ssventer ~
$ rgi auto_load
Traceback (most recent call last):
  File "/home/harbj019/miniconda3/envs/rgi-card/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/app/MainBase.py", line 164, in auto_load
    self.auto_load_run(args)
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/app/MainBase.py", line 171, in auto_load_run
    app.auto_load.main(args)
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/app/auto_load.py", line 19, in main
    card_cannonical_version, card_variants_version = get_versions()
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/app/auto_load.py", line 105, in get_versions
    soup = bs(r.content, 'lxml')
  File "/home/harbj019/miniconda3/envs/rgi-card/lib/python3.6/site-packages/bs4/__init__.py", line 246, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

the fix:

(rgi-card) 
harbj019@ssventer ~
$ conda install lxml
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/harbj019/miniconda3/envs/rgi-card

  added / updated specs:
    - lxml

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icu-69.1                   |       h9c3ff4c_0        13.2 MB  conda-forge
    libxml2-2.9.12             |       h885dcf4_1         760 KB  conda-forge
    libxslt-1.1.33             |       h0ef7038_3         521 KB  conda-forge
    lxml-3.8.0                 |           py36_0         3.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        18.3 MB

The following NEW packages will be INSTALLED:

  icu                conda-forge/linux-64::icu-69.1-h9c3ff4c_0
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libxml2            conda-forge/linux-64::libxml2-2.9.12-h885dcf4_1
  libxslt            conda-forge/linux-64::libxslt-1.1.33-h0ef7038_3
  lxml               conda-forge/linux-64::lxml-3.8.0-py36_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
lxml-3.8.0           | 3.8 MB    | ########################################################################################################################################## | 100% 
icu-69.1             | 13.2 MB   | ########################################################################################################################################## | 100% 
libxslt-1.1.33       | 521 KB    | ########################################################################################################################################## | 100% 
libxml2-2.9.12       | 760 KB    | ########################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

re-running auto_load:

rgi auto_load
Directory '/home/harbj019/rgi_autoload_1weogk15' created
=================================== DOWNLOAD CARD CANONICAL DATA ===================================
--2021-11-29 06:36:05--  https://card.mcmaster.ca/download/0/broadstreet-v3.1.4.tar.bz2
Resolving card.mcmaster.ca (card.mcmaster.ca)... 130.113.77.126
Connecting to card.mcmaster.ca (card.mcmaster.ca)|130.113.77.126|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3577605 (3.4M) [application/x-bzip2]
Saving to: '/home/harbj019/rgi_autoload_1weogk15/data'

/home/harbj019/rgi_autoload_1weogk15/data     100%[==============================================================================================>]   3.41M  1.68MB/s    in 2.0s    

2021-11-29 06:36:08 (1.68 MB/s) - '/home/harbj019/rgi_autoload_1weogk15/data' saved [3577605/3577605]

=================================== DOWNLOAD CARD VARIANTS DATA ===================================
--2021-11-29 06:36:09--  https://card.mcmaster.ca/download/6/prevalence-v3.0.9.tar.bz2
Resolving card.mcmaster.ca (card.mcmaster.ca)... 130.113.77.126
Connecting to card.mcmaster.ca (card.mcmaster.ca)|130.113.77.126|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1107447022 (1.0G) [application/x-bzip2]
Saving to: '/home/harbj019/rgi_autoload_1weogk15/variants'

/home/harbj019/rgi_autoload_1weogk15/variants 100%[==============================================================================================>]   1.03G  7.61MB/s    in 3m 16s  

2021-11-29 06:39:27 (5.38 MB/s) - '/home/harbj019/rgi_autoload_1weogk15/variants' saved [1107447022/1107447022]

=================================== CARD CANONICAL ANNOTATIONS ===================================
=================================== CARD VARIANTS ANNOTATIONS ===================================
Done writing wildcard_database_v3.0.9.fasta
=================================== CLEAN OLD DATABASES ===================================
=================================== LOAD DATABASES ===================================
=================================== CHECK LOADED DATABASES ===================================
card_canonical: 3.1.4 | card_variants: 3.0.9 | kmer_sizes: 61
=================================== DONE ===================================

**Comment by innovate-invent** [comment]
If you guys can silver a 5.2.1 release then I will update the bioconda recipe.

**Comment by raphenya** [comment]
@biobrad version 5.2.1 is released. Do you want to switch?
