### ISSUE TITLE
Current bioconda recipe biopython version causing incompatibilities

### ISSUE THREAD

**Issue by fmaguire** [arpcard/rgi#177]
The RGI bioconda recipe currently in bioconda is pinned to biopython 1.72

This is causing incompatible issues installing RGI in conda envs that require newer biopython versions.

Unfortunately, this includes a lot of tools due to biopythons recent compatibility breaking changes (which I believe we fixed in RGI in this repo). 

I think if we just made a 5.2.1 release and updated the conda recipe a lot of this would be solved pretty automatically!

**Comment by raphenya** [comment]
@fmaguire published rgi version 5.2.1 to conda with biopython 1.78, please help me test and let me know. Cheers.

**Comment by FabbriniMarco** [comment]
Hi everyone, 

Just wanted to say i've installed development version 5.2.1 cloning the git, following the instruction and the installation ran flawlessly. It just requires a bit of time for conda hanging on "Solving environment", but after a while it successfully builds the environment. 

For what i've tested so far, everything is fine. And concerning this issue #177, i find **biopython 1.79**

JIC you may want to check it, this is the conda environment built from the conda_env.yml file:

    _libgcc_mutex=0.1=conda_forge
    _openmp_mutex=4.5=1_llvm
    bio=1.3.3=pypi_0
    biopython=1.79=pypi_0
    biothings-client=0.2.6=pypi_0
    brotlipy=0.7.0=py39h27cfd23_1003
    bzip2=1.0.8=h7f98852_4
    c-ares=1.18.1=h7f98852_0
    ca-certificates=2021.10.8=ha878542_0
    certifi=2021.10.8=py39hf3d152e_1
    cffi=1.14.6=py39h400218f_0
    chardet=4.0.0=py39h06a4308_1003
    conda=4.11.0=py39hf3d152e_0
    conda-package-handling=1.7.3=py39h27cfd23_1
    cryptography=3.4.7=py39hd23ed53_0
    icu=68.2=h9c3ff4c_0
    idna=2.10=pyhd3eb1b0_0
    krb5=1.19.2=hcc1bbae_0
    ld_impl_linux-64=2.35.1=h7274673_9
    libarchive=3.5.2=hccf745f_1
    libcurl=7.80.0=h0b77cf5_0
    libedit=3.1.20191231=he28a2e2_2
    libev=4.33=h516909a_1
    libffi=3.3=he6710b0_2
    libgcc-ng=11.2.0=h1d223b6_11
    libiconv=1.16=h516909a_0
    libmamba=0.19.1=h3985d26_0
    libmambapy=0.19.1=py39h8bfa403_0
    libnghttp2=1.46.0=hce63b2e_0
    libsolv=0.7.19=h780b84a_5
    libssh2=1.10.0=ha56f1ee_2
    libstdcxx-ng=11.2.0=he4da1e4_11
    libxml2=2.9.12=h72842e0_0
    llvm-openmp=12.0.1=h4bd325d_1
    lz4-c=1.9.3=h9c3ff4c_1
    lzo=2.10=h516909a_1000
    mamba=0.19.1=py39hfa8f2c8_0
    mygene=3.2.2=pypi_0
    ncurses=6.2=he6710b0_1
    networkx=2.6.3=pypi_0
    numpy=1.22.0=pypi_0
    openssl=1.1.1l=h7f98852_0
    pandas=1.3.5=pypi_0
    pip=21.1.3=py39h06a4308_0
    pybind11-abi=4=hd8ed1ab_3
    pycosat=0.6.3=py39h27cfd23_0
    pycparser=2.20=py_2
    pyopenssl=20.0.1=pyhd3eb1b0_1
    pysocks=1.7.1=py39h06a4308_0
    python=3.9.5=h12debd9_4
    python-dateutil=2.8.2=pypi_0
    python_abi=3.9=2_cp39
    pytz=2021.3=pypi_0
    readline=8.1=h27cfd23_0
    reproc=14.2.3=h7f98852_0
    reproc-cpp=14.2.3=h9c3ff4c_0
    requests=2.25.1=pyhd3eb1b0_0
    ruamel_yaml=0.15.100=py39h27cfd23_0
    setuptools=52.0.0=py39h06a4308_0
    six=1.16.0=pyhd3eb1b0_0
    sqlite=3.36.0=hc218d9a_0
    tk=8.6.10=hbc83047_0
    tqdm=4.61.2=pyhd3eb1b0_1
    tzdata=2021a=h52ac0ba_0
    urllib3=1.26.6=pyhd3eb1b0_1
    wheel=0.36.2=pyhd3eb1b0_0
    xz=5.2.5=h7b6447c_0
    yaml=0.2.5=h7b6447c_0
    yaml-cpp=0.6.3=he1b5a44_4
    zlib=1.2.11=h7b6447c_3
    zstd=1.5.0=ha95c52a_0

Many thanks!

**Comment by raphenya** [comment]
Thanks @FabbriniMarco
