### ISSUE TITLE
Conda envs, solving environment not finished

### ISSUE THREAD

**Issue by dbu008** [arpcard/rgi#178]
Hi All,
I do not know what is going on but I can not create the conda envs with RGI any version.
Do you experience some issues?

Input:
conda create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 

Error:
The Solving environment stage takes forever, two days solving for now, and nothing changes.
I checked with another conda tool and it works perfectly.

I tried with RGI 5.2.1, 5.1.0

I would be glad to get a hint or info what is going on if you know.
I experience the conda solving environment issues only with your RGI.

Thank you a lot,
Dorota

**Comment by danrlu** [comment]
When I tried to install with conda, it cannot be done with 1 line of command. But below worked:
```
conda create --name rgi
conda activate rgi
conda install --channel conda-forge --channel bioconda --channel defaults rgi=5.2.0 
```

I started to do things 1 step at a time for all conda installations since this issue is fairly common among conda packages.

**Comment by dbu008** [comment]
Thank you Danrlu,

of course, I tried many different ways to install RGI.
One way was to create env, activate and then install.
Nothing changed. All options stucked on the "solving environment".

Also as previously I mentioned I am using conda for years and did not experience any issues like with RGI at the moment.

Thank you for your answer.
Best,
Dorota

**Comment by apetkau** [comment]
@dbu008 you may want to try out `mamba` instead of `conda`: https://mamba.readthedocs.io/

```bash
conda install mamba
mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi
```

Mamba handles dependency solving different from conda and can be much faster.

**Comment by dbu008** [comment]
Thank you Apetkau,

I will try mamba:)

Cheers,
Dorota

**Comment by dbu008** [comment]
> @dbu008 you may want to try out `mamba` instead of `conda`: https://mamba.readthedocs.io/
> 
> ```shell
> conda install mamba
> mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi
> ```
> 
> Mamba handles dependency solving different from conda and can be much faster.

It works perfectly:) I will use Mamba from now:)
Thank you a lot :)

**Comment by dbu008** [comment]
> @dbu008 you may want to try out `mamba` instead of `conda`: https://mamba.readthedocs.io/
> 
> ```shell
> conda install mamba
> mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi
> ```
> 
> Mamba handles dependency solving different from conda and can be much faster.

It works perfectly:) I will use Mamba from now:)
Thank you a lot :)

**Comment by raphenya** [comment]
Thank you @apetkau

**Comment by jpjarnoux** [comment]
I had the same problem today and mamba save me. Maybe it could be a good idea to add the mamba solution to install possibilities.
