### ISSUE TITLE
[BUG]Problem with xml file

### ISSUE THREAD

**Issue by Rainjie-afk** [arpcard/rgi#179]
I am trying to run RGI v5.2.1. and also the database is auto_load. But enter-counting these errors. How can i solve this?

rgi main --input_sequence /home/hyj/desktop/test/B_ovtus.fna  -o /home/hyj/desktop/test/B_ovtus -t contig -a blast -n 6 --clean

**Error: NCBI C++ Exception:**
    T0 "/opt/conda/conda-bld/blast_1594418791377/work/blast/c++/src/corelib/ncbistr.cpp", line 6543: Error: ncbi::CUtf8::SymbolToChar() - Failed to convert symbol to requested encoding (m_Pos = 0)
    T0 "/opt/conda/conda-bld/blast_1594418791377/work/blast/c++/src/serial/objostrxml.cpp", line 1507: Error: ncbi::CObjectOStreamXml::WriteClassMember() -  Frame type= eFrameClassMember, Member name= db (m_Pos = 0)
    T0 "/opt/conda/conda-bld/blast_1594418791377/work/blast/c++/src/serial/objostrxml.cpp", line 1488: Error: ncbi::CObjectOStreamXml::WriteClass() -  Frame type= eFrameClass, Object type= BlastOutput (m_Pos = 0)
    T0 "/opt/conda/conda-bld/blast_1594418791377/work/blast/c++/src/serial/objostr.cpp", line 610: Error: ncbi::CObjectOStream::Write() -  Frame type= eFrameNamed, Object type= BlastOutput (m_Pos = 0)

Process Process-1:4:
Traceback (most recent call last):
  File "/home/hyj/miniconda3/envs/rgi5.2.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hyj/miniconda3/envs/rgi5.2.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyj/miniconda3/envs/rgi5.2.1/lib/python3.8/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/hyj/miniconda3/envs/rgi5.2.1/lib/python3.8/site-packages/app/RrnaModel.py", line 38, in run
    for blast_record in blast_records:
  File "/home/hyj/miniconda3/envs/rgi5.2.1/lib/python3.8/site-packages/Bio/Blast/NCBIXML.py", line 800, in parse
    raise ValueError("Your XML file was empty")
**ValueError: Your XML file was empty**

Maybe it's not the same problem like https://github.com/arpcard/rgi/issues/31? I'm not sure. 
Can someone help me deal with it? Many thanks!

**Comment by raphenya** [comment]
@Rainjie-afk this looks like there are some non-ASCII characters in your input or your input fasta is not formatted correctly.

**Comment by raphenya** [comment]
@Rainjie-afk Please re-open if you are still experiencing the same issue. Cheers.
