### ISSUE TITLE
RGI tab fails with KeyError "category_aro_class_name"

### ISSUE THREAD

**Issue by sachalau** [arpcard/rgi#18]
Hello,

I recently updated to RGI 4.0.3 and I am now running rgi tab to produce a tsv from the json results.
However this steps fails with KeyError "category_aro_class_name". By looking at the json indeed there are no fields with this name. 
Thanks a lot for your help,

**Comment by arpcard** [comment]
Which command did you run? By default you should both json and tab files. 
If you can please share the both fasta and json

**Comment by sachalau** [comment]
Sorry this was an error on my side, closing now.
