### ISSUE TITLE
Repetitive matches and abnormal id percentage

### ISSUE THREAD

**Issue by pg42866** [arpcard/rgi#180]
I m trying to use paired-end libraries as input, with no quality control and no assembly to compare with the same metagenomic processed samples. However, I'm getting strange outputs, as they are repetitive (maybe there are multiple reads for the same gene) and the id percentage is mainly lower than zero (?). Is there any way of minimizing these errors for non-processed metagenomic Illumina paired-end samples?

**Comment by raphenya** [comment]
@ pg42866 I don't understand the question. Can you provide commands, too (I'm assuming you are using RGIbwt)
