### ISSUE TITLE
What to look at Best_Hit_Bitscore or Best_Identities?

### ISSUE THREAD

**Issue by elianapc** [arpcard/rgi#181]
I am using RGI to search antimicrobial genes in a bacterial genome (previously assembled), but I am conffused about the result I got. 
How field should I focus to chose the best result? I mean should I focus only in the **Best_Identities** column or should I consider the **Best_Hit_Bitscore and Pass_Bitscore fields**?

For example when I analize the OKPB10 gen and I see a Best_Identities value of 100 I would think that my isolate most likely has that gen, however when I used blast to analize this sequence (my sequence) I got a very good match with a very differente gene. So, should not consider the Best_Identitie value and just focus in Best_Hit_Bitscore?

Thanks!

**Comment by raphenya** [comment]
@elianapc The descriptions of each column is located at https://github.com/arpcard/rgi#rgi-main-tab-delimited-output-details
