### ISSUE TITLE
Exception : <class 'KeyError'> -> '3' -> Model(1366) missing in database. Please generate new database.

### ISSUE THREAD

**Issue by neelam19051** [arpcard/rgi#183]
Hi, i am trying to run rgi  and encountered following error -

rgi main -i /home/bvs/neelam/genome/ffn2/P_aerugionsa_M18.fasta -o out_tf
WARNING 2022-04-25 14:42:46,541 : Exception : <class 'KeyError'> -> '3' -> Model(1366) missing in database. Please generate new database.
WARNING 2022-04-25 14:42:46,541 : Exception : <class 'KeyError'> -> '3' -> Model(1366)
WARNING 2022-04-25 14:42:46,541 : cmx ---> hsp.bits: 24.2534 <class 'float'> ? <class 'str'>

Thank you

**Comment by raphenya** [comment]
@neelam19051 This happen when the sequences were updated with a new CARD release, updating the databases will resolve this issue.

**Comment by peflanag** [comment]
Hi @raphenya this is going to sound like a stupid question but how do I update the database? is there like a rig update database option? I downloaded card-data from the card website and (I think) made a localDB in the directory I'm running card in and it says its v3.2.4 when I run rgi database --version --local

But when I run this command rgi main -i /Volumes/NMRSARL/MiSeqFastQFiles/S_maltophilia/Fasta/2342376.fasta --output_file 2342376 --input_type contig --clean --num_threads 28

I get the following:

WARNING 2022-09-09 09:24:06,538 : Exception : <class 'KeyError'> -> '344' -> Model(1210) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,538 : Exception : <class 'KeyError'> -> '344' -> Model(1210)
WARNING 2022-09-09 09:24:06,539 : novA ---> hsp.bits: 86.6557 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,541 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,541 : Exception : <class 'KeyError'> -> '475' -> Model(1817)
WARNING 2022-09-09 09:24:06,541 : vgaB ---> hsp.bits: 36.965 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,542 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,542 : Exception : <class 'KeyError'> -> '475' -> Model(1817)
WARNING 2022-09-09 09:24:06,542 : vgaB ---> hsp.bits: 30.0314 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,565 : Exception : <class 'KeyError'> -> '5873' -> Model(200) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,566 : Exception : <class 'KeyError'> -> '5873' -> Model(200)
WARNING 2022-09-09 09:24:06,566 : LEN-14 ---> hsp.bits: 25.409 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,566 : Exception : <class 'KeyError'> -> '1898' -> Model(325) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,566 : Exception : <class 'KeyError'> -> '1898' -> Model(325)
WARNING 2022-09-09 09:24:06,567 : LEN-23 ---> hsp.bits: 25.7942 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,567 : Exception : <class 'KeyError'> -> '5855' -> Model(1503) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,567 : Exception : <class 'KeyError'> -> '5855' -> Model(1503)
WARNING 2022-09-09 09:24:06,567 : LEN-4 ---> hsp.bits: 25.409 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,568 : Exception : <class 'KeyError'> -> '1657' -> Model(270) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,568 : Exception : <class 'KeyError'> -> '1657' -> Model(270)
WARNING 2022-09-09 09:24:06,568 : LEN-20 ---> hsp.bits: 25.409 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,568 : Exception : <class 'KeyError'> -> '1424' -> Model(1684) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,569 : Exception : <class 'KeyError'> -> '1424' -> Model(1684)
WARNING 2022-09-09 09:24:06,569 : LEN-18 ---> hsp.bits: 25.409 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,569 : Exception : <class 'KeyError'> -> '1502' -> Model(1110) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,569 : Exception : <class 'KeyError'> -> '1502' -> Model(1110)
WARNING 2022-09-09 09:24:06,569 : LEN-19 ---> hsp.bits: 25.0238 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,577 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,578 : Exception : <class 'KeyError'> -> '475' -> Model(1817)
WARNING 2022-09-09 09:24:06,578 : vgaB ---> hsp.bits: 24.2534 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,581 : Exception : <class 'KeyError'> -> '6042' -> Model(3751) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,581 : Exception : <class 'KeyError'> -> '6042' -> Model(3751)
WARNING 2022-09-09 09:24:06,581 : TEM-181 ---> hsp.bits: 24.6386 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,587 : Exception : <class 'KeyError'> -> '1813' -> Model(1495) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,588 : Exception : <class 'KeyError'> -> '1813' -> Model(1495)
WARNING 2022-09-09 09:24:06,588 : ACT-4 ---> hsp.bits: 27.7202 <class 'float'> ? <class 'str'>
WARNING 2022-09-09 09:24:06,588 : Exception : <class 'KeyError'> -> '3306' -> Model(3306) missing in database. Please generate new database.
WARNING 2022-09-09 09:24:06,589 : Exception : <class 'KeyError'> -> '3306' -> Model(3306)
WARNING 2022-09-09 09:24:06,589 : Exception: <class 'KeyError'> -> '3306' -> model_type: homolog
WARNING 2022-09-09 09:24:06,968 : Exception : <class 'KeyError'> -> '4553' -> Model(489)
WARNING 2022-09-09 09:24:06,969 : Mycobacterium tuberculosis gidB mutation conferring resistance to streptomycin ---> hsp.bits: 24.2534 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:07,037 : Exception : <class 'KeyError'> -> '4553' -> Model(489)
WARNING 2022-09-09 09:24:07,037 : Mycobacterium tuberculosis gidB mutation conferring resistance to streptomycin ---> hsp.bits: 26.9498 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:07,213 : Exception : <class 'KeyError'> -> '5928' -> Model(3628)
WARNING 2022-09-09 09:24:07,213 : Neisseria gonorrhoeae PBP2 conferring resistance to beta-lactam antibiotics ---> hsp.bits: 27.335 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:07,252 : Exception : <class 'KeyError'> -> '2080' -> Model(1432)
WARNING 2022-09-09 09:24:07,252 : Mycobacterium tuberculosis embC mutant conferring resistance to ethambutol ---> hsp.bits: 26.5646 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:07,873 : Exception : <class 'KeyError'> -> '4553' -> Model(489)
WARNING 2022-09-09 09:24:07,873 : Mycobacterium tuberculosis gidB mutation conferring resistance to streptomycin ---> hsp.bits: 31.5722 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:09,221 : Exception : <class 'KeyError'> -> '4553' -> Model(489)
WARNING 2022-09-09 09:24:09,221 : Mycobacterium tuberculosis gidB mutation conferring resistance to streptomycin ---> hsp.bits: 26.1794 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:10,676 : Exception : <class 'KeyError'> -> '5973' -> Model(3654)
WARNING 2022-09-09 09:24:10,676 : Neisseria gonorrhoeae gyrB conferring resistance to zoliflodacin ---> hsp.bits: 26.1794 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:10,882 : Exception : <class 'KeyError'> -> '5978' -> Model(3649)
WARNING 2022-09-09 09:24:10,882 : Neisseria gonorrhoeae mtrR with mutation conferring resistance ---> hsp.bits: 46.595 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:10,953 : Exception : <class 'KeyError'> -> '5928' -> Model(3628)
WARNING 2022-09-09 09:24:10,953 : Neisseria gonorrhoeae PBP2 conferring resistance to beta-lactam antibiotics ---> hsp.bits: 357.066 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:11,470 : Exception : <class 'KeyError'> -> '4553' -> Model(489)
WARNING 2022-09-09 09:24:11,470 : Mycobacterium tuberculosis gidB mutation conferring resistance to streptomycin ---> hsp.bits: 74.3294 <class 'float'> ? <class 'float'>
WARNING 2022-09-09 09:24:14,388 : Exception : <class 'KeyError'> -> '5928' -> Model(3628)
WARNING 2022-09-09 09:24:14,389 : Neisseria gonorrhoeae PBP2 conferring resistance to beta-lactam antibiotics ---> hsp.bits: 27.335 <class 'float'> ? <class 'float'>

**Comment by BGI-Alpacas** [comment]
I lowered the version to 5.1.1 to solve this problem
