### ISSUE TITLE
 invalid protein fasta due to: '*'

### ISSUE THREAD

**Issue by TKsh6** [arpcard/rgi#184]
**Describe the bug**
The results from` prodigal` must contain "*", but `rgi` cannot recognize it? so how can I fix it?

**Input**
`rgi main --input_sequence ~/h/20220423/com/9_prodigal_res/2_prodigal_res/${bin_id}/${bin_id}.faa --output_file ~/h/20220423/com/9_prodigal_res/6_rgi_res/${bin_id}.out --local --input_type protein --clean -a diamond `

**Input file**
>k141_67634_3 # 1387 # 2484 # -1 # ID=1_3;partial=00;start_type=GTG;rbs_motif=AGxAGG/AGGxGG;rbs_spacer=5-10bp;gc_cont=0.545
MRFNINKSELLNALTIVSKGTASRSTIPVLSGVYIKAEGMGLVMETTDLERSIRYSVPAL
VEEEGTTVIPEKLLLDIVKNLPEAAVEFQTNDSTVTVSCGKSSFTLKTLDAADFPPFPNV
DVSSSIEVPFAEFCSMVKRVAKVVSKDQSRAVLTGVLISTSEEGLRMVATDSYRLAVADI
ALEGVQENFEAIVSGVFLQEVAGLPKMEENITIGLTANQIVFTYQNMVLINRRIEGNFPN
YRQIIPQSWATKTCFTTQELITAVKRVGLVSALSSPVKIDINAEAGNAIINAATQDVGSA
EEVVGCEVAGESIQIALNHQYVLDGLMSVSTDQVFFETSSPMKPGIFRAGAGENFLYLVM
PVRVS*
...
contents of files like this

**Error log**
ERROR 2022-06-11 17:54:53,480 : invalid protein fasta due to: '*'

**CARD Version**
3.2.2

**RGI version**
5.2.1

**Expected behavior**
Annotating successfully

If applicable, include dependency versions such as Biopython version and Python version.
Python:3.8.5

**Comment by TKsh6** [comment]
so i used `sed 's/*//g' ./2_prodigal_res/${line}/${line}.faa  > ./2_prodigal_sed/${line}.faa` to delete *, but I got a new problem:
`/var/spool/slurmd/job06563/slurm_script: line 13: 76138 Segmentation fault      rgi main --input_sequence ~/h/20220423/com/9_prodigal_res/2_prodigal_sed/${bin_id}.faa --output_file ~/h/20220423/com/9_prodigal_res/6_rgi_res/${bin_id}.out --local --input_type protein --clean -a diamond
`
This resulted in many samples with no annotated results and very few samples with only a few annotated. e.g
![image](https://user-images.githubusercontent.com/95459755/173184271-0769749a-b1f4-480f-bbf7-e39d1c92f5de.png)
![image](https://user-images.githubusercontent.com/95459755/173184294-66f8fffd-f9fd-425b-8cc0-b200ce89023e.png)

**Comment by raphenya** [comment]
@TKsh6 you just need to edit your predicted proteins and remove the stop codon chars (`*`) and you can use the `--input_type protein` option in RGI.
