### ISSUE TITLE
Nudging heuristic leads to implausible results

### ISSUE THREAD

**Issue by SvetlanaUP** [arpcard/rgi#185]
When running your metagenome sample through RGI with default (BLAST) settings (which I believe most studies do), you will get outputs with “Perfect” and “Strict” hits AND “Strict” hits with a much lower bitscore than the threshold (nudged). The reason is not obvious and lies in the RGI default setting: 
"By default, all Loose RGI hits of 95% identity or better are automatically listed as “Strict”, regardless of alignment length, unless the --exclude_nudge flag is used."

**So, if you do not specify --exclude_nudge to exclude hits nudged from “Loose” to “Strict” hits, your “Loose” hit with at least 95 percent identity will be pushed into “Strict”.** However, there is no check for the length of the alignment, so even very short alignments are considered “Strict”. 

For example:

```
>GMGC10.028_222_711.PSTC
MQGKALERFMKYVFMFCAFLSILSIVLIFYFIFIGGTVNEGVWKFQGGIPFLMKQGFFKTFVGQQWQPSWKEPLYGIFPFIMGSIYVTIGAIIVGVPIGVLTAIFMAYFCPASLYRLFKPAINLMAAIPSIVYGFFALQMMVPFIRGLKFLPANNGMNILTASVLLGVMILPTIIGLSEAAIRAVPKHYYNASMGLGATHERSVLSVVVPAAKSGILSAIILGIGRAIGETMAVVLIAGNQPRLATSLLDGTRTLTTNIVLEMGYASGDHQHALIMTASVLFIFILIINSIFMWVKSKGDRN
```
is tagged as a beta lactamase based on an 8 AA match (e-value = 3). Eggnog-mapper and pfam consider this a transposase (https://gmgc.embl.de/search.cgi?search_id=GMGC10.028_222_711.PSTC).

We will switch to using --exclude_nudge and recommend that it should be the default. Alternatively, a more robust “nudging” heuristic can perhaps be justifiable.

This is the underlying reason why BLAST and DIAMOND results can be so different even in “Strict” mode (https://github.com/arpcard/rgi/issues/147): **as BLAST is more sensitive for short matches, it reports them, leading to nudging**.

**Comment by arpcard** [comment]
Hello, thanks for your post. The 95% nudge was added based on user requests, its impact is mentioned twice in the documentation (once in bold), and RGI output includes a column indicating which Strict hits were the product of a 95% nudge. RGI is used in a number of automated pipelines, so changing default settings is not a small proposition and could impact a large number of users. RGI results are designed to be as transparent as possible, indicating length of alignment, % identity, nudge, criteria to allow users to filter results as they need depending upon if they are interested in clinically relevant known ARGs (i.e. Perfect or high identity Strict) or are using combinations of BLAST/DIAMOND and filters for ARG discovery, with the accompanying noise that comes with relaxed search parameters.

Note we have not yet updated to the latest version of DIAMOND as our early tests indicate it is more aggressive in expanding alignments and we need to examine the impact relative to our curated bitscore cut-offs.

**Comment by luispedro** [comment]
I can appreciate the concerns regarding backwards compatibility, but changing it in the next major version would not be out of line in the same way that introducing this feature in `4.0.0` fundamentally changed the meaning of _Strict_ [1].

When annotating the GMGCv1, we observed that >86% of the _Strict_ hits are actually _Nudged_. Many of them are very short alignments (>52% of the total _Strict_ hits have <20% coverage). The claim that "Strict hits are likely functional" ([FAQ](https://github.com/arpcard/FAQ)) is hard to believe when the majority of these are such short alignments (the median bitscore is 21.6 and ~82% of bitscores are <30).

As far as I can tell (although I confess I was not exhaustive in my reading), the nudging heuristic is not discussed in any of the publications (including [Alcock et al., 2020](https://doi.org/10.1093%2Fnar%2Fgkz935) which postdates its introduction). Instead, like in the FAQ, _Strict_ hits are discussed as being likely homologs, which, again, seems improbable to me if nudged hits are the vast majority of _Strict_ hits and many of these are not even statistically significant (e-values >1).

A quick backwards compatible step would be changing the first examples in the docs to use `--exclude-nudges`.

[1] I believe it was version `4.0.0` that introduced nudging, but it was not explicit in the release notes. In any case, its introduction was a fundamental change to the concept of _Perfect_/_Strict_/_Loose_ as there are now two types of _Strict_ hits (true _Strict_ and _nudged Strict_)

**Comment by agmcarthur** [comment]
Hi @luispedro, I'm the PI for @arpcard. Reviewing your post and an unrelated query, we agree with your assessment. While we are writing a proper RGI paper, you are correct that _--exclude_nudge_ puts RGI's default behaviour out of sync with what is decribed in the literature. Fortunately, we are preparing the next RGI release now, so at that time we will depreciate _--exclude_nudge_, making the default setting not include nudges in the Strict results. We will introduce a new flag _--include_nudge_ to support those who wish to include nudges in Strict results. We will keep this issue open until it is resolved with the new version of RGI.

**Comment by agmcarthur** [comment]
Update released! https://github.com/arpcard/rgi
