### ISSUE TITLE
additional .fai file produced

### ISSUE THREAD

**Issue by Biofarmer** [arpcard/rgi#186]
Hi, I am running contig with rgi main function with default settings. The version is 5.2.0. There are two issues that I am confused:
1. for a few genomes (not all), an additional .fai file is produced in the directory where the genome is located, may I ask whether this is normal, is it due the genome itself?
2.warnnings like below are produced for a few genomes, may I ask whether this is normal, and can be ignored?
WARNING 2022-06-27 01:55:38,858 : partial gene in card reference: aad(6)
WARNING 2022-06-27 02:37:04,779 : partial gene in card reference: OXA-140

The results seem fine with two files (rgi_card.json  and rgi_card.txt) produced in the output directory.

Thanks
Wang

**Comment by raphenya** [comment]
@Biofarmer The index file`.fai` are normal. They are generated to search for alternate start codons and check for partials.

The warnings are also normal, they inform the user that the reference sequence in CARD are partials. Hence the user can further investigate if they have a complete gene.

Hope that helps.

Cheers,
Amos.

**Comment by Biofarmer** [comment]
> @Biofarmer The index file`.fai` are normal. They are generated to search for alternate start codons and check for partials.
> 
> The warnings are also normal, they inform the user that the reference sequence in CARD are partials. Hence the user can further investigate if they have a complete gene.
> 
> Hope that helps.
> 
> Cheers, Amos.

Hi Amos, many thanks for reply. Are "aad(6)" and "OXA-140" the gene names in CARD?

**Comment by Biofarmer** [comment]
> @Biofarmer The index file`.fai` are normal. They are generated to search for alternate start codons and check for partials.
> 
> The warnings are also normal, they inform the user that the reference sequence in CARD are partials. Hence the user can further investigate if they have a complete gene.
> 
> Hope that helps.
> 
> Cheers, Amos.

Hi Amos, many thanks for reply. Are "aad(6)" and "OXA-140" the gene names in CARD reference?

**Comment by Biofarmer** [comment]
Hi Amos, many thanks for your reply.
