### ISSUE TITLE
error in python3 setup.py test

### ISSUE THREAD

**Issue by chloelulu** [arpcard/rgi#19]
Hi, 
I have two questions. Hope to get answer from rgi team. Thanks in advance.
(1) there is github based rgi install, and also conda based install. But conda based can only support python2 and thr rgi version is  3.2. Is there any difference between these two channel installed rgi?

(2) I got the error in "python3 setup.py test". May I know how to solve this? I used conda install all the required dependencies. "python3 setup.py build . & python3 setup.py install" all successfully run. 

`python3 setup.py test

running test
running egg_info
writing RGI.egg-info/PKG-INFO
writing dependency_links to RGI.egg-info/dependency_links.txt
writing requirements to RGI.egg-info/requires.txt
writing top-level names to RGI.egg-info/top_level.txt
reading manifest file 'RGI.egg-info/SOURCES.txt'
writing manifest file 'RGI.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: 'fasta.fas'`

And `pytest -v -rxs` can not run. All failed.
Thanks so much.

**Comment by arpcard** [comment]
> (1) there is github based rgi install, and also conda based install. But conda based can only support python2 and thr rgi version is 3.2. Is there any difference between these two channel installed rgi?

The code base is the same. The versions are as follows: 
- RGI versions 3.X.X and below are python 2.7. 
- RGI versions 4.X.X are python 3.

The lastest [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/rgi/meta.yaml) didn't specify the correct version. We will fix this.

> (2) I got the error in "python3 setup.py test". May I know how to solve this? I used conda install all the required dependencies. "python3 setup.py build . & python3 setup.py install" all successfully run.

The following caused the error:

- The test files that needs to be removed are `app/fqToFsa.py` and `app/Report.py`. 
- The typo in `app/Analyser.py` import statement, it should read `from app.settings import *`

**Comment by arpcard** [comment]
@chloelulu 
>The lastest recipe didn't specify the correct version. We will fix this.

This was fixed with the following:
https://github.com/bioconda/bioconda-recipes/commit/90b14b2d0e0103a83314e21108833df34e1a1d58
