### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TommyH-Tran** [arpcard/rgi#192]
I just tried to install rgi on an m1 Mac and I got this error. 

Traceback (most recent call last):
  File "/Users/klemonlab/rgi/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/Users/klemonlab/rgi/app/MainBase.py", line 16, in <module>
    from app.BWT import BWT
  File "/Users/klemonlab/rgi/app/BWT.py", line 9, in <module>
    import dask.dataframe as dd
ModuleNotFoundError: No module named 'dask'

Not sure exactly what this means?

**Comment by raphenya** [comment]
@TommyH-Tran, I have added the use of `dask.dataframe` module recently to improve efficiency. It appears the module is not included in your environment. The requirements are in https://github.com/arpcard/rgi/blob/master/requirements.txt.

**Comment by raphenya** [comment]
Closing, @TommyH-Tran please re-open if you still have the same issue. Cheers.
