### ISSUE TITLE
failed to copy json file when loading CARD Reference Data

### ISSUE THREAD

**Issue by BangzhuoTong** [arpcard/rgi#193]
**Describe the bug**
fail to run rgi card_annotation

**Input**
**Download latest card database**
```wget https://card.mcmaster.ca/download/0/broadstreet-v3.2.4.tar.bz2```
**unzip into json file**
```tar -xvf broadstreet-v3.2.4.tar.bz2 /myfolder/card.json```
**load card database from json**
```docker run --rm -it -v /myfolder:/card/ finlaymaguire/rgi bash -c "rgi load --card_json /card/card.json"```
**run card annotation**
```docker run --rm -it -v /myfolder:/card/ finlaymaguire/rgi bash -c "rgi card_annotation -i /card/card.json > /card/card_annotation.log"```
**Something already went wrong above because noting was written to card_annotation.log file  
load annotated card database, version should be 3.2.4, which is the same as the version of downloaded card database.**
```docker run --rm -it -v /myfolder:/card/ finlaymaguire/rgi bash -c "rgi load -i /card/card.json --card_annotation  card_database_v3.2.4.fasta --local"```
**Error occur in last step: failed to copy json file: [Errno 2] No such file or directory: 'card_database_v3.2.4.fasta'**

**Input file**
The file you used as an input to run the data.
Either paste a sample or upload the file.

**Error log**
failed to copy json file: [Errno 2] No such file or directory: 'card_database_v3.2.4.fasta'

**CARD Version**
3.2.4

**RGI version**
lastest docker image.
finlaymaguire/rgi:latest

**Expected behavior**
load  annotated card_database_v3.2.4.fasta

**Screenshots**

**Desktop (please complete the following information):**
Linux server
x86_64 GNU/Linux

**Additional context**
If applicable, include dependency versions such as Biopython version and Python version.

**Comment by lpbbbbbb** [comment]
Hellow sir, I met the same problem. can you give me some adadvice vice  to solve this?
