### ISSUE TITLE
--local (or default) assumes no parallel jobs

### ISSUE THREAD

**Issue by nick-youngblut** [arpcard/rgi#195]
The `--local` in `rgi main` assumes that there are no parallel `rgi main` occurring in the same directory. This assumption causes problems with running `rgi main` in parallel via snakemake (or similar). It would be helpful to allow the user to set the local of the "local" database (as done with most other bfx software that requires >=1 database).

**Comment by raphenya** [comment]
@nick-youngblut Agreed! We will work on this. Cheers.
