### ISSUE TITLE
OSError: [Errno 16] Resource busy

### ISSUE THREAD

**Issue by peflanag** [arpcard/rgi#196]
Hi,

I'm new to RGI and I was running 16 samples through it. Half way through my samples I get the following error;

OSError: [Errno 16] Resource busy: '/Volumes/NMRSARL/MiSeqFastQFiles/S_maltophilia/RGI/M220598.fasta.temp.predictedGenes.json'

The program still seems to run on the remainder samples with the same error per sample and generates the .txt and .json file but the other temp files remain. can I assume that the .txt files are correct?

Cheers,

P

**Comment by raphenya** [comment]
@peflanag maybe try running the one sample on it's own and see if you get the same error message?

**Comment by raphenya** [comment]
@peflanag please re-open the issue if you still need help on this.
