### ISSUE TITLE
Add support for global installation

### ISSUE THREAD

**Issue by cnthornton** [arpcard/rgi#2]
The program currently only works for local installs. This is due to the creation of a log file in the installation directory, which would normally be read-only for standard users if installed globally. It would be nice if the user could specify their own log file path.

Here is the relevant code in settings.py:
line 35: logs = os.path.join(script_path, "_logs/")
line 50: file_handler = logging.FileHandler(os.path.join(logs,"app.log"))

**Comment by arpcard** [comment]
@cnthornton thank you. We will update this.
