### ISSUE TITLE
Inconsistency summary table and results in CARD-RGI

### ISSUE THREAD

**Issue by ikher** [arpcard/rgi#201]
I have recently run a CARD-RGI job in the RGI web portal. It worked fine but I find a little inconsistency among the summary table (see below) and the results table (see below too). The summary table says I have 0+6+323 hits (perfect+strict+loose). If I download the results I get 452 lines. If I count the lines in the results table shown in the HTML table I get 452 lines, too. I have tried to filter out repeated entries based on best-hit ARO and ARO, but then I get only about 280 hits…
Do you know why the numbers in the summary table and the full-length table do not match exactly? My guess is that the summary table may group/merge somehow redundant hits, but I can’t see how...
Thanks in advance,

Summary table:
![image](https://user-images.githubusercontent.com/30260892/197139148-7a50faec-d422-487c-9861-d3b495a7d73c.png)
Results table (1st page):
![image](https://user-images.githubusercontent.com/30260892/197139193-9be10d32-6f2b-45c3-81a8-57291378f1a8.png)

**Comment by raphenya** [comment]
@ikher We will look into this. Cheers.

**Comment by agmcarthur** [comment]
@ikher, the CARD website will update shortly with more informative text:

**Summary (summary counts and figures only include Loose hits of e-10 or better)**

**Results (all Loose hits shown)**

The download files and Results table include all possible Loose hits, but the summary table and visualizers are limited to Loose of e-10 or better.

**Comment by agmcarthur** [comment]
Apologies for the confusion.
