### ISSUE TITLE
fastq read limit for rgi bwt?

### ISSUE THREAD

**Issue by annettemcgrath** [arpcard/rgi#202]
Hi,
I have been trying to run rgi bwt on trimmed metagenomic reads. The input paired end illumina read files are big: I have been using files containing from 65M reads to 122M reads each. I also have files with >300M reads to process.

Analysis proceeds through the sam, bam file creation quickly but hangs once 
`bwa.model_species_data_type.temp.txt`
`bwa.reference_mapping_stats.txt`
`bwa.coverage_all_positions.summary.temp.txt`
`bwa.coverage_all_positions.temp.txt`
files are created until the script times out. This happens for both kma and bwa. I have not tried bowtie.

I have used subsets of the data - 50M, 20M and 10M paired reads - and get the same behaviour, again with both kma and bwa.

So far the only read set that has successfully completed is a 1M paired read subset. 

I am using RGI 6.0.1 with a local database, including wildcards.

Thanks for your help

**Comment by raphenya** [comment]
@annettemcgrath Is it possible to send me the 10M paired reads so that I can test them? Please also send me the commands you are using. Cheers.
