### ISSUE TITLE
rgi v6.0.1 unable to install using conda 

### ISSUE THREAD

**Issue by jayramr** [arpcard/rgi#203]
Hi Team,

conda version -> 4.14.0
rgi -> 6.0.1

I followed below steps 

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create --name rgi rgi=6.0.1

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): -
```

Please advise

Thanks
Jay

**Comment by apetkau** [comment]
So I have a similar issue to you @jayramr. Running the installation using [mamba](https://mamba.readthedocs.io/en/latest/) gives more information:

```
mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi=6.0.1
...
Looking for: ['rgi=6.0.1']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/main/linux-64                                            No change
pkgs/r/noarch                                                 No change
Encountered problems while solving:
  - package rgi-6.0.1-pyha8f3691_0 requires lxml 4.6.5, but none of the providers can be installed
```

However, I did notice if I removed conda channel priorities (`--no-channel-priority`) it would install:

```bash
# This succeeds
mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults --no-channel-priority rgi=6.0.1
```

I suspect there's incompatibilities with the package `lxml` version `4.6.5` that is available through different conda channels.

**Comment by jayramr** [comment]
Thanks @apetkau i tried mamba which resolves the issue. 

In my automation pipeline, it never looks for mamba binary. this i need to manually update. But for me without passing ```--no-channel-priority`` this succeeded.

Jay

**Comment by apetkau** [comment]
For `--no-channel-priority` it would only be needed if you have configured strict channel priority before `conda config --set channel_priority strict` (as described in the bioconda documentation: https://bioconda.github.io/).

**Comment by apetkau** [comment]
You may also want to look at [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/), which should make the `conda` command act the same as `mamba`.

**Comment by jayramr** [comment]
Thanks for the advise :)

**Comment by jayramr** [comment]
@StephanieAFlowers you may try using mamba

**Comment by raphenya** [comment]
Thank you @apetkau
