### ISSUE TITLE
What format should I use for antibiotic resistance analysis?

### ISSUE THREAD

**Issue by osidito91** [arpcard/rgi#213]
Hi, I'm new here. Firstly, I would like to thank you for the bioinformatics contribution to the scientific research work.

I have a question, if I have super heavy shotgun metagenomic contigs, the recommendation is to use CONDA, right?

I currently have a linux computer, I plan to install conda on it. Or do you recommend miniconda? Should I also install python on it?

Thank you very much in advance.

Best regards.

**Comment by raphenya** [comment]
@osidito91 Yes conda is your best bet for managing software. Cheers.
