### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by manolis2023** [arpcard/rgi#216]
Hi,

I'm trying to install rgi from conda but the installation never finish. Last time was running all the night, without any warning/error, looking for the packages.

I used your conda code as also the simply "conda install <tool>", but nothing.

Best

**Comment by karla-vasco** [comment]
Hi, the same happened to me yesterday, but I finally solved it based on https://stackoverflow.com/questions/69187142/solving-environment-failed-with-current-repodata-json-will-retry-with-next-rep

1. First, update your conda
conda update conda

2. Make sure you added the necessary channels
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge

3. Update a package called conda-canary (I'm not sure what it does)
conda update conda -c conda-canary

4. Change your channel priority to false
conda config --set channel_priority false

5. create your environment 
conda create -n rgi

6. activate the new environment
conda activate rgi

7. Install the last version of rgi
conda install rgi=6.0.2

8. Test that rgi works
rgi main -v

I hope it works!

**Comment by weiguanyue** [comment]
Hi, I tried to use your method , but it does not work , the same  reaction as before. When conda install rgi=6.0.2, it has been parked at solving environment:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |

Best

**Comment by karla-vasco** [comment]
It took some minutes to solve the environment but it finally worked after being patient

**Comment by weiguanyue** [comment]
ok,I'll wait and see what happens today. How long did it take you to finally install it?

**Comment by karla-vasco** [comment]
I don't remember exactly, but it was like ~20 mins...

**Comment by karla-vasco** [comment]
Some people solved the issue using mamba instead of conda
[](https://github.com/arpcard/rgi/issues/178)
[](https://github.com/arpcard/rgi/issues/203[](url))

**Comment by weiguanyue** [comment]
Hi, I have another problem. I don't know if you have

When running code：rgi main -i faa -o CARD -n 5 --debug -t protein -a DIAMOND --clean --local
Something wrong were happened:

INFO 2023-02-18 11:36:33,974 : create blast DB.
INFO 2023-02-18 11:36:34,526 : create diamond DB.
**Error: Accession file not found. BLAST databases require preprocessing using this command line: diamond prepdb -d DATABASE_PATH**
INFO 2023-02-18 11:36:34,825 : run filter
ERROR 2023-02-18 11:36:34,825 : missing blast xml file. Please check if input_type: 'protein' correspond with input file: ‘--low_quality' flag for short contigs to predicts partial genes.

However，when I nonuse the option ,-a DIAMOND,there were nothing wrong happened.

What is the reason for this?  Thank you very much.

**Comment by aaronmussig** [comment]
This is specific to mamba, but I was only able to get it to install by adding `--no-channel-priority`:

`mamba install -c conda-forge -c bioconda -c defaults --no-channel-priority rgi==6.0.2`

**Comment by pratibha-kadam** [comment]
> Hi, the same happened to me yesterday, but I finally solved it based on https://stackoverflow.com/questions/69187142/solving-environment-failed-with-current-repodata-json-will-retry-with-next-rep
> 
>     1. First, update your conda
>        conda update conda
> 
>     2. Make sure you added the necessary channels
>        conda config --add channels defaults
>        conda config --add channels bioconda
>        conda config --add channels conda-forge
> 
>     3. Update a package called conda-canary (I'm not sure what it does)
>        conda update conda -c conda-canary
> 
>     4. Change your channel priority to false
>        conda config --set channel_priority false
> 
>     5. create your environment
>        conda create -n rgi
> 
>     6. activate the new environment
>        conda activate rgi
> 
>     7. Install the last version of rgi
>        conda install rgi=6.0.2
> 
>     8. Test that rgi works
>        rgi main -v
> 
> 
> I hope it works!

I follwed these steps but for me 
solving environment taking forever. it's been 4 hours its running. what I am supposed to do??

I am even trying to install mamba but its also taking a lot of time and not finishing the process.
