### ISSUE TITLE
can not conda install

### ISSUE THREAD

**Issue by Wanli-HE** [arpcard/rgi#218]
hi do you have any idea why it can not conda install rgi

**Comment by Wanli-HE** [comment]
and are you plan to solve this?

**Comment by bgizelarMCW** [comment]
Having same issue trying to install rgi==6.0.2 with conda:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                            failed

ResolvePackageNotFound:
  - filetype[version='>=1.0.0']

**Comment by rbtoscan** [comment]
Same here.

Running 
`conda install --channel bioconda rgi` for over an hour.

**Comment by JuanmaMedina** [comment]
I have the same issue. It also gets stuck when specifying to install the most updated version.

`conda install --channel conda-forge --channel bioconda --channel defaults rgi`

**Comment by Yuxia88** [comment]
Having same issue trying to install rgi==6.0.2 with conda:
Solving environment: failed
CondaValueError: Malformed version string '~': invalid character(s).

**Comment by Amjadhpc** [comment]
I have used mamba instead of conda to install rgi==6.0.2
https://anaconda.org/conda-forge/mamba

Just replace conda with mamba  in the installation script and it should work fine.

**Comment by raphenya** [comment]
@Amjadhpc Thank you! @Wanli-HE please try the following command to install RGI lastest version:

```
mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi=6.0.2
```
