### ISSUE TITLE
Does not work with DIAMOND 0.9.22

### ISSUE THREAD

**Issue by LarsDu** [arpcard/rgi#22]
I wanted to make a comment of this so that others can see this in the event they have the same problem. I only figured this out by looking through the commit history:
RGI fails if you use the -a DIAMOND flag with DIAMOND 0.9.22 installed.
Using DIAMOND 0.8.36 fixes this problem.

**Comment by arpcard** [comment]
@LarsDu Please see requirements [here](https://github.com/arpcard/rgi#requirements)
