### ISSUE TITLE
Heatmap values generated from rgi-main json files

### ISSUE THREAD

**Issue by StephanieAFlowers** [arpcard/rgi#224]
I was reviewing the cvs files that accompany the heatmaps generated from my rgi-main json files. As my python skills aren't great, I was having trouble compiling the rgi-main results and was using the heatmap function as a start. It occurred to me that these values might represent a gene count with screened mutations in each sample, but when I crosscheck these values with the accompanying rig-main generated txt files for the same sample, the values didn't match. How are the heatmap values generated? Is there a suggested way to combine rgi-main results for a cohort of samples? Thanks!

**Comment by raphenya** [comment]
@StephanieAFlowers command used on the `jsons` from `rgi main`:

`rgi heatmap -i jsons -o out`

 I used the following accessions (JN420336.1, AY123251.1, HQ451074.1, AL123456), and results are like so for the `.csv` file produced:
```
% cat out-4.csv 
gene,2023-11-14_21:26:16.060_JN420336.1.fasta,2023-11-14_21:26:16.524_AY123251.1.fasta,2023-11-14_21:26:17.893_AL123456.fasta,2023-11-14_21:26:17.123_HQ451074.1.fasta
OXA-1,2,0,0,0
AAC(6')-Ib-cr6,1,0,0,0
NDM-1,2,0,0,2
QnrB1,2,0,0,0
catI,2,0,0,0
CTX-M-15,2,0,0,0
AAC(2')-Ic,0,0,2,0
AAC(3)-IId,0,0,0,2
AAC(6')-IIa,0,2,0,0
AAC(6')-Ib7,0,1,0,0
CARB-3,0,1,0,0
Mycobacterium tuberculosis 23S rRNA mutation conferring resistance to capreomycin,0,0,1,0
Mycobacterium tuberculosis intrinsic murA conferring resistance to fosfomycin,0,0,1,0
Mycobacterium tuberculosis katG mutations conferring resistance to isoniazid,0,0,1,0
Mycobacterium tuberculosis rpoB mutants conferring resistance to rifampicin,0,0,1,0
RbpA,0,0,1,0
TEM-1,0,0,0,2
aadA,0,2,0,0
armA,0,0,0,2
blaC,0,0,2,0
catB8,0,2,0,0
dfrA1,0,2,0,0
efpA,0,0,2,0
mfpA,0,0,2,0
mphE,0,0,0,2
msrE,0,0,0,2
qacG,0,0,1,0
sul1,0,0,0,2

```
The values means the following:

2 = Perfect
1 = Strict
