### ISSUE TITLE
How to export the result as excel format from RGI

### ISSUE THREAD

**Issue by chungui** [arpcard/rgi#23]
Step: https://card.mcmaster.ca/home-Analysis-AGI-upload the data -result
Question: there are several format of the result, such as "table view","AMR Genes","AMR gene Family", "Drug class" and "resistance mechanism", how to export the table view result as excel?

**Comment by arpcard** [comment]
Clicking on `Download` or `Download All` will provide results in a `json` and `tab-delimited` files.
The `tab-delimited` file can be opened with excel.
