### ISSUE TITLE
[BUG] Warnings and errors during installation using mamba

### ISSUE THREAD

**Issue by Swt623** [arpcard/rgi#232]
**Describe the bug**
There are "Invalid package cache" warnings and "ClobberError"

**Input**
`mamba create --name rgi --channel conda-forge --channel bioconda --channel defaults rgi`

**Error log**

> WARNING Invalid package cache, file '/home/wse3132/.conda/pkgs/rgi-6.0.2-pyha8f3691_0/site-packages/app/_data/card.json' has incorrect size
> WARNING Invalid package cache, file '/home/wse3132/.conda/pkgs/rgi-6.0.2-pyha8f3691_0/site-packages/app/_data/loaded_databases.json' has incorrect size

> SafetyError: The package for rgi located at /home/wse3132/.conda/pkgs/rgi-6.0.2-pyha8f3691_0
appears to be corrupted. The path 'site-packages/app/_data/card.json'
has an incorrect size.
  reported size: 33472923 bytes
  actual size: 35357447 bytes

> SafetyError: The package for rgi located at /home/wse3132/.conda/pkgs/rgi-6.0.2-pyha8f3691_0
appears to be corrupted. The path 'site-packages/app/_data/loaded_databases.json'
has an incorrect size.
  reported size: 286 bytes
  actual size: 410 bytes

>ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::perl-compress-raw-bzip2-2.087-pl526he1b5a44_0, bioconda/linux-64::perl-extutils-makemaker-7.36-pl526_1, bioconda/linux-64::perl-io-zlib-1.10-pl526_2, bioconda/linux-64::perl-json-4.02-pl526_0
  path: 'lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod'

**RGI version**
6.0.2
Installation on June 30, 2023.

**Desktop (please complete the following information):**
I am installing on university's high-performance computer cluster which I have successfully installed virtual environemnts for other programs before. 

**Additional context**
I am using mamba v0.15.3

**Comment by raphenya** [comment]
@ Swt623 The best thing is to install RGI using virtual and don't use mamba.

**Comment by raphenya** [comment]
@Swt623 please re-open the issue if you get the same error with a newer version of Mamba. Cheers.
