### ISSUE TITLE
How to interpret duplicate output rows and negative percent identity (rRNA gene variant model)

### ISSUE THREAD

**Issue by danrlu** [arpcard/rgi#237]
We can't tell whether this is a bug or it is intended and it's us not interpreting the results properly. 

**Describe the bug/confusion**
- One AMR hit has 8 rows in the RGI main output. 
- Only the `ORF_ID` is different and all other columns are identical, but the query contigs in the `ORF_ID` don't match the `Contig` column. I'm guessing this AMR hit was found in 8 different contigs, but wouldn't the `Contig` column show their corresponding contig names? 
![image](https://github.com/arpcard/rgi/assets/20667188/9f1d767b-8c92-41b5-9ebd-c70d8038583b)
- Separately in the `Percentage Length of Reference Sequence` column, the number is -15.74 and < 0 (b/c the orientation of AMR gene and the contig are the opposite direction). This is the only time I see this column < 0 in all RGI outputs so wondering whether this is intended. 

**Input**
`rgi main -i contigs.fasta -o contig_amr_report -t contig -a BLAST --include_nudge --clean`

**Input file**
https://github.com/danrlu/debug_data/tree/main/rgi

**Error log**
No error.

**CARD Version**
**RGI version**
latest version of rgi
CARD 3.2.6
(same result when uploading the contig.fasta to CARD website)

Thanks very much for this great tool and database and continuous improvements!!!

Originally noticed by @lvreynoso.

**Comment by raphenya** [comment]
Correct, 8 of the contigs hit model `Neisseria gonorrhoeae 23S rRNA with mutation conferring resistance to azithromycin`. 

For the `rRNA gene variant model` the ORF_ID is named with the model and the query identifier .e.g., `3646_5918 | model_type_id: 40295 | pass_bit_score: 5300 | SNP: C2600T,A2145G,C2597T,A2045G,A2059G,C2611T | Neisseria gonorrhoeae 23S rRNA with mutation conferring resistance to azithromycin | QUERY: NODE_26_length_1251_cov_840.666388	NODE_26_length_1251_cov_840.666388`

The `Percentage Length of Reference Sequence` calculation is incorrect, which we will fix. Cheers.
