### ISSUE TITLE
Resistance genes not identified by RGI

### ISSUE THREAD

**Issue by btroppo** [arpcard/rgi#238]
Hello, what is the main reason for not all resistance genes being present in CARD? For example, a protein sequence was identified by RGI as a loose hit (30-40% identity) to Bcr-1 from Pseudomonas spp., however if that same sequence is searched in another database, i.e. NCBI nr or Uniprot, the protein is identified with 100% aa identity to a Bcr family drug resistance efflux transporter from E. albertii. Although these two proteins confer resistance to bicyclomycin, they are only share 35% aa identity

**Comment by raphenya** [comment]
Thank you @springwang24! @btroppo please re-open the issue if you have more questions or information. Cheers.
