### ISSUE TITLE
Kmer Query 61mer dataset

### ISSUE THREAD

**Issue by editnori** [arpcard/rgi#239]
Hi I was running both RGI and Kmer query tools and I ended up with kmer analysis and output analysis json files for both. I was wondering within the kmer query tool if it also provides direct information with the kmer dataset. i.e the 61 mer data sets.  when extracting info from the data set into a CSV file for training I didnt see the kmer data set this analysis references only the number of kmers in the dataset

![image](https://github.com/arpcard/rgi/assets/39071311/03ea482d-e45a-4295-b5c4-c4e7651d1b55)

**Comment by raphenya** [comment]
There is a description of the CARD data with the downloads at https://card.mcmaster.ca/download and https://card.mcmaster.ca/readme/variants.
