### ISSUE TITLE
ModuleNotFoundError: No module named 'ahocorasick'

### ISSUE THREAD

**Issue by rickbeeloo** [arpcard/rgi#24]
The` requirements.txt` states:
```
...
pyahocorasick==1.1.8
...
```
After installing these I get a `ModuleNotFoundError: No module named 'ahocorasick'` error. Apparently it's looking for  `ahocorasick` instead of` pyahocorasick`? Of course I could install `ahocorasick` , however this package isn't updated since 2005 and installing it failed for me.

**Comment by rickbeeloo** [comment]
It was caused by the old version of RGI

**Comment by arpcard** [comment]
We used this package: https://github.com/WojciechMula/pyahocorasick
