### ISSUE TITLE
Update README (and add Wiki)?

### ISSUE THREAD

**Issue by agmcarthur** [arpcard/rgi#244]
Some suggestions for us to work on:

* put all the messages about what the earlier versions of RGI were doing e.g. UPDATED RGI version 6.0.0 onward: in one place, and have a link to it near the top of the readme? 
* the headings e.g. Running RGI main with Protein Sequences are highlighted by being bold (i think) and blue, but they seem the same size as the rest of the text. this makes it a bit harder to see exactly what you’re looking at. maybe if the text for those could be a different size, then that would also help?
* a bigger piece of work would be to use a github wiki instead? because there’s a lot of valuable information in there, would be great if it were a bit easier for beginners to see what was what e.g. https://github.com/ablab/spades/wiki

**Comment by raphenya** [comment]
Yes, I support Wiki, as the readme is now too long.

**Comment by agmcarthur** [comment]
Moved to internal developer task list.
