### ISSUE TITLE
CARD version not available

### ISSUE THREAD

**Issue by shreya1singh728** [arpcard/rgi#249]
Hello RGI team,
I installed RGI using the following commands : git clone https://github.com/arpcard/rgi
                                                                           conda env create -f conda_env.yml
                                                                           conda activate rgi
                                                                           pip install git+https://github.com/arpcard/rgi.git
and then downloaded the database as follows : wget https://card.mcmaster.ca/latest/data
                                                                            tar -xvf data ./card.json
The installation was done successfully but it is not displaying the version of the installed database. I get the following results:

![Screenshot 2023-10-20 144330](https://github.com/arpcard/rgi/assets/118904769/b6539176-6402-47ff-89ab-c84f7b86d494)

Please suggest a solution.

Thankyou in advance.
Regards,
Shreya

**Comment by hunglin59638** [comment]
You still need to type as following:
```
rgi card_annotation -i /path/to/card.json
```
It will generate card_database_v3.2.8.fasta and card_database_v3.2.8_all.fasta in the current directory.
Then, load them.
```
rgi load -i /path/to/card.json --card_annotation card_database_v3.2.8.fasta  --card_annotation_all_models card_database_v3.2.8_all.fasta
rgi database --version
# 3.2.8
```
Or just do this, it can download all CARD and WildCARD.
```
rgi auto_load
rgi database --version
# 3.2.8
```

**Comment by raphenya** [comment]
@hunglin59638 Thank you!
