### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by MohamedRefaat92** [arpcard/rgi#25]
Hi,
When I ran ` pytest -v -rxs` I got a report with a lot of failed process. It starts as follows

`heatmap_test.py::test_base_heatmap PASSED    [  7%]                                                                                                                                                       
heatmap_test.py::test_category_heatmap PASSED    [ 14%]                                                                                                                                                           
heatmap_test.py::test_cluster_heatmap PASSED         [ 21%]                                                                                                                                                       
heatmap_test.py::test_frequency_heatmap FAILED     [ 28%]                                                                                                                                                         
heatmap_test.py::test_category_frequency_heatmap PASSED     [ 35%]                                                                                                                                                
heatmap_test.py::test_category_cluster_heatmap PASSED       [ 42%]                                                                                                                                                
test_1.py::test_rgi_protein_sequence FAILED           [ 50%]                                                                                                                                                      
test_1.py::test_rgi_nucleotide_sequence FAILED      [ 57%]                                                                                                                                                        
test_1.py::test_rgi_homolog_model FAILED        [ 64%]                                                                                                                                                            
test_1.py::test_rgi_variant_model FAILED            [ 71%]                                                                                                                                                        
test_1.py::test_rgi_overexpression_model FAILED      [ 78%]                                                                                                                                                       
test_1.py::test_rgi_effluxpump_model FAILED   [ 85%]                                                                                                                                                              
test_1.py::test_rgi_rrna_model FAILED       [ 92%]                                                                                                                                                                
test_3.py::test_create_local_db FAILED        [100%]                                                                                                                                                              
`
This is followed by a long report for each of the above failures. One common thing between all the reports is that they contain the following 
` FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/mdr_project/softwares/rgi-4.2.2/tests/inputs/card.json'`

Can someone help me fix this problem?
Thanks in advance

**Comment by raphenya** [comment]
@MohamedRefaat92 You are getting this error because you don't have `card.json` inside inputs directory in tests. Running `test.sh` would download the `card.json` and run all the tests

**Comment by MohamedRefaat92** [comment]
@raphenya thanks for your reply. Now I don't get an error for not having `card.jason`, but this didn't solve the problem, though. Most of the tests still fail, probably for another reason. What should I do with that? any suggestions?

**Comment by raphenya** [comment]
@MohamedRefaat92 closing this issue, please comment if you still have this issue.
