### ISSUE TITLE
failed to load latest card database(version 3.2.8) using docker rgi(latest)

### ISSUE THREAD

**Issue by hemantgoyat22** [arpcard/rgi#252]
**Describe the bug**
fail to load latest card database(version 3.2.8) using docker rgi(latest).

**Input**
**Download latest card database**
wget https://card.mcmaster.ca/latest/data
**unzip into json file**
tar -xvf data /Path/to/card-data.tar.bz2
**load card database from json**
docker run -v $PWD:/data finlaymaguire/rgi rgi load --card_json  /Path/to/card.json

**Input file**
Unzipped card.json file.

**Error log**
ERROR conda.cli.main_run:execute(41): `conda run rgi load --card_json /Users/hemantgoyat/Downloads/card-data/card.json` failed. (See above for error).
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hemantgoyat/Downloads/card-data/card.json'

**CARD Version**
Currently loaded version is 3.2.5. Desired version that i want to load is 3.2.8

**RGI version**
Latest RGI version.
docker pull finlaymaguire/rgi:latest

**Expected behavior**
load latest card database (version3.2.8), (file name = card.json) 

**Screenshots**
<img width="1104" alt="Card_database_load_error" src="https://github.com/arpcard/rgi/assets/105455342/eb9f6135-fad2-4c00-a9cd-07a8e761ad01">

**Desktop (please complete the following information):**
 - macOS Ventura 13.5.1
 - Browser [safari]
 

**Additional context**
If applicable, include dependency versions such as Biopython version and Python version.

**Comment by raphenya** [comment]
@hemantgoyat22 see https://github.com/arpcard/rgi/issues/144
