### ISSUE TITLE
Review/Update RGI for Galaxy

### ISSUE THREAD

**Issue by agmcarthur** [arpcard/rgi#255]
Two entries in the Galaxy Toolshed:
* https://toolshed.g2.bx.psu.edu/view/card/rgi/84bd24ac33fd 
* https://toolshed.g2.bx.psu.edu/view/card/rgi/a5a3c70913e99d57

Plus two RGI repos:
* https://github.com/arpcard/rgi_wrapper
* https://github.com/arpcard/rgi_database_builder

@arpcard please review and update to support latest version of RGI.

**Comment by raphenya** [comment]
I will get to this soon.

**Comment by arpcard** [comment]
I didn't get a chance to implement this yet.
