### ISSUE TITLE
[BUG]rgi database --version N/A

### ISSUE THREAD

**Issue by alex-trist** [arpcard/rgi#258]
I recently installed rgi using mamba in a new environment. Then I tried
wget https://card.mcmaster.ca/latest/data
tar -xvf data ./card.json
rgi load -i Data_Bases/CARD/card.json

but when I check the version with
rgi database --version

result is
N/A

Same applies with the --local flag

Any thoughts.

Thanks!

**CARD Version**
2.3.8

**RGI version**
6.0.3

**Expected behavior**
Display 2.3.8 in database version

**Comment by raphenya** [comment]
@alex-trist Thank you! I will fix it. Cheers.

**Comment by jduquez** [comment]
Hi @raphenya same error!
any progress?

cheers

**Comment by b-tierney** [comment]
Hi -- I think I'm bumping into the same issue, but it's with the wildcard database. I'm trying to figure out what the current release number is for the loading process as I setup RGI. Can you point to where that info is found? I see card is 3.2.8, but don't see metadata for wildcard.

eg

rgi wildcard_annotation -i wildcard --card_json card.json -v ??? > wildcard_annotation.log 2>&1

**Comment by raphenya** [comment]
@b-tierney If you want to see loaded database use the following:

#### card canonical (i.e loaded only card.json)

```rgi database --version```

#### Wildcard (loaded everything e.g `rgi auto_load`)

```rgi database --version --all```

**Comment by b-tierney** [comment]
Thank you —but don’t you have to specify the database when you load? Eg the above command requires you to specify the database, and as far as I can tell it needs to be run before rgi database —version?

It seems circular, but maybe I’m misunderstanding something.

**Comment by raphenya** [comment]
@b-tierney we wanted to be able to add each database separately. It is best to use `rgi auto_load` to get the latest dbs.

**Comment by luxuejuan** [comment]
have you fixed it? Ihave the same problem.
RGI-6.0.2
want to get 3.2.8 in database version
rgi database --version   (#N/A)

**Comment by sciguy** [comment]
I'm getting the same result (NA) when checking the database version from the latest docker:
```bash
docker run -it quay.io/biocontainers/rgi:6.0.3--pyha8f3691_1 rgi database -v
# => N/A
```
