### ISSUE TITLE
Inconsistent results of 'rgi main' and 'rgi bwt' on the same sequencing data

### ISSUE THREAD

**Issue by JemmaSun** [arpcard/rgi#259]
Hi! 

I recently ran 'rgi bwt' on metagenomic sequences (FASTQ reads, default setting), which gives me over 700 ARO terms. Next, I ran 'rgi main' on the metagenome assemblies (reads were assembled by megahit) of the same sequences (FASTA - prodigal called genes; default setting with `-t protein`) to see how many of the reads AROs were represented at the contig level. However, almost no AROs identified from assemblies share the same ARO terms with reads. This happens to most of my soil samples:
![image](https://github.com/arpcard/rgi/assets/38450486/01b0e92f-742e-4ec4-97d1-0a0d0c445cc3)

I then collected the reads that mapped to my contigs, and ran `rgi bwt` on the collected reads. Unsurprisingly, the detected AROs from the mapped reads did not match the assembly AROs. While I can understand that `rgi bwt` and `rgi main` query AROs in different ways, still wondering why the results are so different and if there's a way to improve the consistency.

Thank you!

**Comment by raphenya** [comment]
@JemmaSun I think soil samples will have different sequences for AMR; CARD sequences are mostly clinical sequences. We have a separate dataset called card variants that might help in this. The CARD Variants contain variants of canonical AMR sequences we have in CARD.

Are the soil samples linked to human activity?

With `rgi bwt`, `kma` procudes better alignment as compared to Bowtie2. Which aligner were you using?

**Comment by raphenya** [comment]
@JemmaSun If you can, please share with me samples `S94` (high mapped reads) and `S99` (low mapped reads)

**Comment by JemmaSun** [comment]
Sure! May I have your email address please?






------------------ Original ------------------
From: amos ***@***.***&gt;
Date: Tue, Dec 5, 2023 9:31 AM
To: arpcard/rgi ***@***.***&gt;
Cc: JemmaSun ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [arpcard/rgi] Inconsistent results of 'rgi main' and 'rgi bwt' onthe same sequencing data (Issue #259)





 
@JemmaSun If you can, please share with me samples S94 (high mapped reads) and S99 (low mapped reads)

**Comment by JemmaSun** [comment]
Hi! I've sent the reads via email. Please let me know if you cannot access them. Cheers.

**Comment by raphenya** [comment]
@JemmaSun Ok, I'm downloading the samples and I will test. Cheers.

**Comment by raphenya** [comment]
@JemmaSun what is the command you used for `megahit` assembly?

**Comment by JemmaSun** [comment]
Hi, I used default settings of megahit
`megahit -1 "%$%_FORWARD_READ_FP_%$%" -2 "%$%_REVERSE_READ_FP_%$%" -t %$%_NUM_CPUS_%$% -o $OUTPUT_DIR`
