### ISSUE TITLE
ModuleNotFoundError: No module named 'ahocorasick'

### ISSUE THREAD

**Issue by inmanjm** [arpcard/rgi#26]
After what appeared to be a successful installation using the instructions in README.rst, all operations using the 'rgi' executable result in this:

> % ./rgi main -h
> Traceback (most recent call last):
>   File "./rgi", line 2, in <module>
>     from app.MainBase import MainBase
>   File "/[...]/rgi/rgi-4.2.0/app/MainBase.py", line 9, in <module>
>     import app.build_kmer_sets
>   File "[...]/rgi/rgi-4.2.0/app/build_kmer_sets.py", line 2, in <module>
>     import app.make_kmer_json
>   File "/[...]/rgi/rgi-4.2.0/app/make_kmer_json.py", line 1, in <module>
>     import csv, re, argparse, multiprocessing, math, json, ahocorasick, os
> ModuleNotFoundError: No module named 'ahocorasick'
>

I don't see this module in the installation tarball, nor is it listed as a requirement anywhere I can see.

I presume it was intended to find the 'ahocorasick' module provided by installing the 'pyahocorasick' package.  Could that be added to the requirements to save other folks the time I spent looking for this?

Thanks!

**Comment by raphenya** [comment]
@inmanjm Sorry, we didn't add all the requirements to README.rst. But all the requirements are in the file [requirements.txt](https://github.com/arpcard/rgi/blob/master/requirements.txt) which is used for installation.
