### ISSUE TITLE
USING RGI TOOL V 3.6.2 IN Linux (Ubuntu) 

### ISSUE THREAD

**Issue by mainakbioinfo** [arpcard/rgi#260]
I am getting this error message once I give the command :
rgi --help  in my Linux system
*_*DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('RGI==6.0.1', 'rgi')**_
I am a novice in Python and not able to understand what should be done to overcome the error.
I have followed the instructions given in the Github page for installing and setting the RGI tool.
Urgently need your intervention since I am in the middle of something very important which cannot be completed if I cant run the wgs data in RGI..
Sincerely looking for your positive response..

**Comment by raphenya** [comment]
@mainakbioinfo see my comment at https://github.com/arpcard/rgi/issues/261#issuecomment-1877437994
