### ISSUE TITLE
RGI heatmap/parser Issue [BUG]

### ISSUE THREAD

**Issue by MicoNick** [arpcard/rgi#263]
Good day, dear representatives of RGI. 
I faced a problem when using rgi heatmap and rgi parser.

About heatmap: 
When trying to build a heatmap and giving as arguments a folder with only json files and a subfolder, an error comes out. That said, all files were generated by searching on peptides annotated with prokka. The search for ARG genes was done in protein mode.
 
Heatmap construction was done in debug mode, hope it helps:

INFO 2024-01-08 22:00:31,106 : {
  { "input": "rgi_gene_res_blast",
  "classification": { "drug_class",
  "frequency": true,
  "output": "HM_gene/DJ_HM_DC",
  "cluster": { "both",
  "display": "plain",
  "debug": true
}
Traceback (most recent call last):
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 83, in __init__
    getattr(self, args.command)()
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 346, in heatmap
    self.heatmap_run(args)
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 365, in heatmap_run
    obj.run()
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 438, in run
    df = self.create_categories(drug_class, df)
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 97, in create_categories
    df = df.append([df.loc[model]]*(len(class_dict[model])-1)))
  File "/home/vasilchenko_ng/miniconda3/envs/rgi/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

As for the parser, it accepts json formats generated by the parser on the site without content (0 strict, 0 loose, o perfect) although everything is in the files, checked.

**Comment by raphenya** [comment]
@MicoNick what is the command you used and which version of RGI?

**Comment by MicoNick** [comment]
> @MicoNick what is the command you used and which version of RGI?
@raphenya You're talking about rgi command for heatmap generation, rgi main or something else?

RGI v 6.0.3

**Comment by raphenya** [comment]
> You're talking about rgi command for heatmap generation, rgi main or something else?

Yes, the command for the rgi heatmap.

**Comment by MicoNick** [comment]
rgi heatmap -i rgi_gene_res_blast -cat drug_class -f -clus both -d plain -o HM_gene/DJ_HM_DC

**Comment by skon7** [comment]
you should update the package version because the bug was fixed.The issue was caused by a compatibility problem with pandas versions greater than 2. : [stackoverflow](https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append#answer-75956237)

**Comment by MicoNick** [comment]
> You should update the package version because the bug was fixed.The issue was caused by a compatibility problem with pandas versions greater than 2. : [stackoverflow](https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append#answer-75956237)

Dear scon7, which package are we talking about? 
If RGI, it is already 6.0.3.

**Comment by raphenya** [comment]
@MicoNick the `rgi heatmap` only uses `json` files produced by `rgi main`. The `rgi parser` is used for generating `json` files for the RGI wheel on the card.mcmaster.ca website only. Hope that helps.

**Comment by MicoNick** [comment]
> @MicoNick the `rgi heatmap` only uses `json` files produced by `rgi main`. The `rgi parser` is used for generating `json` files for the RGI wheel on the card.mcmaster.ca website only. Hope that helps.

Dear Raphenya, I'm used rgi heatmap only with json files, which I put in the one directory. And rgi parser used for json generate, but this json has a strange visualised on the website (all wheels be a empty).

**Comment by MicoNick** [comment]
> @MicoNick the `rgi heatmap` only uses `json` files produced by `rgi main`. The `rgi parser` is used for generating `json` files for the RGI wheel on the card.mcmaster.ca website only. Hope that helps.

Dear Raphenya, I'm used rgi heatmap only with json files, which I put in the one directory. And rgi parser used for json generate, but this json has a strange visualised on the website (all wheels be a empty).

**Comment by MicoNick** [comment]
Dear colleagues, friends! 
Could you please suggest possible solutions to the problem?
