### ISSUE TITLE
Failed tests and error message

### ISSUE THREAD

**Issue by izip27** [arpcard/rgi#265]
Hello, 

I have downloaded rgi and the CARD database using conda. After running "pytest -v -rxs" I get a message saying that there are 16 failed tests. Right above that message I get an error message saying that there is no such file or directory. It looks like it is looking for the card.json file in a location where it is not located. Should I be loading the CARD database into that directory where it is searching for the card.json file?

Thank you for the help in advance!

**Comment by raphenya** [comment]
@izip27 If you would like to run tests, download the tarball of RGI and change into the tests directory to run the tests. See https://github.com/arpcard/rgi/blob/master/test.sh
