### ISSUE TITLE
RGI heatmap does not execute

### ISSUE THREAD

**Issue by DeepakNandi** [arpcard/rgi#266]
The RGI manual given has a great flaw.
It doesnt present the heatmap command. I did follow all the commands in the manual step by step.

**Input** 
rgi heatmap -i /home/t7400/json_files -cat drug_class -o rgiheat.png

This  folder (containing .json files from rgi main) was used to run heatmap as written in manual/README to generate a result. 
secondaly, it shows same error when the given command is rgi --version

**Error log**
usage: rgi <command> [<args>]
            commands are:
               main     Runs rgi application
               tab      Creates a Tab-delimited from rgi results
               parser   Creates categorical .json files RGI wheel visualization. An input .json file containing the RGI results must be input.
               load     Loads CARD database json file
               clean    Removes BLAST databases and temporary files
               galaxy   Galaxy project wrapper
               database Information on installed card database
rgi: error: argument command: invalid choice: 'heatmap' (choose from 'main', 'tab', 'parser', 'load', 'clean', 'galaxy', 'database')

**Expected behaviour**
It was to produce a pie chart of all the correctly found hits and to display it as a file named rgiheat.png

**Desktop (please complete the following information):**
 - OS: LINUX
 - Browser :chrome

**Comment by raphenya** [comment]
@DeepakNandi can you provide all the commands used and version of rgi?

**Comment by DeepakNandi** [comment]
v 6.0.3
even the .json file formed is over 20MB. Hence not able to visualize in web portal.

Can somebody please explain properly all the coloumns and its significance in the rgi results like
ORF_ID | Contig | Start | Stop | Orientation | Cut_Off | Pass_Bitscore | Best_Hit_Bitscore | Best_Hit_ARO | Best_Identities | ARO | Model_type | SNPs_in_Best_Hit_ARO | Other_SNPs | Drug Class | Resistance Mechanism | AMR Gene Family | Predicted_DNA | Predicted_Protein | CARD_Protein_Sequence | Percentage Length of Reference Sequence | ID | Model_ID |   

Especially   these ones:
Cut_Off | Pass_Bitscore | Best_Hit_Bitscore | Best_Hit_ARO | Best_Identities | ARO | Model_type | SNPs_in_Best_Hit_ARO | Other_SNPs | Drug Class | Resistance Mechanism | AMR Gene Family | 


Regards and thank you

**Comment by DeepakNandi** [comment]
@raphenya Can you please explain properly all the coloumns and its significance in the rgi results like
ORF_ID | Contig | Start | Stop | Orientation | Cut_Off | Pass_Bitscore | Best_Hit_Bitscore | Best_Hit_ARO | Best_Identities | ARO | Model_type | SNPs_in_Best_Hit_ARO | Other_SNPs | Drug Class | Resistance Mechanism | AMR Gene Family | Predicted_DNA | Predicted_Protein | CARD_Protein_Sequence | Percentage Length of Reference Sequence | ID | Model_ID |  

Especially these ones:
Cut_Off | Pass_Bitscore | Best_Hit_Bitscore | Best_Hit_ARO | Best_Identities | ARO | Model_type | SNPs_in_Best_Hit_ARO | Other_SNPs | Drug Class | Resistance Mechanism | AMR Gene Family |

Regards and thank you

**Comment by agmcarthur** [comment]
Full documentation https://github.com/arpcard/rgi
