### ISSUE TITLE
[BUG] The readme file for RGI on Github is not rendering

### ISSUE THREAD

**Issue by danrlu** [arpcard/rgi#267]
**Describe the bug**
<img width="951" alt="image" src="https://github.com/arpcard/rgi/assets/20667188/ffd81e13-3171-46b1-91f8-403fedbff7eb">

**Additional context**
I've been reading the RGI readme as plain text for a while XD It'd be good fix this at some point. Thanks for this great tool!

**Comment by agmcarthur** [comment]
Fixed!

**Comment by danrlu** [comment]
Thanks very much!!
