### ISSUE TITLE
BLAST process is not using multiple threads

### ISSUE THREAD

**Issue by drdee255** [arpcard/rgi#27]
I have used: rgi main -i inputseq.fasta -n 10 --clean -o out_rgi 
But blastp process is running on single threads only.

**Comment by raphenya** [comment]
@drdee255 I ran the following command to investigate this: 

```rgi main -i inputseq.fasta -n 10 --clean -o out_rgi --debug```

The attached pictures shows blastp running with 10 threads:

![blastp_10threads](https://user-images.githubusercontent.com/972724/48023735-a510d100-e10c-11e8-868a-64dc17e4abf2.png)
