### ISSUE TITLE
purpose of --data in rgi main

### ISSUE THREAD

**Issue by danpal96** [arpcard/rgi#272]
`rgi main` has the next option:
```
  -d {wgs,plasmid,chromosome,NA}, --data {wgs,plasmid,chromosome,NA}
                        specify a data-type (default = NA)
```
But I couldn't find what is the difference in the analysis if I use the different data types. Could you explain this to me?

**Comment by raphenya** [comment]
The `--data` option is used to explicitly specify the data used. This information is used for the CARD variants downstream analysis. Cheers.
