### ISSUE TITLE
[BUG]Error: Invalid parameter count for option '--query'

### ISSUE THREAD

**Issue by diego00012138** [arpcard/rgi#274]
**Describe the bug**
Error: Invalid parameter count for option '--query'
**Input**
The command-line input you used to run your data.
rgi main -i ./prodigal/protein.fa  -t protein  -n 12 -a DIAMOND --include_loose -o ./card/output.card

**Input file**
The file you used as an input to run the data.
Either paste a sample or upload the file.
error occurs when put in this :
>k97_81242_1 # 1 # 381 # -1 # ID=1_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.362
VFNFPKVKKEQVKQFQLFDYPKIYDHYKCNSIFGYGDPNQNEANKLLNFYNAKLGRSKEV
RMIILIFRGQPLDAGFLQEGYWKRGNKNEFITTIGIDSENTVQWSYVFSWTESESLITET
RNFVLGQ
but it is ok when put in this :
>k141_288077_1 # 14 # 343 # -1 # ID=1_1;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.570
VHWGNEMTPTPTPEQRELSKRWIDAGASAIIGGHPHVTQTIDSYRGRPIVYSLGNFVFDY
YPVDPAIWYGWAIRLSIPPQSPDGSTPIDWETITVELDPRGLPKPVDPN
**Error log**
The error that is thrown when you run the process.

**CARD Version**
The version of CARD you are using. Please ensure it is up to date.

**RGI version**
The version of RGI you are using.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
If applicable, include dependency versions such as Biopython version and Python version.

**Comment by diego00012138** [comment]
actually i find an interesting question. The file "K97" was stored in a hard disk, and it can not be input, but it do can when i move it to the storage of my server.

**Comment by raphenya** [comment]
@diego00012138 Are you inputting valid FASTA formatted files?
