### ISSUE TITLE
Heatmap questions 

### ISSUE THREAD

**Issue by LeonardosMageiros** [arpcard/rgi#28]
Hi, 

I am trying rgi for the first time and I have a quick question. 
So after running just one isolate (contigs fasta file) against the db I received a number of files as an output. 
After inspecting the .out.txt to see what hits I had from the run I also tried to make a heatmap. 
While running I received  the message "Loose hit encountered. Not being added." a few times. 
Can you please explain what that means? 

Additionally in the end of the run a message is typed indicating the colors of the heatmap. 
Specifically: Yellow represents a perfect hit, teal represents a strict hit, purple represents no hit.

Is that correct? I am wondering because in my txt file I have many strict hits that they are in purple and not in teal color in the heatmap. 

Thank you very much for your time and help.

Leonardos

**Comment by raphenya** [comment]
> While running I received the message "Loose hit encountered. Not being added." a few times.
Can you please explain what that means?

RGI produces perfect, strict and loose hits for each gene predicted. The heatmap only uses perfect and strict hits.

> Is that correct? I am wondering because in my txt file I have many strict hits that they are in purple and not in teal color in the heatmap.

Hmm, maybe there is a bug. Which command did you run?

**Comment by lautty** [comment]
Hi Leonardos,
Thanks for bringing this to our attention. If you pull the latest update, this bug should be fixed. Please let us know if works for you!

**Comment by LeonardosMageiros** [comment]
Thx for your help. 
Best
Leonardos
