### ISSUE TITLE
Kmer-query only works with data created with bwa or bowtie2 aligner

### ISSUE THREAD

**Issue by VinzentRisch** [arpcard/rgi#281]
Hello 
I am trying to run kmer-query on my AMR annotations and I found that I get an error when running it with a BAM file that was created with the KMA aligner in the bwt step.
`failed to parse BAM file: {}, please check which aligner software was used to produce the BAM file in the RGI BWT step.`

Is something wrong with my BAM file or is it only possible to run kmer-query with BAM files that were created with the BWA and bowtie2 aligners?

**Comment by agmcarthur** [comment]
We believe this is related to the KMA bug discussed in #256. It seems to be an edge case, i.e. does not occur for all analyses.
