### ISSUE TITLE
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped

### ISSUE THREAD

**Issue by jihen-lau** [arpcard/rgi#286]
**The bug**
I'm having the same issue as previously posted by some users, is there a fix for this, or any solution for troubleshooting?
Many many lines of: [W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped

Then it shows:
[bam_sort_core] merging from 36 files and 12 in-memory blocks...

Followed by various lines, different content, but the same format of
WARNING 2024-06-29 02:57:34,837 : model with id : 3278, has few mapped reads to make consensus sequence skipping: 'Prevalence_Sequence_ID:2857|ID:3278|Name:Acinetobacter_baumannii_AbaQ|ARO:3004574'

I believe the process were then terminated as I saw some temporary files, and I not sure how will the program prompt if the process is completed without error.

**My Command**
rgi bwt --read_one "${in_dir}/${read1}" --read_two "${in_dir}/${read2}" --output_file "${out_dir}/${prefix}" --local --include_wildcard --include_other_models --clean -n 12

**CARD Version**
CARD version: 3.2.9
wildCARD version: 4.0.2

**RGI version**
RGI v 6.0.3 (downgraded KMA to 1.3.4)

**Desktop (please complete the following information):**
 - Ubuntu 20.04.6 LTS, 64GB RAM

**Additional context**
There are the same issues listed here at https://github.com/arpcard/rgi/issues/256 but it's close due to stale, so I raise a new issue here, to see if there's any updates or recommended solution

Thanks !

**Comment by agmcarthur** [comment]
see #256
