### ISSUE TITLE
KMA in RGI bwt

### ISSUE THREAD

**Issue by KatariinaParnanen** [arpcard/rgi#290]
The kma seems to be ran with default parameters which means that the identity cut off is about 20% for sequence identity. Why is there custom no cut off for KMA?

**Comment by KatariinaParnanen** [comment]
Are the sam and bam files used to filter the reads after mapping according to the strict and perfect cutoffs like with RGI for assembled data? In the documents for rgi bwt, does the allele refer to a read & its sequence in the sample analysed? I find the word allele's use confusing since short reads don't cover the length of the whole ARG.

**Comment by agmcarthur** [comment]
Hello @KatariinaParnanen, thanks for your suggestion. We will work on adding custom flags for support of KMA within RGI. 

RGI's Perfect & Strict paradigms only apply to the BLAST-based _rgi main_ algorithms, not to read mapping by _rgi bwt_. Currently, RGI reports all KMA results with no filtering so users can secondarily filter that data as they see fit. In the documentation, when we refer to allele, we mean the reference sequence in CARD, not your sequencing reads.

I hope this helps!
