### ISSUE TITLE
How to run RGI BWT on single nanopore reads?

### ISSUE THREAD

**Issue by gilmahu** [arpcard/rgi#293]
The usage report printed by "rgi bwt -h" shows the only available options to be for paired end illumina reads. 
Is there any flag to feed it single ONT sequenced metagenomic reads?

**Comment by gilmahu** [comment]
As a test i have tried rgi bwt with read one only for the single ONT reads and it seems to have worked. So i'm guessing the solution is that as long as read-two is not provided, the tool works with one..?

**Comment by edwardbirdlab** [comment]
Hello, I was wondering this a while back, and looked into how this would work. RGI assumes that single ended reads as single ended short reads, not ONT reads. The issue with this is that when mapping ONT reads with KMA you would ideally specify the "-bcNano". Additionally the default support level "-bc" is usually lowered a bit with ONT data as well. I was testing our some of this as while back on my own [here.](https://github.com/edwardbirdlab/rgi/tree/master) If this would be helpful, I'd be glad to assist with a full implementation.
