### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by fasemoreakinyemi** [arpcard/rgi#31]
I get this error after installing with conda 

$ conda install --channel bioconda rgi 

$ rgi --help
Traceback (most recent call last):
  File "/home/man/anaconda3/bin/rgi", line 11, in <module>
    import package.rgi.rgi
  File "/home/man/anaconda3/lib/python3.6/site-packages/package/rgi/rgi.py", line 158
    print "DB exists"
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("DB exists")?

I know it's a python version error but rgi requirement says python3.6 so I wonder what I am doing wrong?

regards

**Comment by raphenya** [comment]
@fasemoreakinyemi can you try `conda install --channel bioconda rgi=4.2.2`

**Comment by fasemoreakinyemi** [comment]
$ conda install --channel bioconda rgi=4.2.2

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - rgi=4.2.2
  - filetype[version='>=1.0.0']
  - rgi=4.2.2
  - pyahocorasick[version='>=1.1.7']

**Comment by hkoo877** [comment]
Hi, I have been trying to install rig=4.2.2, however it showed "Solving environment: failed"

I ran below commands as suggested above:

conda config --add channels conda-forge
conda install --channel bioconda rgi=4.2.2

Please let me know how I can resolve this issue. Thanks.

**Comment by fasemoreakinyemi** [comment]
A virtual environment created with python 2.7 then install with pip

hkoo877 <notifications@github.com> schrieb am Do. 21. Feb. 2019 um 23:01:

**Comment by jakob-wirbel** [comment]
I managed to install `rgi` using the suggested answer: 

```bash
$ conda config --add channels conda-forge
$ conda install --channel bioconda rgi=4.2.2
```
but this let to another problem with the installation:

```bash
$ rgi main -i /path/to/input.fa -o /path/to/output
# blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directorysuch file or directory
```

**Comment by raphenya** [comment]
> blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

@apetkau Have you seen this error before?

**Comment by apetkau** [comment]
I suspect that different dependencies in your main conda envivronments may be conflicting with the dependencies required by `rgi`. You may wish to install rgi in a separate environment. That is:

```
conda create --name rgi rgi=4.2.2
```

Then, to use `rgi` you can first activate the environment:

```
conda activate rgi
rgi --help
```

This way, `rgi` is completely isolated from other packages (and so dependencies should not conflict with each other).

Another possibility is related to the order of the channels used to install packages. The [bioconda documentation[(https://bioconda.github.io/#set-up-channels) recommends to set up channels in this order:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

I suspect other orders can mean different dependency packages get installed which conflict with each other.

**Comment by jakob-wirbel** [comment]
Thank you very much for your answer!!!
The problem was indeed the order of the channels, which led to some incompatible dependencies.

The following worked for me:
```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create --name rgi rgi=4.2.2
conda activate rgi
```

**Comment by rotheconrad** [comment]
I follow these instructions:
`
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create --name rgi rgi=4.2.2
conda activate rgi
`
 but I still get the error:
`makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

when running:
`rgi main --input_sequence 01_Genomes/E_coli_group_FMT1.fna --output_file FMT1_RGI --input_type contig --include_loose --clean`

**Comment by myshu2017-03-14** [comment]
@rotheconrad Hi, I met with the same error.
The command:
> rgi main --input_sequence GCF_000005845.2_ASM584v2_protein.faa --output_file test_out --input_type protein --local --include_loose --clean --debug

And the error:

> INFO 2019-07-31 17:29:05,678 : /home/shumingyue/1-software/Miniconda/GCF_000005845.2_ASM584v2_protein.faa => None
> INFO 2019-07-31 17:29:05,753 : create blast DB.
> makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
> INFO 2019-07-31 17:29:05,761 : diamond DB exists
> INFO 2019-07-31 17:29:05,762 : run blast
> blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
> INFO 2019-07-31 17:29:05,767 : set blast xml file: [/home/shumingyue/1-software/Miniconda/GCF_000005845.2_ASM584v2_protein.faa.temp.blastRes.xml]
> INFO 2019-07-31 17:29:05,768 : run filter
> ERROR 2019-07-31 17:29:05,768 : missing blast xml file(/home/shumingyue/1-software/Miniconda/GCF_000005845.2_ASM584v2_protein.faa.temp.blastRes.xml). Please check if input_type: 'protein' correspond with input file: '/home/shumingyue/1-software/Miniconda/GCF_000005845.2_ASM584v2_protein.faa' or use '--low_quality' flag for short contigs to predicts partial genes.
> INFO 2019-07-31 17:29:05,768 : Total running time 0.092s

Did you find any solutions?

**Comment by Lamm-a** [comment]
Have any solutions been found to this as despite insalling conda as mentioned above in the stread I still the the error @myshu2017-03-14 and @rotheconrad describe

**Comment by iwangtoknow** [comment]
I think the file `/home/user/envs/jupyter/lib/python3.6/site-packages/package/rgi/rgi.py` was written in python2 style, so when it is executed by python3 gets wrong.
```
$ rgi -h
Traceback (most recent call last):
  File "/home/wang/envs/jupyter/bin/rgi", line 11, in <module>
    import package.rgi.rgi
  File "/home/wang/envs/jupyter/lib/python3.6/site-packages/package/rgi/rgi.py", line 158
    print "DB exists"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("DB exists")?
```

**Comment by iwangtoknow** [comment]
> I think the file `/home/user/envs/jupyter/lib/python3.6/site-packages/package/rgi/rgi.py` was written in python2 style, so when it is executed by python3 gets wrong.
> 
> ```
> $ rgi -h
> Traceback (most recent call last):
>   File "/home/wang/envs/jupyter/bin/rgi", line 11, in <module>
>     import package.rgi.rgi
>   File "/home/wang/envs/jupyter/lib/python3.6/site-packages/package/rgi/rgi.py", line 158
>     print "DB exists"
>                     ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("DB exists")?
> ```

I found conda will install rgi=3.1.0 in default, and this version was build in py_0.
So that's why we get error.
