### ISSUE TITLE
support for .gz ? (or '.fsa')

### ISSUE THREAD

**Issue by bigdoyle** [arpcard/rgi#32]
Is there support for .gz files? The help indicates that .gz are accepted (e.g. myFasta.fasta.gz). I'm running rgi 4.2.2 in python 3.6 from a fresh conda install. Whenever I input filename.fasta.gz I see the following errors in the log:
ERROR 2019-01-03 16:41:20,906 : gz
ERROR 2019-01-03 16:41:20,906 : application/gzip
WARNING 2019-01-03 16:41:20,906 : Sorry, no support for this format.

------------------------------------------------------------

also, it seems that the extension must be '.fasta'.  Would it be possible to accept other extensions (.fsa, .fa)?

Thanks!

**Comment by raphenya** [comment]
@bigdoyle 
> Is there support for .gz files? The help indicates that .gz are accepted (e.g. myFasta.fasta.gz). I'm running rgi 4.2.2 in python 3.6 from a fresh conda install. Whenever I input filename.fasta.gz I see the following errors in the log:
ERROR 2019-01-03 16:41:20,906 : gz
ERROR 2019-01-03 16:41:20,906 : application/gzip
WARNING 2019-01-03 16:41:20,906 : Sorry, no support for this format.

We currently don't have support for `.gz` or compressed files, but we will in the future.

> also, it seems that the extension must be '.fasta'. Would it be possible to accept other extensions (.fsa, .fa)?

Any FASTA formatted file should work fine
