### ISSUE TITLE
error with rgi installation on singularity image

### ISSUE THREAD

**Issue by EnriqueDoster** [arpcard/rgi#33]
Hello, 

Hope this message finds you well. I was easily able to install RGI using conda on my local server, but have been getting different errors when trying to containerize RGI within a singularity image. When I use pip to install dependencies and RGI from the github repository (https://www.singularity-hub.org/containers/6131), the installation completes without any issues but then I try running rgi and get the following error:

```
$Singularity EnriqueDoster-sing_biotools-master-latest.simg:~> rgi --help
Traceback (most recent call last):
  File "/usr/local/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/usr/local/lib/python3.4/dist-packages/app/MainBase.py", line 9, in <module>
    import app.build_kmer_sets
  File "/usr/local/lib/python3.4/dist-packages/app/build_kmer_sets.py", line 2, in <module>
    import app.make_kmer_json
  File "/usr/local/lib/python3.4/dist-packages/app/make_kmer_json.py", line 145
    f = {**f, **results[i][1]}
          ^
SyntaxError: invalid syntax
```

On the other hand, when I try to install RGI using conda in a singularity image the installation fails with dependency errors even though I've tried installing to conda environments with python 3.7 or python 2.7 as well as individually installing readline, sqlite, and tk with conda:

```
$conda install --channel bioconda rgi=4.2.2
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - rgi=4.2.2 -> blast==2.6.0 -> boost=1.64 -> python=2.7 -> readline=6.2
  - rgi=4.2.2 -> blast==2.6.0 -> boost=1.64 -> python=2.7 -> sqlite=3.13
  - rgi=4.2.2 -> blast==2.6.0 -> boost=1.64 -> python=2.7 -> tk=8.5
Use "conda info <package>" to see the dependencies for each package.

ABORT: Aborting with RETVAL=255
Cleaning up...

```

Thank you for any ideas on how to fix this issue. I'm attempting to use RGI on a supercomputer and they don't support docker or allow new installations of software, but singularity is supported so I hope to find a way for it work. 

Best,
-Enrique

**Comment by raphenya** [comment]
@EnriqueDoster RGI requires python version 3.6. We haven't tested exhaustively for python 3.7.

**Comment by EnriqueDoster** [comment]
@raphenya Thanks for pointing out my silly mistake! It's all working fine now.
