### ISSUE TITLE
RGI using reads (fastq files) results in an error

### ISSUE THREAD

**Issue by apetkau** [arpcard/rgi#35]
I'm testing out RGI (version `4.2.2` in conda) using reads (fastq format) but I keep on running into errors.

The command I run is:

```bash
rgi main -i SRR1952908_1.fastq -o out -t read -a diamond -n 8 -d NA --debug
```

I get the following printed out, at which point the program exits with exit code `1`:

```                                                
INFO 2019-01-23 14:20:20,624 : /home/aaron/tmp/test-sra/SRR1952908_1.fastq => None
INFO 2019-01-23 14:20:23,181 : blast DB exists
INFO 2019-01-23 14:20:23,182 : diamond DB exists
INFO 2019-01-23 14:20:23,182 : process read
```

Is there something I'm missing here? When I run with an assembled genome everything works.

The specific reads I used are https://www.ncbi.nlm.nih.gov/sra/SRR1952908 but this same issue occurs for other sets of reads.

This is also being run on Linux and the version of Python being used is `3.5.6`.

**Comment by raphenya** [comment]
@apetkau we haven't added code for using fastq for `rgi main` since we have been expanding rgi to use Burrows-Wheeler Transform for `rgi bwt`

**Comment by raphenya** [comment]
@apetkau you can actually convert your fastq to fasta and use `rgi main` with `--low_quality` flag

**Comment by apetkau** [comment]
Thanks @raphenya. I did not realize that. Sorry.

I think we should remove the option for this in the Galaxy tool then. I'll add an issue in that repo.
