### ISSUE TITLE
cannot save output into the output file

### ISSUE THREAD

**Issue by YiweiZhu** [arpcard/rgi#37]
When the rgi main program finish running, the results are kept in the current file instead of the output file as indicated in the command line. 
Here is my command:
$ rgi main -i ./WGS_sequence/193_scaffolds.fasta -o ./RGI/ --local

What is wrong?

**Comment by raphenya** [comment]
The option `-o ./RGI/` should be a file not a directory. Try something like:
```
rgi main -i ./WGS_sequence/193_scaffolds.fasta -o ./RGI/193_scaffolds.fasta.output --local
```
provided you have `./RGI/` directory
