### ISSUE TITLE
problem with missing xml file 

### ISSUE THREAD

**Issue by saadleeshehreen** [arpcard/rgi#38]
I am trying to run RGI v4.2.2. But enter-counting these errors. How to solve this?  
export PATH="/Volumes/userdata/student_users/miniconda3/bin:$PATH"
 ~/miniconda3/bin/rgi main -i /Volumes/scratch/DB/RefSeq93/bacteria/P/Pseudomonas_aeruginosa_19660-1402497#GCF_000481765.1/GCF_000481765.1_Pseu_aeru_19660_V1_genomic.fna --low_quality  -o test
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
ERROR 2019-04-16 23:14:00,682 : missing blast xml file(/Volumes/userdata/student_users/GCF_000481765.1_Pseu_aeru_19660_V1_genomic.fna.temp.contig.fsa.blastRes.xml). Please check if input_type: 'contig' correspond with input file: '/Volumes/scratch/DB/RefSeq93/bacteria/P/Pseudomonas_aeruginosa_19660-1402497#GCF_000481765.1/GCF_000481765.1_Pseu_aeru_19660_V1_genomic.fna' or use '--low_quality' flag for short contigs to predicts partial genes.

**Comment by raphenya** [comment]
@saadleeshehreen It looks like NCBI blast is not installed

**Comment by raphenya** [comment]
@saadleeshehreen Please see this issue https://github.com/arpcard/rgi/issues/31

**Comment by Lamm-a** [comment]
I am comming accross the same error but don't see a solution to the prolem in the linked thread? I followed that threads instructions during my install but still am getting this error. Are there any solutions, do I have to manually install blast?
