### ISSUE TITLE
error RGI main with Protein Sequences

### ISSUE THREAD

**Issue by sskhanam** [arpcard/rgi#40]
I am running rgi for my protein.faa files and this is the error message I get: 
command:  rgi main --input_sequence /home/khanam/Active_Projects/Resistome/Genome/TW008.faa --output_file /home/khanam/Active_Projects/Resistome/Genome/TW008out --input_type protein --local --clean 
Error message inr eturn: 
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
ERROR 2019-04-19 15:29:47,725 : missing blast xml file(/home/khanam/Active_Projects/Resistome/Genome/TW008.faa.temp.blastRes.xml). Please check if input_type: 'protein' correspond with input file: '/home/khanam/Active_Projects/Resistome/Genome/TW008.faa' or use '--low_quality' flag for short contigs to predicts partial genes.

Adding --low quality as flag did not help. How can I resolve this? thanks!

**Comment by raphenya** [comment]
@sskhanam It looks like you don't have NCBI blast installed.

**Comment by sskhanam** [comment]
Thank you Raphenya for your response! I figured it out and fixed it. My data analysis went through nicely after that.  Thanks!

**Comment by Lamm-a** [comment]
Would it be possible to share how you fixed it, I am struggling with the same issue despite blast aparently being installed

**Comment by sskhanam** [comment]
It appeared that my python version was not the right one for the conda package I installed. Also, I did not have the library. I used this code below and it solved the environment to run rgi.
conda install -c bioconda openssl=1.0

Hope this help.
