### ISSUE TITLE
RGI web portal unreliable with 5.0.0 update?

### ISSUE THREAD

**Issue by rmzelle** [arpcard/rgi#41]
I've been trying to rerun some draft genomes today with https://card.mcmaster.ca/analyze/rgi, but RGI kept going straight to a blank page showing only the "Back to RGI" and "Download Results" buttons (and the download is only a 112 byte file). After trying a bunch of times, the smallest genomes files went through, but I'm still having issues with the larger files.

The same files all ran fine last week with RGI 4.2.2 and CARD 3.0.1. The FASTA files are 2-12 Mbyte in size.

**Comment by raphenya** [comment]
@rmzelle Can you try running again? We just did an update between 10am-12noon.

**Comment by rmzelle** [comment]
Still happens with my next-smallest FASTA genome file (6 Mb).

**Comment by arpcard** [comment]
Checking!

**Comment by raphenya** [comment]
@rmzelle Can you share the session number?

**Comment by arpcard** [comment]
My tests passed. @rmzelle, @raphenya will follow up if you can share your session number. He is the Lead CARD Developer.

**Comment by rmzelle** [comment]
Can I use card@mcmaster.ca to contact @raphenya?

**Comment by raphenya** [comment]
Yes

**Comment by raphenya** [comment]
The error was with ambiguous nucleotide codes. RGI doesn't predict on data with ambiguous nucleotide codes. We will be working to report better on the web frontend. Thank you @rmzelle
