### ISSUE TITLE
conda installation issues

### ISSUE THREAD

**Issue by darwinbandoy** [arpcard/rgi#42]
I tried reinstalling rgi to take advantage of the heatmap function.

I created a separate environment in conda and used this command:

conda install -c bioconda rgi

but I had this conda installation error message:

ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::atomicwrites-1.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/Users/miniconda3/envs/rgi/bin/python3.6'")
Attempting to roll back.

**Comment by raphenya** [comment]
@darwinbandoy Can you provide the commands you ran, so that we can reproduce?

**Comment by raphenya** [comment]
@darwinbandoy Do you still have this issue?

**Comment by darwinbandoy** [comment]
Yes is it now solved, thanks
