### ISSUE TITLE
Link to full hit results from Table View

### ISSUE THREAD

**Issue by rmzelle** [arpcard/rgi#44]
When you drill down to the lowest level in "AMR Genes", "AMR Gene Family", "Drug Class", and "Resistance Mechanism" tabs, RGI 5.0.0 shows links in the Hit column that link to a table at the bottom of the page with the full results for that particular hit. E.g.:

![image](https://user-images.githubusercontent.com/77951/57800786-37c7a380-7720-11e9-9d17-cae87b88a813.png)

Could these links also be added to "Table View"? I often want to know more about certain hits in the table from "Table View", and it looks like the only way I can access those details is to look up the same hit in one of the other tabs, or by downloading the results.

**Comment by raphenya** [comment]
@rmzelle Thank you. We will work on updating the view.
