### ISSUE TITLE
Incorrect total for number of (loose) hits?

### ISSUE THREAD

**Issue by rmzelle** [arpcard/rgi#45]
I don't understand why I'm seeing a different number of (loose) hits in a new RGI 5.0.0 search. It shows 260 as "# Loose Hits" in the summary under "Table View", but the table appears to have 14 pages of 25 hits and a 15th with 6 (14*25+6 = 356). The downloaded txt file for the search also has 356 rows of hits. Is this a bug or are (loose) hits grouped somehow to explain the different totals?

![image](https://user-images.githubusercontent.com/77951/57803962-95abb980-7727-11e9-8eb5-205a64c146ea.png)

**Comment by qinghong2019** [comment]
some of them in your txt file are duplicate hits. 260 is the unique hits

**Comment by rmzelle** [comment]
> some of them in your txt file are duplicate hits

Is there any documentation about what duplicate hits represent? Are they redundant BLAST hits against the same reference AMR allele?

**Comment by raphenya** [comment]
@rmzelle Can you email the input file and options used?

**Comment by arpcard** [comment]
Are you still in need of assistance?
If no answer is received in 48 hours, this issue will be closed.
