### ISSUE TITLE
RGI website exits with error when uploading .JSON file 

### ISSUE THREAD

**Issue by Alagarda** [arpcard/rgi#46]
I've been trying to upload a .JSON file created from running rgi main but the online visualization tool won't open it. Furthermore, when using the website to run rgi with the same sequence, an Acinetobacter baumannii reference genome fasta file, it still exits with error. Am I doing anything wrong?

**Comment by raphenya** [comment]
@Alagarda How big is the `json` file? Which version of `rgi` did you use? Can you share both files with us? You can also email it to card@mcmaster.ca. Cheers.

**Comment by arpcard** [comment]
A bug in the JSON uploading has been repaired, please try again.
