### ISSUE TITLE
RGI wheel visualization

### ISSUE THREAD

**Issue by shenfanfan** [arpcard/rgi#47]
I wonder how to generate the RGI wheel visualization through rgi commands

**Comment by arpcard** [comment]
You can load a pre-computed JSON file (created by RGI command-line tools) at the RGI website: https://card.mcmaster.ca/analyze/rgi. Command line does not (yet) support generation of this visualization.

**Comment by shenfanfan** [comment]
Thank you for your answer. I have loaded a pre-computed JSON file of 1.6M in size (created by RGI command-line tools) at the RGI website, but the website is in a waiting state all the time without any outcomes. What's wrong with it?

**Comment by arpcard** [comment]
Looking into this now!

**Comment by raphenya** [comment]
@shenfanfan This is now fixed.
