### ISSUE TITLE
different results through rgi online prediction and rgi in linux

### ISSUE THREAD

**Issue by qinghong2019** [arpcard/rgi#50]
Hi, RGI developer
I upload my contigs onto RGI online to analyze, I got patB, tetO and ErmB with strict. low quanlity/high quanlity. However, when I run the same contig file through rgi linux with local database 3.0.2, In txt file, I got pat B, Tet (W/N/W), ErmB and patA. the identity matching region is 66.49%.  in json file, I got pat B, TetO, ErmB and patA. The same problem when I run other strains. txt file have tet(W/N/W), while json file always have TetO. What happened? why the online miss pat A? thankyou

**Comment by raphenya** [comment]
> I upload my contigs onto RGI online to analyze, I got patB, tetO and ErmB with strict. low quanlity/high quanlity

Please provide options used and if you can email us your inputs and results files

>However, when I run the same contig file through rgi linux with local database 3.0.2, In txt file, I got pat B, Tet (W/N/W), ErmB and patA. 

By default, RGI uses NCBI Blast and RGI online uses DIAMOND. The alignments can be slightly different. Please provide both results files so that we can compare

**Comment by raphenya** [comment]
@qinghong2019 Do you have an update?

**Comment by arpcard** [comment]
Refer to Issue #89 .

Closing this issue unless there are further need of assistance.
