### ISSUE TITLE
FASTA file will not upload in the RGI tool in CARD and give data

### ISSUE THREAD

**Issue by pms29394** [arpcard/rgi#51]
Hello,

I used CARD's RGI last year. I uploaded a FASTA sequence file then and got an output in fasta.txt and fasta.json. Today, I uploaded different FASTA sequence files and could not get any output. I double checked with the FASTA formats I used last year, and I could not any output, although last year I did. Could you help me figure out what is going wrong? I attached  "Today files" below that I have yet to analyze.

LAST YEAR:
     Example of Input:
            CDI_13A11_pro.fasta
      Example of output:
             CDI_13A11_pro.fasta.json
              CDI_13A11_pro.fasta.txt

TODAY:
A new FASTA sequence file: 
        Akk_mu_AA.fa

[AA_Files (1).zip](https://github.com/arpcard/rgi/files/3346754/AA_Files.1.zip)

**Comment by raphenya** [comment]
@pms29394 the issue is with the stop codon character (*) in your FASTA files.
