### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by schorlton** [arpcard/rgi#52]
### Issue:
Tried downloading v5 from releases and building docker image. Build failed due to pip version. After correcting that, there were missing dependencies including bowtie2, samtools, bamtools, bedtools. Finally the cp command for the CARD json was failing.
Also tried cloning repository for latest version. That too failed.

### Solution:
Use different base image, as the repo in the ubuntu phusion repo is outdated and has pip v8 instead of 19. Options include LTS ubuntu or a python base image. Next install additional dependencies in Dockerfile via apt-get or pip. Finally, correct the last cp line for the database json.

**Comment by raphenya** [comment]
@schorlton This is awesome! Thank you. Do you mind sharing your scripts? Cheers.
