### ISSUE TITLE
'rgi bwt' error

### ISSUE THREAD

**Issue by mkazanov** [arpcard/rgi#54]
The execution of `rgi bwt -1 mysample.fq.gz -o myout` failed with the following error:

`Error: could not open /.../rgi-5.0.0/app/_data/card_reference.fasta`

**Comment by raphenya** [comment]
@mkazanov You have to annotate CARD data and load both annotations and card data. The pipeline is like so:

##### Step 1:  Run card annotations using `rgi card_annotation -h` or `rgi  wildcard_annotation -h`

##### Step 2: Load the annotations and card data using `rgi load -h`

##### Step 3: Run rgi using `rgi bwt -h`

**Comment by mkazanov** [comment]
Could you, please, describe it in more details, or give an example, or give a link to documentation how to use `rgi bwt`? Thanks.

**Comment by 7670367** [comment]
I had the same initial error `Error: could not open ...localDB/card_reference.fasta` while running RGI from the quay repository (5.1.0--py36hed695b0_0). This code resolved that error:
```
rgi card_annotation -i /path.to.card.data/card.json 
mv card_database_v3.0.6.fasta localDB/card_reference.fasta
rgi load -i /path.to.card.data/card.json --local
```
However, when I then try to run `bwt` using this code:
```
rgi bwt --read_one /path.to.sample/sample.fastq.gz --aligner bowtie2 --output_file data.file.rgi --local
```
I get these errors:
```
samtools: symbol lookup error: samtools: undefined symbol: hts_open_format
samtools: symbol lookup error: samtools: undefined symbol: hts_open_format
samtools: symbol lookup error: samtools: undefined symbol: sam_index_build3
```
What am I doing wrong?
Thanks
Josh

**Comment by dsurujon** [comment]
@joshua-theisen thanks for the fix with moving the fasta file, `rgi bwt` worked fine for me. Though I'd used bwa as the aligner, not bowtie2. I'm using samtoools v 1.9, htslib v1.9, bwa v 0.7.17-r1188
