### ISSUE TITLE
rgi 4.2.2 issue

### ISSUE THREAD

**Issue by chevrm** [arpcard/rgi#56]
Hey all--

Command:
`rgi main -i $genome -a DIAMOND -n $threads -o $pref --clean`

Comes back with this:
> WARNING 2019-07-29 15:51:43,664 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: homolog
> WARNING 2019-07-29 15:51:43,727 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: overexpression
> WARNING 2019-07-29 15:51:43,759 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: variant

and an empty txt (no ARO assigments, only the header line). Same thing happens without `-a DIAMOND`. Same thing happens whether or not i load a local version of CARD with `rgi load -i $card` beforehand.

I'm on Ubuntu 18.04.2 LTS and installed v4.2.2 with conda. An example input fasta that I'm using is `ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/174/435/GCA_900174435.1_Acinetobacter_baumannii/GCA_900174435.1_Acinetobacter_baumannii_genomic.fna.gz`

Is this a known bug? Maybe I'm missing a dependency?

--Marc

**Comment by raphenya** [comment]
@chevrm I noticed this warning from my last commits. I'm working to resolve this.

**Comment by raphenya** [comment]
@chevrm The issue is with biopython 1.74 not setting `hsp.bits` see [here](https://github.com/biopython/biopython/issues/2179)

**Comment by raphenya** [comment]
@chevrm installing biopython version 1.72 should revolve this issue
