### ISSUE TITLE
OpenSSL libssl issue with blastn with rgi 5.0.0 installed via conda

### ISSUE THREAD

**Issue by boulund** [arpcard/rgi#57]
Hi,

I seem to be having trouble with `blastn` when trying to run `rgi main`. I'm running RGI in a Snakemake workflow using a custom conda environment defined as such:
```
name: resistance
channels:       
  - conda-forge 
  - bioconda    
  - defaults     
dependencies:   
  - rgi=5.0.0   
  - bbmap=38.58 
```

I'm running the following command in my Snakefile:
```
rgi main \
    --input_sequence 2181a.fa \
    --output_file rgi/2181a \
    --input_type contig \
    --num_threads 10 \
    --alignment_tool DIAMOND \
    --local \
    --low_quality \
    --clean \
    2>&1 > 2181a.rgi.log

```
This unfortunately leads to the following error message when trying to run `rgi main`: 
```
blastn: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Process Process-1:4:
Traceback (most recent call last):
  File "/home/ctmr/projects/analyses/102.rgi/.snakemake/conda/f4559059/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ctmr/projects/analyses/102.rgi/.snakemake/conda/f4559059/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ctmr/projects/analyses/102.rgi/.snakemake/conda/f4559059/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/ctmr/projects/analyses/102.rgi/.snakemake/conda/f4559059/lib/python3.6/site-packages/app/RrnaModel.py", line 35, in run
    with open(os.path.join(self.xml_file), 'r') as result_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ctmr/projects/analyses/102.rgi/rgi/2181a.fa.temp.blastRes.rrna.xml'
WARNING 2019-08-06 10:34:19,337 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: homolog
WARNING 2019-08-06 10:34:19,908 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: overexpression
```

I've tried using both `--aligner BLAST` and `--aligner DIAMOND` (as in my example above), but both produce the same kind of error. I'm guessing the rRNA alignment step always uses BLASTN? 

Searching for other issues, I found e.g. #31 that described a similar problem for an older version of RGI. The solution suggested in that issue does not work for me. Redefining my environment to include `openssl=1.0` leads to an `UnsatisfiableError` from conda: 

```
name: resistance
channels:       
  - conda-forge 
  - bioconda    
  - defaults     
dependencies:   
  - rgi=5.0.0   
  - openssl=1.0
  - bbmap=38.58 
```
```
CreateCondaEnvironmentException:
Could not create conda environment from /home/ctmr/projects/analyses/102.rgi/env.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package openssl conflicts for:
rgi=5.0.0 -> seaborn[version='>=0.8.1'] -> statsmodels[version='>=0.5.0'] -> patsy[version='>=0.4.0'] -> scipy -> nu
mpy[version='1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2
.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a,>=1.1.1c,<1.1.2a']
openssl=1.0
```

I appreciate any pointers on how to proceed.

**Comment by boulund** [comment]
I worked around it for now by manually creating a conda environment (`conda env create -f env.yaml`) based on the following `env.yaml` file:
```
name: resistance
channels:       
  - conda-forge 
  - bioconda    
  - defaults     
dependencies:   
  - rgi=5.0.0   
  - bbmap=38.58 
```

Then I manually activated the environment and removed the blast package:
```
$ conda activate resistance
(resistance)$ conda uninstall --force blast
```

I have blast version 2.9.0 installed in my machine, so when running my Snakemake workflow with the manually activated `resistance` conda environment, without `--use-conda` it will fall back through and use my local blast version instead. 

My first plan was to just replace blast in the environment with blast 2.9.0 (which works with `libssl=1.1`), but that led to an UnsatisfiableError due to rgi specifying a strict dependency on `blast=2.6.0`.

**Comment by raphenya** [comment]
@boulund Can you try the same thing from issue #58

**Comment by boulund** [comment]
I'm not exactly sure what you mean, you're referring to using biopython version 1.72 instead?

**Comment by raphenya** [comment]
> I'm not exactly sure what you mean, are you referring to using biopython version 1.72?

Yes, because you were also getting the same warnings in this issue. I suggested this because that's how you can narrow down the problem

> I think the long-term solution is to not pin blast 2.6.0 in the conda rgi package, so that conda can install a more recent version. This is of course only possible if there are no changes in later blast versions that affect the functionality of rgi.

The aim was to have a stable version with specified versions for all dependencies. 

Maybe you can have `rgi` on it's own environment?

**Comment by boulund** [comment]
The outcome of everything is exactly identical when I create an environment with only RGI and biopython 1.72.  This is not that surprising considering that bbmap has no overlapping dependencies with anything that RGI depends on. 

Are there any changes in more recent versions of blast that prevent you from pinning a blast version that is compatible with the latest OpenSSL versions?

**Comment by raphenya** [comment]
> Are there any changes in more recent versions of blast that prevent you from specifying a blast version that is compatible with the latest OpenSSL versions available in conda?

We haven't tested newer versions but we will.

**Comment by boulund** [comment]
I don't understand why no one else has reported this issue. It feels unlikely I am the only one experiencing this when blast 2.6.0 in conda doesn't work with openssl 1.1?

**Comment by raphenya** [comment]
@agmcarthur @bpalcock @fmaguire and @apetkau can you help me test this for me? Cheers.

**Comment by apetkau** [comment]
So, I do not have a solution for you @boulund but I think the reason why it is likely working for others but not for you is if someone has openssl 1.0 installed system-wide.

For example, for me, looking at the libraries linked to `blastn` I get:

```
ldd `which blastn` | grep libssl
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe54ec2c000)
```

In other words, `blastn` is linked to a system version of libssl 1.0.0 (under `/usr/lib`) instead of a conda version.

As a quick solution, could you try installing openssl 1.0.0 system-wide on your machine (on Ubuntu this looks to be package `libssl1.0.0`).

For a better solution (via conda) we'd probably have to look at the dependencies more in-depth.

**Comment by raphenya** [comment]
@apetkau Thank you for looking into this for me. @boulund do you have any updates regarding this issue?

**Comment by boulund** [comment]
I'm running Scientific Linux 7.6 (Nitrogen)  and the only OpenSSL library available via channels approved in my environment is version 1.1. 
RGI 5.0.0 seems to be running just fine with Blast 2.9 though, but I obviously haven't done any extensive testing. You could try running all your tests with a more recent version of blast and update the dependencies for the conda package.

**Comment by imasianxd** [comment]
I just ran into the same problem with RGI 5.0.0 and RGI 4.2.2 on the CEDAR compute Canada cluster. The conda environment is missing the openSSL1.0.0 libraries (libcrypto and libssl)

Since i cannot have a system wide installation of the libraries, the only workaround for now is to uninstall blast from the environment so it falls back to my local copy of blast 2.6.0+ (2016 Dec build) which for some reason doesn't require the openssl libraries.

there are also other libraries that links to system wide paths rather than paths in the conda installation which may or may not lead to the same issue in the future:  
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f468d2a3000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f468d089000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f468ce81000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f468cc65000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f468c963000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f468c596000)

**Comment by chris-rands** [comment]
I have the same issue and am currently using the same work-around (uninstalling blast via conda to fall back on my local blast 2.9 install). #48 appears to be the same but with a different suggested solution

**Comment by raphenya** [comment]
The latest tag 5.1.0--py_1 at https://quay.io/repository/biocontainers/rgi?tab=tags resolves these issues.
