### ISSUE TITLE
Exception TypeError '>=' not supported between NoneType and float model_type: homolog, overexpression

### ISSUE THREAD

**Issue by boulund** [arpcard/rgi#58]
Running RGI as described in #57, with my recent workaround it seems to be running well, but I'm seeing the following errors printed:
```
WARNING 2019-08-06 11:45:14,550 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneTyp
e' and 'float' -> model_type: homolog
WARNING 2019-08-06 11:45:15,021 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneTyp
e' and 'float' -> model_type: overexpression
```
My output files are empty. I don't know if they are empty due to these errors, but it would be strange if the samples didn't contain any resistance genes (microbiome samples).

**Comment by raphenya** [comment]
@boulund This is due to `biopython` bug in version 1.74. There are no issues with version 1.72.

**Comment by boulund** [comment]
Ok, thanks for your reply. However, that doesn't answer my question if this is a problem. Is it related to my output files being empty?

If it is not a problem I guess it doesn't matter that much, but if it is, what should I do to solve it? I tried setting `biopython=1.72` as a dependency in my conda env and conda does seem to be able to resolve such an environment. Will try running RGI with that (with blast manually removed as mentioned in #57) and will report back soon.

**Comment by boulund** [comment]
Thanks for pointing out the issue with biopython. RGI now appears to run just fine with the following environment:

```
  - rgi=5.0.0
  - biopython=1.72
```

I manually removed blast version 2.6.0 from the environment, falling back to my system-wide installation of blast 2.9.0. 

It seems one of my samples actually was devoid of any resistance genes, but several others have now been processed and appears to have produced some output. As far as I'm concerned this issue can be closed now.

**Comment by raphenya** [comment]
@boulund Cheers
