### ISSUE TITLE
Can not see the report of json file

### ISSUE THREAD

**Issue by myshu2017-03-14** [arpcard/rgi#61]
Hi,
 Recently I had run RGI on Linux and generated the result in json format. But when I upload external RGI json results and visualize on the at the CARD Website (https://card.mcmaster.ca/analyze/rgi), the website crashed just with "Whoops, looks like something went wrong."

The result’s [link](https://card.mcmaster.ca/rgi/results/Jn0MsotsCpjQlSHMIAatMEIPCGDFdaGejTuV5I3y)
 
I choosed the Protein sequence option when I uploaded.

What’s more, I can’t open the sample result as well.
https://card.mcmaster.ca/rgi/results/MCNL01
 
What should I do?

Best wishes,
Myshu

**Comment by raphenya** [comment]
@myshu2017-03-14 the web service was not running, please try again.

**Comment by raphenya** [comment]
@myshu2017-03-14 closing this issue, let us know if you still have the same problem. cheers.
