### ISSUE TITLE
float() argument must be a string or a number, not 'NoneType

### ISSUE THREAD

**Issue by zioboe** [arpcard/rgi#62]
Hi get this error after i called rgi main
WARNING 2019-08-07 16:47:47,565 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(1206)
WARNING 2019-08-07 16:47:47,565 : qepA ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
Really,this warning is repeated in more rows with the only exception that the number of model between the round bracket changes in all rows.

**Comment by raphenya** [comment]
@zioboe The warnings are due to biopython version 1.74 bug. Please see #56 and https://github.com/biopython/biopython/issues/2179
