### ISSUE TITLE
metagenomic data

### ISSUE THREAD

**Issue by yjiakang** [arpcard/rgi#64]
Thanks for the wonderful tool, here I have some questions about metagenomic data.
1). After get the heatmap of the AMR genes of samples, I found that the color represents the hit degree -- perfect, strict or no. However, this info does not describe the category of the AMR genes in detail. Would it be possible to show the AMR genes' abundance in samples? 
2). From rows of the heatmap, there are only the abbreviation of the AMR classification, where should I find the detailed info of them?
Thanks in advance.

**Comment by raphenya** [comment]
> Thanks for the wonderful tool, here I have some questions about metagenomic data.
1). After get the heatmap of the AMR genes of samples, I found that the color represents the hit degree -- perfect, strict or no. However, this info does not describe the category of the AMR genes in detail. Would it be possible to show the AMR genes' abundance in samples?

The latest version of RGI (5.0.0) doesn't have heatmap for metagenomic data. The heatmap we have is for genomic data. The categories you can find on CARD downloads section (https://card.mcmaster.ca/download) or searching through the ontology. For example, looking at NDM-1 page (https://card.mcmaster.ca/ontology/36728) there will be `AMR Gene Family`, `Drug Class`, and `Resistance Mechanism`.

> Would it be possible to show the AMR genes' abundance in samples?

We have `rgi bwt` which is used to search for AMR genes in a metagenomic samples by aligning reads to CARD reference AMR data.

> 2). From rows of the heatmap, there are only the abbreviation of the AMR classification, where should I find the detailed info of them?

There are more details on the CARD website for each AMR classification. Let us know of which specific ones you are trying look at.
