### ISSUE TITLE
rgi  cannot recognize * in protein seq？

### ISSUE THREAD

**Issue by uyghbo** [arpcard/rgi#66]
Dear CARD RGI developer team,
When I put my pep sequences，I get this err report, that means I need to delete the * at the end of pep sequences?
ERROR 2019-09-03 10:59:06,706 : invalid protein fasta due to: '*'
ERROR 2019-09-03 10:59:06,706 : invalid fasta

Please suggest how to deal with this issue.
Thank you .

**Comment by raphenya** [comment]
@uyghbo Yes, please remove `*` character on the sequence.

**Comment by fujch7** [comment]
Hi，
    I have a question about this issue. I tried to merge some normal protein sequences and bad sequences(contains asterisk \*) in one  file. And I found that as long as the first sequence does not contain an asterisk, the program can run successfully, although some other sequences contain an asterisk. 
    I'd like to know how this program recognize an asterisk and raise this error. I'm using rgi version 5.1.0.
    Thank you!!!



> 
> 
> @uyghbo Yes, please remove `*` character on the sequence.
