### ISSUE TITLE
Corrupted file? CARD Prevalence, Resistomes, & Variants data v3.0.5

### ISSUE THREAD

**Issue by bigdoyle** [arpcard/rgi#67]
Can't get 3.0.5 to work. 3.0.4 does work for me.

$ rgi wildcard_annotation -i wildcard --card_json <path>/card.json -v 3.0.5 > wildcard_annotation.log 2>&1

$ cat wildcard_annotation.log  #paths edited for brevity
Traceback (most recent call last):
  File "<path>/rgi", line 4, in <module>
    MainBase()
  File "<path>/MainBase.py", line 81, in __init__
    getattr(self, args.command)()
  File "<path>/MainBase.py", line 221, in wildcard_annotation
    self.wildcard_annotation_run(args)
  File "<path>/MainBase.py", line 228, in wildcard_annotation_run
    app.wildcard_annotation.main(args)
  File "<path>/wildcard_annotation.py", line 21, in main
    for row in lines:
  File "<path>/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by devindrown** [comment]
I'm not sure of the root cause, but I solved this by unzipping the contents of the wildcard directory.

**Comment by raphenya** [comment]
@devindrown @bigdoyle The tarball for the CARD Prevalence v3.0.5 has its contents gzipped. You need to decompress to run `rgi wildcard_annotation`. Previous versions didn't have contents gzipped. Moving forward the CARD Prevalence tarballs will be gzipped. Please accept our apologies.

**Comment by jfourquet2** [comment]
Thanks a lot, decompress files and then run rgi wildcard_annotation works !
