### ISSUE TITLE
Warnings with "model_type"

### ISSUE THREAD

**Issue by seanaller** [arpcard/rgi#69]
Hi there,

I'm trying to run rgi (5.0.0) installed through conda.

When I run rgi main, with my contigs, I get the following errors:

```
WARNING 2019-09-26 16:24:57,969 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: overexpression
WARNING 2019-09-26 16:24:58,053 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: homolog
WARNING 2019-09-26 16:24:58,116 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: variant
```

The output file is empty apart from the headers.

Any ideas?

**Comment by oschwengers** [comment]
Hi, 
this is a known bug caused by a wrong Biopyhton version... resume to v1.72 and the error is gone.

**Comment by raphenya** [comment]
@oschwengers Thank you. @seanaller Please see issue: https://github.com/biopython/biopython/issues/2179
