### ISSUE TITLE
How to find the wildcard_database_v3.0.?.fasta to install in rgi

### ISSUE THREAD

**Issue by luongphekidz07** [arpcard/rgi#70]
Dear experts,

I am newbie in rgi installation. I would like how can I find: "wildcard_database_v3.0.2.fasta"

Here is my command line: rgi load --wildcard_annotation /home/lephuong07/anaconda3/envs/rgi/bin/wildcard/*.fastq.gz --wildcard_index /home/lephuong07/anaconda3/envs/rgi/bin/wildcard/index-for-model-sequences.txt.gz --card_annotation /home/lephuong07/anaconda3/envs/rgi/bin/card_database_v3.0.5.fasta --local

Unfortunately, I can find the wildcard reference file and received this: ERROR 2019-10-14 16:36:12,332 : missing wildcard reference file

I used ll to find which files are in the wildcare folder:
total 666080
-rw-r--r-- 1 lephuong07 lephuong07 240221722 Aug 22 22:14 61_kmer_db.json.gz
-rw-r--r-- 1 lephuong07 lephuong07 400026013 Aug 22 22:14 all_amr_61mers.txt.gz
-rw-r--r-- 1 lephuong07 lephuong07   4989277 Aug 22 22:14 card-genomes.txt.gz
-rw-r--r-- 1 lephuong07 lephuong07     82774 Aug 22 22:14 card_prevalence.txt.gz
-rw-r--r-- 1 lephuong07 lephuong07   9307764 Aug 22 22:14 index-for-model-sequences.txt.gz
drwxrwxr-x 2 lephuong07 lephuong07      4096 Oct 14 16:33 localDB
-rw-r--r-- 1 lephuong07 lephuong07  20725768 Aug 22 22:14 nucleotide_fasta_protein_homolog_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07     37946 Aug 22 22:14 nucleotide_fasta_protein_overexpression_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07   1830854 Aug 22 22:14 nucleotide_fasta_protein_variant_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07     39991 Aug 22 22:14 nucleotide_fasta_rRNA_gene_variant_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07   4371610 Aug 22 22:14 protein_fasta_protein_homolog_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07     16091 Aug 22 22:14 protein_fasta_protein_overexpression_model_variants.fasta.gz
-rw-r--r-- 1 lephuong07 lephuong07    377343 Aug 22 22:14 protein_fasta_protein_variant_model_variants.fasta.gz

Could you please give me the instructions? 
Thank you very much,

Yours sincerely,
Le Phuong.

**Comment by ziejan** [comment]
At first you have to download Wildcard data and uncompress to the folder wildcard:
wget -O wildcard_data.tar.bz2 https://card.mcmaster.ca/latest/variants
`mkdir -p wildcard
tar -xvf wildcard_data.tar.bz2 -C wildcard
run 
Then uncompress everythng inside the wildcard directory:
gunzip wildcard/*.gz`

Then run:
`rgi wildcard_annotation -i wildcard --card_json card.json -v 3.0.5 > wildcard_annotation.log 2>&1`

Then you will see that yout wildcard_database.fasta has been created in your current directory.
Hope this helps...

**Comment by raphenya** [comment]
@ziejan That's correct. Thank you.
