### ISSUE TITLE
Why the result of generating Perfect or Strict hits for a set of protein sequences include Loose hits?

### ISSUE THREAD

**Issue by jy3412** [arpcard/rgi#73]
After I generating Perfect or Strict hits for a set of protein sequences with this code "rgi main --input_sequence /path/to/protein.fasta --output_file /path/to/output_file --input_type protein -d wgs --clean",  I found  the result  inculde "Loose" hit，but I did not use the parameter “--include_loose” ，so under that premise, how did this happen?
![image](https://user-images.githubusercontent.com/34858637/66895859-4a733b00-f026-11e9-8c9b-a02192696e69.png)

**Comment by raphenya** [comment]
@jy3412 We will look into this. If you are able to share the input file at card@mcmaster.ca that will great. Otherwise will try to identify this bug, using the command stated. Cheers.

**Comment by jy3412** [comment]
Thank you for your reply. 
Please see the attachment for my input file. And the command what I run was  
   "rgi main -t protein -i input.fa -o output.fa -d wgs --clean" .

[input.zip](https://github.com/arpcard/rgi/files/3817626/input.zip)
 Looking forward to your reply.

**Comment by raphenya** [comment]
@jy3412 I ran your sample with CARD data version 3.0.7 and RGI version 5.1.0 as follows:

#### Command
```rgi main -t protein -i input.fa -o output.fa -d wgs --clean --debug```
#### Results
```
cat output.fa.txt | cut -f6,9
Cut_Off	Best_Hit_ARO
Strict	adeF
Strict	aadA9
Strict	aadA6/aadA10
Strict	mexN
Strict	sul4
Perfect	TEM-116
Strict	Klebsiella pneumoniae KpnF
Strict	CRP
Strict	adeF
Strict	Escherichia coli EF-Tu mutants conferring resistance to Pulvomycin
```
None of `Loose` hits were produced.

Which versions for CARD data and RGI software did you use?

**Comment by jy3412** [comment]
I used RGI_4.0.3  and  CARD_data_2.0.1 .

**Comment by arpcard** [comment]
Hello @jy3412 ,

Please use the latest CARD data and RGI-5.1.0.
Let us know if there are any further issues.
I will be closing this issue for now. Do not hesitate to open a  new issue if there are any further problems.

All the best.
-------
William Huynh, CARD Curator-Developer
