### ISSUE TITLE
Empty file output

### ISSUE THREAD

**Issue by darwinbandoy** [arpcard/rgi#75]
I am running rgi on Macbook Pro MacOS Mojave 10.14 and I am getting this warning: 

WARNING 2019-10-29 23:13:53,576 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: homolog

I also do not get any results on my output (which I do when I use the website).

**Comment by raphenya** [comment]
> WARNING 2019-10-29 23:13:53,576 : Exception: <class 'TypeError'> -> '>=' not supported between instances of 'NoneType' and 'float' -> model_type: homolog

This might be due this issue #56 

> I also do not get any results on my output (which I do when I use the website).

You can share the session on the website so that we can look at your inputs and options used.
