### ISSUE TITLE
Exception : <class 'KeyError'> when running rgi main

### ISSUE THREAD

**Issue by ziejan** [arpcard/rgi#78]
I'm getting a lot of errors like the following:
_Exception : <class 'KeyError'> -> '4766' -> Model(2914) missing in database. Please generate new database_
when running 
`rgi main --input_sequence input_genome.fasta --output_file card-out --input_type contig`
All RGI tests `pytest -v -rxs` are succesfull.
`rgi database -v` outputs 3.0.7 so the database seems to be loaded succesfully.
I can't figure out what the problem is...

With ncbi-blast Version 2.9+ I don't get any results and with ncbi-blast Version 2.6+ I get results but still those errors and less results compared to a working card on another computer.
I'm using python 3.6

looks like a python error to me?

**Comment by raphenya** [comment]
@ziejan It look like you have an old blast database for card data. Every time you load a new `card.json` use `rgi clean` to remove old databases. In this case, a sequence with id `4766` was removed and replaced with a new sequence for model id 2914. Let us know if that's not the case. Cheers.

**Comment by ziejan** [comment]
Thanks for your answer.
Unfortunately this didn't solve the problem. I still get the same errors. Here is what I did:
`sudo rgi clean`
`sudo rgi database -v`  -> Error: no databases found in data path: /usr/local/lib/python3.6/dist-packages/app/_data
`sudo rgi load --card_json card.json`
`sudo rgi database -v` --> 3.0.7

**Comment by ziejan** [comment]
Is there nothing else I can do? I still have the problem and don't know how to solve it.

**Comment by raphenya** [comment]
We can try to narrow down the issue this way:

#### step 1:

-  install RGI version 5.1.0
-  download CARD data version 3.0.7

#### step 2:

- load `card.json` using `--local` flag

- ```rgi load -i /path/to/card.json --local --debug > load.log 2>&1```

- share the load.log file

#### step 3:
- run `rgi main` using local db
- ```rgi main --input_sequence input_genome.fasta --output_file card-out --input_type contig --debug --local > rgi_run.log 2>&1```
- share the rgi_run.log
- share `localDB/proteindb.fsa`
- also, run `tree` inside `localDB` and share the file list

**Comment by ziejan** [comment]
Hey.
Thanks for your help.
I don't know what happened but now it works with python 3.8. The only thing I changed is the loading command. I used `sudo rgi load --card_json card.json` and you told me to use `rgi load -i /path/to/card.json`

I don't know if that changes anything. However, it's working now and I appreciate your help. Thank you.

**Comment by AdeBC** [comment]
> Hey. Thanks for your help. I don't know what happened but now it works with python 3.8. The only thing I changed is the loading command. I used `sudo rgi load --card_json card.json` and you told me to use `rgi load -i /path/to/card.json`
> 
> I don't know if that changes anything. However, it's working now and I appreciate your help. Thank you.

Thanks!

This also works for me!

**Comment by Silverfoxcome** [comment]
> We can try to narrow down the issue this way:
> #### step 1:
> 
>     * install RGI version 5.1.0
> 
>     * download CARD data version 3.0.7
> 
> 
> #### step 2:
> 
>     * load `card.json` using `--local` flag
> 
>     * `rgi load -i /path/to/card.json --local --debug > load.log 2>&1`
> 
>     * share the load.log file
> 
> 
> #### step 3:
> 
>     * run `rgi main` using local db
> 
>     * `rgi main --input_sequence input_genome.fasta --output_file card-out --input_type contig --debug --local > rgi_run.log 2>&1`
> 
>     * share the rgi_run.log
> 
>     * share `localDB/proteindb.fsa`
> 
>     * also, run `tree` inside `localDB` and share the file list

Hi!!!

Thanks a lot for this useful tool!!!
I installed rgi via conda. 
I run it locally and in that way, it works perfectly, but I wanted to load the database system wide so I downloaded the `card.json` and ran the command:
`rgi load --card_json card.json`

Then I ran `rgi main` with 1 genome, without the `--local` flag:

`rgi main --input_sequence 210.6021.fna --output_file 210.6021_rgi3_sw --input_type contig --clean`

The output is not the same as when I ran it with the --local flag (only 1 result and the rest is truncated). And I got a lot of warnings:

> INFO 2022-08-22 18:24:42,911 : /media/koala/Main/mishell/snippy-multi/t5_res/210.6021/210.6021.fna => None
> INFO 2022-08-22 18:24:42,998 : valid nucleotide fasta: {'A': 69994, 'T': 69852, 'G': 41903, 'C': 47135, 'N': 0, 'U': 0, 'W': 0, 'S': 0, 'M': 0, 'K': 0, 'R': 0, 'Y': 0, 'B': 0, 'D': 0, 'H': 0, 'V': 0}
> INFO 2022-08-22 18:24:42,999 : blast DB exists
> INFO 2022-08-22 18:24:42,999 : diamond DB exists
> INFO 2022-08-22 18:24:43,011 : minimum sequence length: 210, maximun sequence length 228884, number of sequences: 42
> INFO 2022-08-22 18:24:51,318 : work with file /media/koala/Main/mishell/snippy-multi/t5_res/210.6021/210.6021.fna.temp.contig.fsa
> INFO 2022-08-22 18:24:51,319 : run blast
> INFO 2022-08-22 18:25:16,759 : set blast xml file: [/media/koala/Main/mishell/snippy-multi/t5_res/210.6021/210.6021.fna.temp.contig.fsa.blastRes.xml]
> INFO 2022-08-22 18:25:16,759 : run filter
> INFO 2022-08-22 18:25:16,772 : homolog_worker started...
> INFO 2022-08-22 18:25:16,777 : variant_worker started...
> INFO 2022-08-22 18:25:16,788 : overexpression_worker started...
> INFO 2022-08-22 18:25:16,792 : rRNA process: contig
> INFO 2022-08-22 18:25:16,793 : rRNA process
> INFO 2022-08-22 18:25:16,862 : create_db_query
> INFO 2022-08-22 18:25:16,862 : DB from user query
> INFO 2022-08-22 18:25:16,978 : blast_reference_to_db_query
> WARNING 2022-08-22 18:25:17,225 : Exception : <class 'KeyError'> -> '253' -> Model(837) missing in database. Please generate new database.
> WARNING 2022-08-22 18:25:17,225 : Exception : <class 'KeyError'> -> '253' -> Model(837)
> WARNING 2022-08-22 18:25:17,225 : vatH ---> hsp.bits: 25.0238 <class 'float'> ? <class 'str'>
> WARNING 2022-08-22 18:25:17,226 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.
> WARNING 2022-08-22 18:25:17,226 : Exception : <class 'KeyError'> -> '475' -> Model(1817)
> WARNING 2022-08-22 18:25:17,226 : vgaB ---> hsp.bits: 25.409 <class 'float'> ? <class 'str'>
> WARNING 2022-08-22 18:25:17,227 : Exception : <class 'KeyError'> -> '1381' -> Model(47) missing in database. Please generate new database.
> WARNING 2022-08-22 18:25:17,227 : Exception : <class 'KeyError'> -> '1381' -> Model(47)
> WARNING 2022-08-22 18:25:17,227 : OXA-60 ---> hsp.bits: 22.7126 <class 'float'> ? <class 'str'>
> WARNING 2022-08-22 18:25:17,227 : Exception : <class 'KeyError'> -> '344' -> Model(1210) missing in database. Please generate new database.
> WARNING 2022-08-22 18:25:17,227 : Exception : <class 'KeyError'> -> '344' -> Model(1210)
> WARNING 2022-08-22 18:25:17,229 : novA ---> hsp.bits: 22.7126 <class 'float'> ? <class 'str'>
> WARNING 2022-08-22 18:25:17,279 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.
> WARNING 2022-08-22 18:25:17,279 : Exception : <class 'KeyError'> -> '475' -> Model(1817)
> WARNING 2022-08-22 18:25:17,279 : vgaB ---> hsp.bits: 40.0466 <class 'float'> ? <class 'str'>
> WARNING 2022-08-22 18:25:17,279 : Exception : <class 'KeyError'> -> '475' -> Model(1817) missing in database. Please generate new database.

I did what you said:
`rgi load -i ~/biotools/rgi/card.json --local --debug > load.log 2>&1`
[load.log](https://github.com/arpcard/rgi/files/9398245/load.log)

Then I ran:
`rgi main --input_sequence 210.6021.fna --output_file card-out --input_type contig --debug --local > rgi_run.log 2>&1`
[rgi_run.log](https://github.com/arpcard/rgi/files/9398248/rgi_run.log)

I'm sharing `localDB/proteindb.fsa` ending with .txt because github doesn't accept the .fsa format:
[proteindb.fsa.txt](https://github.com/arpcard/rgi/files/9398263/proteindb.fsa.txt)

And I ran the command:
`tree localDB`
[tree_localDB.txt](https://github.com/arpcard/rgi/files/9398270/tree_localDB.txt)

Please, I hope you can help me.

Thanks a lot in advance :)
