### ISSUE TITLE
only loose results reported 

### ISSUE THREAD

**Issue by bitcometz** [arpcard/rgi#81]
hello, I run the following commonds with 940 proteins sequences:
rgi main -t protein -i ./input.fa -o input.fa  -d wgs --clean

And no reports were found.
Then I add the paramter: "--include_loose"

Then about 800 items were reported:

ORF_ID	Contig	Start	Stop	Orientation	Cut_Off	Pass_Bitscore	Best_Hit_Bitscore	Best_Hit_ARO	Best_Identities	ARO	Model_type	SNPs_in_Best_Hit_ARO	Other_SNPs	Drug Class	Resistance Mechanism	AMR Gene Family	Predicted_DNA	Predicted_Protein	CARD_Protein_Sequence	Percentage Length of Reference Sequence	ID	Model_ID
CTL_1_402					Loose	1200	20.0162	tet(44)	47.37	3000556	protein homolog model	n/a	n/a	tetracycline antibiotic	antibiotic target protection	tetracycline-resistant ribosomal protection protein		SSYALLYYFLNFKTGEVITSALGMHHKAVCKNSMELSVTINVQPIF	MKIINIGILAHVDAGKTTLTESLLYTSGAILELGSVDKGTTRTDTMFLERQRGITIQAAVTSFNWNDYKINIVDTPGHTDFITEVYRSLSVLDGAILVISAKDGVQAQTRILFHALQKMNIPTIIFINKIDQDGINLNNIYQNIKEKLSNDIIVMQNVTLTPEISIKNIIDLDDWDPVISKNDKLLEKYIVGEKLTIQELMYEEYRCVKKGSLFPIYHGSARNNIGTQQLIEAISNLFCSEMNENDSELCGRVFKIEYTDHKQRLVYLRLYSGTLHLRDTIILPEKKKVKLTEIYIPSNGEMIQTKTVCSGDIFIIPNNTLRLNDIIGNEKLLPCNVWNDKTVPILRTRIEPIKIEEREKLLDALTEIADTDPLLRYYVDTITHEIIISFLGTVQLEVICSLLIEKYHINIRIEDPTVIYLEKPLQKADYTIHIEVPPNPFWASIGLSITPLPIGSGIQYESKVSLGYLNQSFQNAVREGINYGLEQGLYGWEVTDCKICFEYGVYYSPVSTPSDFRFLAPIVLEQTLKKAGTQLLEPYLSFILFTPQGYFSRAYKDAQKHCAIIETSQSKNDEVIFTGHIPVRCINEYRNTLTLYTNGQAVFLTELKDYQIATCEPVIQSRRPNNRIDKVRHMFNKKEN	7.19	gnl|BL_ORD_ID|1104|hsp_num:0	1171
CTL_1_403					Loose	1100	21.557	salA	28.95	3003749	protein homolog model	n/a	n/a	macrolide antibiotic; lincosamide antibiotic; streptogramin antibiotic; tetracycline antibiotic; oxazolidinone antibiotic; phenicol antibiotic; pleuromutilin antibiotic	antibiotic target protection	ABC-F ATP-binding cassette ribosomal protection protein		METLKPLVTTDGYAKCCSCYQTKTNQNKPKQTQRKQTKLNQAKPNQTKPNPNQTQPKQTKTNQTKQKENKQNETTVWWLWWFQ	MLFLFEEKALEVEHKVLIPELTFSIEDHEHLAIVGVNGVGKSTLLKVIHQDQSVDSAMMEQDLTPYYDWTVMDYIIESYPEIAKIRLQLNHTDMINKYIELDGYIIEGEIVTEAKKLGIKEEQLEQKISTLSGGEQTKVSFLKVKMSKASLLLIDEPTNHMDLEMKEWLTKAFKQEQRAILFVSHDRTFLNETPDAILELSLDGAKKYIGKYDKYKQQKDIEHETLKLQYEKQQKEQAAIEETIKKYKAWYQKAEQSASVRSPYQQKQLSKLAKRFKSKEQQLNRKLDQEHIPNPHKKEKTFSIQHHNFKSHYLVQFNHVSFAYDNRKIFDDVSFYIKRNQNVIVEGRNGTGKSTLIKLILGELEPTKGDITVHPELEIGYFSQDFENLNMHHTVLDEILEIPEMKEADARTILASFYFDKDRINDVVETLSMGEKCRLQFVKLYFSNPHIMILDEPTNYFDIGMQENIIQLIQSFQGSVLIVSHDNYFKSQIKDQTWTIKNHQMTHENVQVKDPINTESMKHHLKELEQYTDERNRETEF	15.34	gnl|BL_ORD_ID|2106|hsp_num:0	2265

Is this normal? or is it something wrong with my database.
I have followed the intructions to load the database:
https://github.com/arpcard/rgi

Thanks

**Comment by raphenya** [comment]
This may mean you have partial or distant homologs proteins.
