### ISSUE TITLE
warnings of Nonetype 

### ISSUE THREAD

**Issue by xmkbio-huanwu** [arpcard/rgi#82]
Hi guys,
I run rgi main on contigs, the executable reported lots of warnings as follows:
WARNING 2019-12-24 09:56:45,172 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(139)
WARNING 2019-12-24 09:56:45,172 : QnrB10 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2019-12-24 09:56:45,172 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(539)
WARNING 2019-12-24 09:56:45,172 : QnrB59 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2019-12-24 09:56:45,172 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(1993)
WARNING 2019-12-24 09:56:45,172 : QnrB74 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2019-12-24 09:56:45,172 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(2028)
WARNING 2019-12-24 09:56:45,172 : QnrB43 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2019-12-24 09:56:45,172 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(2028)
Any idea? Will will lose some hits?
Best,
Huan

**Comment by ptapiar** [comment]
Any solutions for this problem?

**Comment by raphenya** [comment]
@xmkbio-huanwu @ptapiar please see #62
