### ISSUE TITLE
 Exception : <class 'TypeError'> 

### ISSUE THREAD

**Issue by ptapiar** [arpcard/rgi#85]
I am getting a lot warning and my output is empty:

WARNING 2020-02-04 23:33:22,868 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(32)
WARNING 2020-02-04 23:33:22,868 : DHA-15 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2020-02-04 23:33:22,868 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(1792)
WARNING 2020-02-04 23:33:22,868 : DHA-20 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2020-02-04 23:33:22,869 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(622)
WARNING 2020-02-04 23:33:22,869 : DHA-7 ---> hsp.bits: None <class 'NoneType'> ? <class 'str'>
WARNING 2020-02-04 23:33:22,869 : Exception : <class 'TypeError'> -> float() argument must be a string or a number, not 'NoneType' -> Model(2828)

**Comment by raphenya** [comment]
@ptapiar Please see #62
