### ISSUE TITLE
Encounter with the problem while trying to build the wildcard database for RGI program

### ISSUE THREAD

**Issue by jayminz** [arpcard/rgi#86]
I encounter with some problem while trying to build the wildcard database using the command line "rgi wildcard_annotation -i wildcard --card_json /path/to/card.json -v version_number > wildcard_annotation.log 2>&1". I attach the wildcard_annotation.log here as I think it refers to my problem. Can anyone know how to fix this? I don't have much knowledge about the code and bioinformatics. but I literally want to use this program for my research.

> Traceback (most recent call last):
>   File "/home/chanwit/.local/bin/rgi", line 4, in <module>
>     MainBase()
>   File "/home/chanwit/.local/lib/python3.6/site-packages/app/MainBase.py", line 81, in __init__
>     getattr(self, args.command)()
>   File "/home/chanwit/.local/lib/python3.6/site-packages/app/MainBase.py", line 221, in wildcard_annotation
>     self.wildcard_annotation_run(args)
>   File "/home/chanwit/.local/lib/python3.6/site-packages/app/MainBase.py", line 228, in wildcard_annotation_run
>     app.wildcard_annotation.main(args)
>   File "/home/chanwit/.local/lib/python3.6/site-packages/app/wildcard_annotation.py", line 21, in main
>     for row in lines:
>   File "/usr/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
[wildcard_annotation.log](https://github.com/arpcard/rgi/files/4204387/wildcard_annotation.log)

Thank you for your help.

Jay.
[wildcard_annotation.log](https://github.com/arpcard/rgi/files/4204413/wildcard_annotation.log)

**Comment by MasterMax-phd** [comment]
This has been solved here already, note that you have to decompress everything and remove the compressed files to not get the decode error
https://github.com/arpcard/rgi/issues/70#issuecomment-548803889

**Comment by janine521** [comment]
I have the same problem as you. Have you solved it？

**Comment by raphenya** [comment]
@MasterMax-phd Thank you.
