### ISSUE TITLE
Average length Coverage is shorter than the read length for BWT rgi

### ISSUE THREAD

**Issue by mettejoe** [arpcard/rgi#87]
Thanks for a nice addition to the RGI family. I believe RGI bwt will be really useful for the community. I just have one question.

I have been running RGI bwt with wildcard on 150bp paired end reads. In a lot cases I get a Average length coverage (bp) of around 20. How can it be shorter than the read length (In cases where there is a least one completely mapped read). Maybe I misunderstand the definition of Average length coverage, but intuitively the minimum should be the read length.

**Comment by raphenya** [comment]
@mettejoe The average length coverage is calculated by averaging for all reads that are mapped to the reference. So, if you have 1 read (150bp) mapping completely and have other reads mapping less than 150bp this will drive the average length coverage down.
