### ISSUE TITLE
KeyError: 'snp' with unknown cause. 

### ISSUE THREAD

**Issue by mahesh-panchal** [arpcard/rgi#93]
Hi, 

I was wondering if you could help me diagnose what the error with my run is. 

RGI is being run inside a singularity container with the following packages installed via miniconda3:
`python=3.6 rgi=5.1.0 openssl=1.1.1e`.

The command being run is:
```
  rgi load --card_json card.json --local
  rgi main -i DA34821_pseudomolecule.fasta -o DA34821_pseudomolecule-rgi \
      -n 20 --local --input_type contig \
      --clean --low_quality
```

The error being thrown is:
```
  Traceback (most recent call last):
    File "/opt/conda/bin/rgi", line 4, in <module>
      MainBase()
    File "/opt/conda/lib/python3.6/site-packages/app/MainBase.py", line 81, in __init__
      getattr(self, args.command)()
    File "/opt/conda/lib/python3.6/site-packages/app/MainBase.py", line 86, in main
      self.main_run(args)
    File "/opt/conda/lib/python3.6/site-packages/app/MainBase.py", line 120, in main_run
      rgi_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/app/RGI.py", line 197, in run
      self.create_databases()
    File "/opt/conda/lib/python3.6/site-packages/app/RGI.py", line 191, in create_databases
      db_obj.build_databases()
    File "/opt/conda/lib/python3.6/site-packages/app/Database.py", line 25, in build_databases
      self.write_fasta_from_json_rna()
    File "/opt/conda/lib/python3.6/site-packages/app/Database.py", line 166, in write_fasta_from_json_rna
      snpList = [j[i]['model_param']['snp']['param_value'][k] for k in j[i]['model_param']['snp']['param_value']]
  KeyError: 'snp'

```
Regards,
Mahesh.

**Comment by raphenya** [comment]
The model https://card.mcmaster.ca/ontology/43123 is missing a mutation parameter, so this happens when the database is being built. This model should be fixed in the next card data release.

**Comment by mahesh-panchal** [comment]
Thank you.

When is the next release estimated to be made available?

Is there anything I can do to make rgi function in the mean time? Is it possible to revert to an older database for example?

**Comment by raphenya** [comment]
@mahesh-panchal The current data 3.0.8 would work just fine, the model with missing parameter won't be added to the database. After the database is built the error should go away. Let us know if you still get the same error. Cheers.

**Comment by mahesh-panchal** [comment]
Hi @raphenya . Then I'm not understanding the basic running instructions. How should I modify my command to build the database?

**Comment by raphenya** [comment]
@mahesh-panchal After a fresh install running command `rgi main -i ...` the database would be built and it will show the error message with `snp` keyerror (then ignore this). Then running `rgi main -i ...` command the error message won't show up because the database is already built with the model I mentioned above. If you are not working with TB isolates you should be ok as the model missing parameters is for TB mutations.

**Comment by hongssy** [comment]
hi @raphenya
I got the same error with rgi=5.1.0  database=3.0.8. when i run  "rgi main -i ..."   it will creat "protein.db.dmnd proteindb.fsa protein.db.phr protein.db.pin protein.db.psq rnadb.fsa" , so my question is how can i creat these files without "rgi main -i ..." , By other command?

**Comment by mahesh-panchal** [comment]
Thanks @raphenya ,

My script now looks like this (for reference):
```
#!/usr/bin/env bash -euo pipefail
rgi load --card_json card.json --local
# Build database and break (See https://github.com/arpcard/rgi/issues/93)
set +e
echo "RGI build database and break"
rgi main -i DA34821_pseudomolecule.fasta -o DA34821_pseudomolecule-rgi \
    -n 4 --local --input_type contig \
    --clean --low_quality
set -e
echo "Run RGI"
rgi main -i DA34821_pseudomolecule.fasta -o DA34821_pseudomolecule-rgi \
    -n 4 --local --input_type contig \
    --clean --low_quality
```

Running `rgi main -i ...` twice works for me. 

@hongssy Run your commands like I have. The first `rgi main -i ...` creates the "protein.db.dmnd proteindb.fsa protein.db.phr protein.db.pin protein.db.psq rnadb.fsa" files. The second time you use `rgi main -i ...` it doesn't try to recreate them.

**Comment by feihongloveworld** [comment]
> Thanks @raphenya ,
> 
> My script now looks like this (for reference):
> 
> ```
> #!/usr/bin/env bash -euo pipefail
> rgi load --card_json card.json --local
> # Build database and break (See https://github.com/arpcard/rgi/issues/93)
> set +e
> echo "RGI build database and break"
> rgi main -i DA34821_pseudomolecule.fasta -o DA34821_pseudomolecule-rgi \
>     -n 4 --local --input_type contig \
>     --clean --low_quality
> set -e
> echo "Run RGI"
> rgi main -i DA34821_pseudomolecule.fasta -o DA34821_pseudomolecule-rgi \
>     -n 4 --local --input_type contig \
>     --clean --low_quality
> ```
> 
> Running `rgi main -i ...` twice works for me.
> 
> @hongssy Run your commands like I have. The first `rgi main -i ...` creates the "protein.db.dmnd proteindb.fsa protein.db.phr protein.db.pin protein.db.psq rnadb.fsa" files. The second time you use `rgi main -i ...` it doesn't try to recreate them.

first time get error，rnadb.fsa was Incomplete；Incomplete files may affect the results from RNAdb ！！！
