### ISSUE TITLE
what‘s mean of NCBI_taxonomy_cvterm_id and category_aro_cvterm_id

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#95]
hi sir:
     what's mean of  category_aro_cvterm_id and NCBI_taxonomy_cvterm_id in card.json,

**Comment by arpcard** [comment]
Hi @feihongloveworld ,
cvterm_id are how terms relate to each other in CARD.

http://gmod.org/wiki/Chado_Tables#Table:_cvterm

More can be read here.

In this regard, category_aro_cvterm_id and NCBI_taxonomy_cvterm_id would relate our item, a gene,  to a cvterm identifier pertaining to the ARO category and the NCBI taxonomy.

Cheers.

-----
William Huynh, CARD Curator-Developer
