### ISSUE TITLE
how to  get index file with baits information for baits_annotation？

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#96]
hi sir：
      i download card-baits.tar.bz2，but could not found index file with baits information which need in 
baits_annotation step,What should I do?

**Comment by huynhw1** [comment]
Hey there @feihongloveworld !

The index file can be found when downloading the Resistomes and Variants files on the CARD website at:
https://devcard.mcmaster.ca/download

Thank you!

-------

William Huynh, CARD Curator-Developer
