### ISSUE TITLE
bug in BWT.extract_alignments_with_length

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#98]
hi,
      there is a bug in BWT.extract_alignments_with_length;
     "length" and "map_quality" could not be sent to cmd.
"""
                cmd="bamtools filter -in {input_bam} -out {output_bam} ".format(
                        input_bam=self.output_bam_sorted_file,
                        output_bam=self.sorted_bam_sorted_file_length_100,
                        length=length,
                        map_quality=map_quality
                )    
"""

**Comment by arpcard** [comment]
Hello @feihongloveworld ,

Is this still an issue with the latest version of RGI?

Please respond so I know whether to close this issue or further investigate this bug.
If this issue still persists, please send us your input file, command-line input and error log.
Any extra information will help us diagnose the issue.

All the best.
------
William Huynh, CARD Curator-Developer
