### ISSUE TITLE
bug in BWT.get_model_id

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#99]
hi,
      there is a bug in BWT.get_model_id;
     when the card_database_v3.0.8.fasta header line as "gb|GQ343019|ARO:3002999|ID:2|Name:CblA-1" from "rgi card_annotation -i card.json --ncbi" ;the BWT.get_model_id function could not get mdel_id;
code as below
"""
      def get_model_id(self, models_by_accession, alignment_hit):
                model_id = "" 
                if alignment_hit[0:22] == "Prevalence_Sequence_ID" or alignment_hit[0:4] == "ARO:":
                        print(alignment_hit)
                        print(alignment_hit.split("|")[1])
                        model_id = alignment_hit.split("|")[1].split(":")[1]
                else:
                        accession = alignment_hit.split("|")[4].split(":")[1]   ### bug2  extract genename not accession gb|L06161|ARO:3002538|ID:51|Name:AAC(3)-IIIc
                        try: 
                                model_id = models_by_accession[accession]["model_id"]
                        except Exception as e:
                                logger.warning("missing aro accession: {} for alignment {} -> {}".format(accession,alignment_hit,e))
                return model_id

"""

**Comment by arpcard** [comment]
Hello @feihongloveworld ,

Is this still an issue with the latest version of RGI?
Please respond so I know whether to close this issue or further investigate this bug.

If this issue still persists, please send us your input file, command-line input and error log.
Any extra information will help us diagnose the issue.

All the best.
-------
William Huynh, CARD Curator-Developer
